// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ArtifactProvenance
 */
export type ArtifactProvenance = {
    /**
     * Artifact Id
     */
    artifact_id: string;
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Expected Kind
     */
    expected_kind: 'tracked_seed' | 'local_operational';
    /**
     * Load Verification Status
     */
    load_verification_status: 'not_verified' | 'verified';
    /**
     * Observed Status
     */
    observed_status: 'ok' | 'local_override' | 'unregistered_local' | 'hash_mismatch' | 'missing_required' | 'local_artifact_missing_ci' | 'expected_hash_missing';
    /**
     * Path
     */
    path: string;
    /**
     * Pointer Status
     */
    pointer_status: 'referenced' | 'pointer_missing' | 'pointer_malformed' | 'pointer_mismatch' | 'not_applicable';
    /**
     * Promotion Status
     */
    promotion_status: 'active' | 'candidate' | 'parked';
    /**
     * Serving Allowed
     */
    serving_allowed: boolean;
    /**
     * Severity
     */
    severity: 'info' | 'caveat' | 'integrity';
};

/**
 * CapacityCandidate
 *
 * One roster player surfaced in the capacity-ordered review list.
 *
 * Raw value fields are re-joined from the universe PVO (the cut engine exposes
 * only percentile/dvs). Each field carries a provenance status so a consumer
 * can tell an "ok" join from an "unavailable"/"pre_model"/"unknown_position"
 * one without guessing from a null.
 */
export type CapacityCandidate = {
    /**
     * Candidate Source
     */
    candidate_source: 'forced_review' | 'capacity_ordered';
    /**
     * Cut Priority
     */
    cut_priority: number;
    /**
     * Dvs
     */
    dvs: number | null;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Median Projection 2Y
     */
    median_projection_2y: number | null;
    /**
     * Position
     */
    position: string;
    /**
     * Raw Xvar
     */
    raw_xvar: number | null;
    /**
     * Sleeper Player Id
     */
    sleeper_player_id: string;
    /**
     * Value Field Status
     */
    value_field_status: {
        [key: string]: string;
    };
    /**
     * Xvar Pct
     */
    xvar_pct: number | null;
};

/**
 * CapacityHealth
 *
 * League-shape capacity summary for David's roster.
 *
 * `total_capacity_cuts_required` and `active_slot_overflow` are DISTINCT:
 * the former is roster-wide (players over total capacity, incl. reserve/taxi),
 * the latter is active-slot pressure (non-reserve, non-taxi players over the
 * active starter slots). A roster can be active-slot heavy while total-capacity
 * compliant (stash slots absorb the excess).
 */
export type CapacityHealth = {
    /**
     * Active Slot Overflow
     */
    active_slot_overflow: number;
    /**
     * By Slot Class
     */
    by_slot_class: {
        [key: string]: number;
    };
    /**
     * Reserve Unrestricted
     */
    reserve_unrestricted: boolean;
    /**
     * Total Capacity
     */
    total_capacity: number;
    /**
     * Total Capacity Cuts Required
     */
    total_capacity_cuts_required: number;
    /**
     * Total Players
     */
    total_players: number;
};

/**
 * CaptureHealthErrorResponse
 */
export type CaptureHealthErrorResponse = {
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Error
     */
    error: string;
    /**
     * Message
     */
    message: string;
};

/**
 * CaptureHealthResponse
 */
export type CaptureHealthResponse = {
    /**
     * Checked At
     */
    checked_at: string;
    /**
     * Config Version
     */
    config_version: number;
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Overall Status
     */
    overall_status: 'ok' | 'degraded';
    /**
     * Stores
     */
    stores: Array<StoreHealth>;
};

/**
 * CohortMetric
 *
 * Within-position rank-accuracy metrics for one position cohort. ``status`` is
 * ``power_floor_not_met`` (correlations suppressed) or ``ok``.
 */
export type CohortMetric = {
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Eligible Count
     */
    eligible_count?: number | null;
    kendall: RankStat;
    ndcg: NdcgStat;
    precision_at_k: PrecisionAtK;
    spearman: RankStat;
    /**
     * Status
     */
    status: string;
};

/**
 * ComponentReadiness
 */
export type ComponentReadiness = {
    /**
     * Basis
     */
    basis: string;
    /**
     * Component
     */
    component: string;
    /**
     * Component Status
     */
    component_status: 'pass' | 'insufficient_data' | 'fail' | 'not_applicable';
    /**
     * Decision Supported
     */
    decision_supported: false;
};

/**
 * CounterArgumentField
 */
export type CounterArgumentField = {
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Status
     */
    status: string;
    /**
     * Text
     */
    text: string | null;
};

/**
 * DegradationField
 */
export type DegradationField = {
    /**
     * Message
     */
    message: string;
};

/**
 * DivergenceField
 */
export type DivergenceField = {
    /**
     * Delta
     */
    delta: number | null;
    /**
     * Status
     */
    status: string;
};

/**
 * DivergenceResult
 *
 * Gate 4. Populated only when sufficient FC snapshots and flagged player data exist.
 */
export type DivergenceResult = {
    /**
     * Diff Bca Ci95
     */
    diff_bca_ci95: [
        number,
        number
    ];
    /**
     * Forward Horizon Days
     */
    forward_horizon_days: number;
    /**
     * Hit Rate
     */
    hit_rate: number;
    /**
     * Hit Rate Wilson Ci95
     */
    hit_rate_wilson_ci95: [
        number,
        number
    ];
    /**
     * Mann Whitney Method
     */
    mann_whitney_method: string;
    /**
     * Mann Whitney P
     */
    mann_whitney_p: number;
    /**
     * Mann Whitney U
     */
    mann_whitney_u: number;
    /**
     * Mean Alpha Control
     */
    mean_alpha_control: number;
    /**
     * Mean Alpha Flagged
     */
    mean_alpha_flagged: number;
    /**
     * N Excluded Injury
     */
    n_excluded_injury: number;
    /**
     * N Flagged
     */
    n_flagged: number;
    /**
     * N Matched Controls Per Flag
     */
    n_matched_controls_per_flag?: number;
    /**
     * Position Beta
     */
    position_beta: number;
};

/**
 * EvidenceListField
 */
export type EvidenceListField = {
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Items
     */
    items?: Array<string>;
};

/**
 * FoldResult
 */
export type FoldResult = {
    /**
     * Calibration By Decile
     */
    calibration_by_decile?: Array<number> | null;
    /**
     * Feature Coefficients
     */
    feature_coefficients?: {
        [key: string]: number;
    } | null;
    /**
     * Fold Index
     */
    fold_index: number;
    /**
     * Kendall Tau
     */
    kendall_tau: number;
    /**
     * Kendall Tau Bca Ci95
     */
    kendall_tau_bca_ci95: [
        number,
        number
    ];
    /**
     * Mae
     */
    mae: number;
    /**
     * Market Pool N
     */
    market_pool_n?: number | null;
    /**
     * Metric Caveats
     */
    metric_caveats?: Array<string>;
    /**
     * N Excluded Injury
     */
    n_excluded_injury?: number;
    /**
     * N Test
     */
    n_test: number;
    /**
     * N Train
     */
    n_train: number;
    /**
     * Ndcg At 12 Market
     */
    ndcg_at_12_market?: number | null;
    /**
     * Ndcg At 12 Model
     */
    ndcg_at_12_model?: number | null;
    /**
     * Ndcg At 24 Market
     */
    ndcg_at_24_market?: number | null;
    /**
     * Ndcg At 24 Model
     */
    ndcg_at_24_model?: number | null;
    /**
     * Ndcg Diff Bca Ci95
     */
    ndcg_diff_bca_ci95?: [
        number,
        number
    ] | null;
    /**
     * Ndcg Diff Primary K
     */
    ndcg_diff_primary_k?: number | null;
    /**
     * Null Coverage
     */
    null_coverage?: number | null;
    /**
     * Outcome Seasons
     */
    outcome_seasons: Array<number>;
    /**
     * Precision At K
     */
    precision_at_k?: {
        [key: string]: TopKResult;
    } | null;
    /**
     * Primary K
     */
    primary_k?: number | null;
    /**
     * R2 Oos
     */
    r2_oos?: number | null;
    /**
     * Rank Ic
     */
    rank_ic: number;
    /**
     * Regime Notes
     */
    regime_notes?: string | null;
    /**
     * Rmse
     */
    rmse: number;
    /**
     * Spearman Rho
     */
    spearman_rho: number;
    /**
     * Spearman Rho Bca Ci95
     */
    spearman_rho_bca_ci95: [
        number,
        number
    ];
    /**
     * Test Year
     */
    test_year: number;
    /**
     * Train Years
     */
    train_years: Array<number>;
};

/**
 * GateResult
 */
export type GateResult = {
    /**
     * G1 Rank Correlation Pass
     */
    g1_rank_correlation_pass: boolean;
    /**
     * G2 Rmse Stability Pass
     */
    g2_rmse_stability_pass: boolean;
    /**
     * G3 Market Superiority Pass
     */
    g3_market_superiority_pass: true | false | 'deferred';
    /**
     * G4 Divergence Validity Pass
     */
    g4_divergence_validity_pass: true | false | 'deferred' | 'insufficient_data';
    /**
     * Gate Version
     */
    gate_version?: string;
    /**
     * Model Status
     */
    model_status?: 'VALIDATED' | 'PROVISIONAL' | 'EXPERIMENTAL';
    /**
     * Null Coverage Min
     */
    null_coverage_min?: number | null;
    /**
     * Overall Grade
     */
    overall_grade: 'PRE_MODEL' | 'EXPERIMENTAL' | 'ACTIVE_B' | 'ACTIVE_B_VALIDATED' | 'DECISION_GRADE';
    /**
     * Promotion Justification
     */
    promotion_justification: string;
    status_explanation?: StatusExplanation | null;
    /**
     * Status Version
     */
    status_version?: string;
    /**
     * Validity Ci Adequacy Pass
     */
    validity_ci_adequacy_pass?: boolean;
    /**
     * Validity Cold Start Fold Index
     */
    validity_cold_start_fold_index?: number | null;
    /**
     * Validity Cold Start Tolerated
     */
    validity_cold_start_tolerated?: boolean;
    /**
     * Validity Leakage Pass
     */
    validity_leakage_pass?: boolean;
    /**
     * Validity Most Recent Fold Index
     */
    validity_most_recent_fold_index?: number | null;
    /**
     * Validity Most Recent Fold Pass
     */
    validity_most_recent_fold_pass?: boolean | null;
    /**
     * Validity Null Coverage Pass
     */
    validity_null_coverage_pass?: boolean;
    /**
     * Validity R2 Pass
     */
    validity_r2_pass?: boolean;
    /**
     * Validity Rmse Stability Pass
     */
    validity_rmse_stability_pass?: boolean;
    /**
     * Validity Spearman Pass
     */
    validity_spearman_pass?: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LeaguePulseCapacityCandidate
 *
 * One descriptive roster-capacity candidate. No nomination: the surface
 * lists every candidate that could free capacity; it never selects one.
 */
export type LeaguePulseCapacityCandidate = {
    /**
     * Capacity Conflict Status
     */
    capacity_conflict_status: 'hard_roster_rules_conflict' | 'roster_capacity_pressure';
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * Dvs
     */
    dvs?: number | null;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Position
     */
    position: string;
    /**
     * Rule Conflict Label
     */
    rule_conflict_label?: string | null;
    /**
     * Sleeper Player Id
     */
    sleeper_player_id: string;
    /**
     * Value Status
     */
    value_status: 'valued' | 'unvalued';
    /**
     * Xvar Pct
     */
    xvar_pct?: number | null;
};

/**
 * LeaguePulseCapacityCandidatePool
 *
 * Descriptive pool that replaces the old tool-selected single-drop field.
 * Exposes roster-capacity constraints (full candidate set, hard-rule
 * conflicts, single-candidate pressure, empty) without nominating an action.
 * ``selection_rule`` is fixed to a no-tool-selection marker (v2-only: T4c
 * dropped the transitional v1-compat migration state).
 */
export type LeaguePulseCapacityCandidatePool = {
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * Items
     */
    items?: Array<LeaguePulseCapacityCandidate>;
    /**
     * Narrowing Rule
     */
    narrowing_rule: string;
    /**
     * Pool Status
     */
    pool_status: 'available' | 'constrained_single_candidate' | 'empty';
    /**
     * Selection Rule
     */
    selection_rule: string;
    /**
     * Sort Key
     */
    sort_key: string;
};

/**
 * LeaguePulseCard
 *
 * Model-native opportunity card. Rejects market evidence/score keys.
 */
export type LeaguePulseCard = {
    /**
     * Card Id
     */
    card_id: string;
    /**
     * Card Type
     */
    card_type: 'ROSTER_SURPLUS_DEFICIT_MATCH';
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * Evidence
     */
    evidence: {
        [key: string]: unknown;
    };
    /**
     * Evidence Status
     */
    evidence_status: 'evidence_complete' | 'evidence_gated' | 'inputs_unavailable';
    /**
     * Rationale Primary
     */
    rationale_primary: string;
    /**
     * Rationale Secondary
     */
    rationale_secondary?: Array<string>;
    /**
     * Score Components
     */
    score_components: {
        [key: string]: number;
    };
    /**
     * Sort Key
     */
    sort_key: string;
    /**
     * Sort Value
     */
    sort_value: number;
};

/**
 * LeaguePulseCardSectionCount
 */
export type LeaguePulseCardSectionCount = {
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * Section Cap
     */
    section_cap: number;
    /**
     * Shown Count
     */
    shown_count: number;
    /**
     * Sort Key
     */
    sort_key: string;
    /**
     * Total Count
     */
    total_count: number;
};

/**
 * LeaguePulseDropCounts
 */
export type LeaguePulseDropCounts = {
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * Market Overlay Cards
     */
    market_overlay_cards?: number;
    /**
     * Model Native Cards
     */
    model_native_cards?: number;
    /**
     * Partner Rankings
     */
    partner_rankings?: number;
    /**
     * Roster Capacity Candidate Pools
     */
    roster_capacity_candidate_pools?: number;
    /**
     * Team Postures
     */
    team_postures?: number;
    /**
     * Team Values
     */
    team_values?: number;
};

/**
 * LeaguePulseMarketCard
 *
 * Labeled market-overlay card (Q3=B). Admits market evidence/score keys.
 */
export type LeaguePulseMarketCard = {
    /**
     * Card Id
     */
    card_id: string;
    /**
     * Card Type
     */
    card_type: 'UNROSTERED_MODEL_MARKET_DIVERGENCE' | 'DIVERGENCE_MODEL_HIGH' | 'DIVERGENCE_MARKET_HIGH' | 'TAXI_LONG_TERM_VALUE_PRESENT';
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * Evidence
     */
    evidence: {
        [key: string]: unknown;
    };
    /**
     * Evidence Status
     */
    evidence_status: 'evidence_complete' | 'evidence_gated' | 'inputs_unavailable';
    /**
     * Rationale Primary
     */
    rationale_primary: string;
    /**
     * Rationale Secondary
     */
    rationale_secondary?: Array<string>;
    roster_capacity_candidates?: LeaguePulseCapacityCandidatePool | null;
    /**
     * Score Components
     */
    score_components: {
        [key: string]: number;
    };
    /**
     * Sort Key
     */
    sort_key: string;
    /**
     * Sort Value
     */
    sort_value: number;
};

/**
 * LeaguePulsePartnerRanking
 */
export type LeaguePulsePartnerRanking = {
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Counterparty Roster Id
     */
    counterparty_roster_id: number;
    /**
     * Counterparty Team Name
     */
    counterparty_team_name: string | null;
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * Evidence
     */
    evidence: {
        [key: string]: unknown;
    };
    /**
     * Market Influenced
     */
    market_influenced?: true;
    /**
     * Matched Positions
     */
    matched_positions: Array<string>;
    /**
     * Partner Score
     */
    partner_score: number;
    /**
     * Score Components
     */
    score_components: {
        [key: string]: number;
    };
};

/**
 * LeaguePulseResponse
 */
export type LeaguePulseResponse = {
    /**
     * Captured At
     */
    captured_at: string;
    /**
     * Card Section Counts
     */
    card_section_counts: Array<LeaguePulseCardSectionCount>;
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: false;
    dropped: LeaguePulseDropCounts;
    /**
     * Market Overlay Cards
     */
    market_overlay_cards?: Array<LeaguePulseMarketCard>;
    /**
     * Model Native Cards
     */
    model_native_cards?: Array<LeaguePulseCard>;
    /**
     * Partner Rankings
     */
    partner_rankings?: Array<LeaguePulsePartnerRanking>;
    /**
     * Perspective Roster Id
     */
    perspective_roster_id: number;
    source_artifacts: LeaguePulseSources;
    /**
     * Status
     */
    status: 'active' | 'degraded';
    /**
     * Team Postures
     */
    team_postures?: Array<LeaguePulseTeamPosture>;
    /**
     * Team Values
     */
    team_values?: Array<LeaguePulseTeamValue>;
};

/**
 * LeaguePulseSources
 */
export type LeaguePulseSources = {
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * League Opportunity
     */
    league_opportunity: {
        [key: string]: unknown;
    };
    /**
     * Team Posture
     */
    team_posture: {
        [key: string]: unknown;
    };
    /**
     * Team Value Matrix
     */
    team_value_matrix: {
        [key: string]: unknown;
    };
};

/**
 * LeaguePulseTeamPosture
 */
export type LeaguePulseTeamPosture = {
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Components
     */
    components: {
        [key: string]: number;
    };
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * Posture Label
     */
    posture_label: 'CONTENDER' | 'REBUILDING' | 'ASCENDING' | 'BALANCED' | 'TRANSITIONAL';
    /**
     * Roster Id
     */
    roster_id: number;
    /**
     * Score
     */
    score: number;
    /**
     * Team Name
     */
    team_name: string | null;
};

/**
 * LeaguePulseTeamValue
 */
export type LeaguePulseTeamValue = {
    /**
     * Age Profile
     */
    age_profile: {
        [key: string]: number;
    };
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * Future Picks
     */
    future_picks: {
        [key: string]: unknown;
    };
    /**
     * Positional Summary
     */
    positional_summary: {
        [key: string]: unknown;
    };
    /**
     * Roster Id
     */
    roster_id: number;
    /**
     * Team Name
     */
    team_name: string | null;
    value_views: LeaguePulseValueViews;
};

/**
 * LeaguePulseValueViews
 */
export type LeaguePulseValueViews = {
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * Depth Credit Xvar
     */
    depth_credit_xvar: number;
    /**
     * Lineup Xvar
     */
    lineup_xvar: number;
    /**
     * Starter Weighted Xvar
     */
    starter_weighted_xvar: number;
    /**
     * Top N Xvar
     */
    top_n_xvar: number;
    /**
     * Total Xvar Capped
     */
    total_xvar_capped: number;
};

/**
 * MarketAssetOverlay
 */
export type MarketAssetOverlay = {
    asset_ref: MarketAssetRef;
    /**
     * Caveats
     */
    caveats: Array<string>;
    /**
     * Coverage Gap
     */
    coverage_gap: string | null;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    divergence_context?: MarketDivergenceContext | null;
    /**
     * Format Key
     */
    format_key: string;
    /**
     * Label
     */
    label: string;
    /**
     * Market Value
     */
    market_value: number | null;
    /**
     * Market Volatility
     */
    market_volatility?: number | null;
    /**
     * Resolution
     */
    resolution: 'player_sleeper_id' | 'pick_exact_slot' | 'pick_generic_year_round' | 'unresolved';
    /**
     * Source
     */
    source: 'fantasycalc';
    /**
     * Source Timestamp
     */
    source_timestamp?: string | null;
    /**
     * Trend 30D
     */
    trend_30d?: number | null;
};

/**
 * MarketAssetRef
 */
export type MarketAssetRef = {
    /**
     * Asset Kind
     */
    asset_kind: 'player' | 'prospect_player' | 'future_pick';
    /**
     * Bucket
     */
    bucket?: 'early' | 'mid' | 'late' | null;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Player Id
     */
    player_id?: string | null;
    /**
     * Quantity Id
     */
    quantity_id?: string | null;
    /**
     * Round
     */
    round?: number | null;
    /**
     * Sleeper Id
     */
    sleeper_id?: string | null;
    /**
     * Slot
     */
    slot?: number | null;
    /**
     * Year
     */
    year?: number | null;
};

/**
 * MarketDivergenceContext
 */
export type MarketDivergenceContext = {
    /**
     * Caveats
     */
    caveats: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Percentile Delta
     */
    percentile_delta: number | null;
    /**
     * Sigma Threshold
     */
    sigma_threshold: number;
    /**
     * Signal Label
     */
    signal_label: 'model_higher_than_market' | 'model_lower_than_market' | 'inside_band' | 'unavailable';
    /**
     * Source Signal Status
     */
    source_signal_status: string | null;
};

/**
 * MarketRealismWarning
 */
export type MarketRealismWarning = {
    /**
     * Caveats
     */
    caveats: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Metrics
     */
    metrics: {
        [key: string]: number;
    };
    /**
     * Severity
     */
    severity: 'advisory';
    /**
     * Warning Type
     */
    warning_type: 'package_dilution_warning' | 'roster_filler_warning' | 'market_package_requires_manual_review';
};

/**
 * MarketReconcileRequest
 */
export type MarketReconcileRequest = {
    /**
     * Counterparty Roster Id
     */
    counterparty_roster_id?: number | null;
    /**
     * Current Draft Year
     */
    current_draft_year?: number;
    /**
     * Format Key
     */
    format_key?: string;
    /**
     * Received Assets
     */
    received_assets: Array<MarketAssetRef>;
    /**
     * Sent Assets
     */
    sent_assets: Array<MarketAssetRef>;
};

/**
 * MarketRosterPenalty
 */
export type MarketRosterPenalty = {
    /**
     * Caveats
     */
    caveats: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Forced Cut Candidates
     */
    forced_cut_candidates: Array<MarketAssetOverlay>;
    /**
     * Forced Cut Market Recovery Range
     */
    forced_cut_market_recovery_range?: [
        number,
        number
    ] | null;
    /**
     * Forced Cut Market Value At Risk Range
     */
    forced_cut_market_value_at_risk_range?: [
        number,
        number
    ] | null;
    /**
     * Market Penalty Status
     */
    market_penalty_status?: 'ok' | 'uncertain_pool_unavailable' | 'blocked';
    /**
     * Penalty Market Value
     */
    penalty_market_value: number;
    /**
     * Post Trade Overflow
     */
    post_trade_overflow: number;
    /**
     * Roster Id
     */
    roster_id: number;
    /**
     * Unresolved Cut Count
     */
    unresolved_cut_count: number;
};

/**
 * MifField
 *
 * Model Input Fidelity for one utilization field — a diagnostic audit of a
 * model INPUT (does realized usage match the model's assumption), NOT a player
 * verdict. ``delta`` is only populated when ``status == "ok"``.
 */
export type MifField = {
    /**
     * Delta
     */
    delta?: number | null;
    /**
     * Status
     */
    status: string;
};

/**
 * MissingRange
 *
 * One contiguous missing-date range; display list is capped, totals never.
 */
export type MissingRange = {
    /**
     * Days
     */
    days: number;
    /**
     * From
     */
    from: string;
    /**
     * To
     */
    to: string;
};

/**
 * ModelCardResponse
 *
 * Curated PUBLIC model-card contract — the 8 safety/identity fields only.
 *
 * Provenance fields (model_version / model_artifact_hash / git_sha) live on the
 * audit-internal PublishedModelCardSource artifact and are deliberately NOT exposed
 * here, so the public surface never leaks the 9-section ModelCard internals.
 */
export type ModelCardResponse = {
    /**
     * Backtest Run Id
     */
    backtest_run_id: string | null;
    /**
     * Caveats
     */
    caveats: Array<string>;
    /**
     * Generated At
     */
    generated_at: string | null;
    /**
     * Intended Use
     */
    intended_use: string;
    /**
     * Is Experimental
     */
    is_experimental: boolean;
    /**
     * Known Failure Modes
     */
    known_failure_modes: Array<string>;
    /**
     * Out Of Scope Uses
     */
    out_of_scope_uses: Array<string>;
    /**
     * Position
     */
    position: string;
};

/**
 * ModelProvenanceErrorResponse
 */
export type ModelProvenanceErrorResponse = {
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Error
     */
    error: string;
    /**
     * Message
     */
    message: string;
};

/**
 * ModelProvenanceResponse
 */
export type ModelProvenanceResponse = {
    /**
     * Artifacts
     */
    artifacts: Array<ArtifactProvenance>;
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Environment
     */
    environment: 'development' | 'ci' | 'serving' | 'production';
    /**
     * Overall Status
     */
    overall_status: 'ok' | 'degraded' | 'blocked';
    /**
     * Registry Version
     */
    registry_version: number;
};

/**
 * ModelReliability
 *
 * QB-only descriptive model-reliability stamp (measured uncertainty, no verdict).
 */
export type ModelReliability = {
    /**
     * Caveat
     */
    caveat: string;
    /**
     * Position
     */
    position: string;
    /**
     * R2 Oos Mean
     */
    r2_oos_mean?: number | null;
    /**
     * Spearman Rho Mean
     */
    spearman_rho_mean?: number | null;
};

/**
 * NdcgStat
 */
export type NdcgStat = {
    /**
     * Value
     */
    value?: number | null;
};

/**
 * PlayerDetailResponse
 */
export type PlayerDetailResponse = {
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: false;
    degradation: DegradationField | null;
    divergence: DivergenceField;
    evidence: PlayerEvidence | null;
    identity: PlayerIdentity;
    market: PlayerMarketLane;
    model: PlayerModelLane | null;
    /**
     * Model Status
     */
    model_status: string;
    /**
     * Sleeper Id
     */
    sleeper_id: string;
    /**
     * Source Timestamps
     */
    source_timestamps: {
        [key: string]: string | null;
    };
};

/**
 * PlayerEvidence
 */
export type PlayerEvidence = {
    caveats: EvidenceListField;
    counter_argument: CounterArgumentField;
    risk_flags: EvidenceListField;
    top_drivers: EvidenceListField;
};

/**
 * PlayerIdentity
 */
export type PlayerIdentity = {
    /**
     * Age
     */
    age: number | null;
    /**
     * Draft Class
     */
    draft_class: number | null;
    /**
     * Name
     */
    name: string | null;
    /**
     * Nfl Draft Pick
     */
    nfl_draft_pick: number | null;
    /**
     * Nfl Draft Round
     */
    nfl_draft_round: number | null;
    /**
     * Position
     */
    position: string | null;
    /**
     * Sleeper Id
     */
    sleeper_id: string;
    /**
     * Team
     */
    team: string | null;
};

/**
 * PlayerMarketLane
 */
export type PlayerMarketLane = {
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Market Rank Overall
     */
    market_rank_overall: number | null;
    /**
     * Market Rank Position
     */
    market_rank_position: number | null;
    /**
     * Market Value
     */
    market_value: number | null;
    /**
     * Source
     */
    source: string | null;
    /**
     * Source Timestamp
     */
    source_timestamp: string | null;
    /**
     * Status
     */
    status: string;
};

/**
 * PlayerModelLane
 */
export type PlayerModelLane = {
    /**
     * Dynasty Value Score
     */
    dynasty_value_score: number | null;
    /**
     * Engine Path
     */
    engine_path: string | null;
    /**
     * Model Grade
     */
    model_grade: string | null;
    /**
     * Model Version
     */
    model_version: string | null;
    /**
     * Projection 1Y
     */
    projection_1y: number | null;
    /**
     * Projection 2Y
     */
    projection_2y: number | null;
    /**
     * Projection 3Y
     */
    projection_3y: number | null;
    /**
     * Xvar
     */
    xvar: number | null;
    /**
     * Xvar Percentile Position
     */
    xvar_percentile_position: number | null;
};

/**
 * PoolRange
 *
 * The unrostered (waiver) replacement range for one position.
 *
 * Deliberately WIDE, not a confidence interval: `low`/`high` are the min/max of
 * the position's display top-K unrostered values — an honest band over a
 * volatile wire, never a tightened point estimate. `top_k_values` carries the
 * ordered (descending) raw values themselves, retained out to the largest
 * requested scenario so T3's depletion math has every per-member value it
 * needs (it may be LONGER than the K that low/high are computed over).
 *
 * `status == "waiver_range_unavailable"` fails closed (stale snapshot,
 * incomplete roster coverage, pool below `min_pool`, valuation coverage below
 * floor); a genuinely barren-but-valid pool stays `ok` with a loud caveat.
 */
export type PoolRange = {
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * High
     */
    high: number | null;
    /**
     * Low
     */
    low: number | null;
    /**
     * Pool Size
     */
    pool_size: number | null;
    /**
     * Status
     */
    status: 'ok' | 'waiver_range_unavailable';
    /**
     * Top K Values
     */
    top_k_values?: Array<number>;
};

/**
 * PrecisionAtK
 */
export type PrecisionAtK = {
    /**
     * Hits
     */
    hits?: number | null;
    /**
     * K
     */
    k?: number | null;
    /**
     * Truth Def
     */
    truth_def?: string | null;
    /**
     * Value
     */
    value?: number | null;
};

/**
 * ProspectRequest
 */
export type ProspectRequest = {
    /**
     * Age
     */
    age: number;
    /**
     * Draft Class
     */
    draft_class?: number | null;
    /**
     * Final College Age
     */
    final_college_age?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Pick
     */
    pick: number;
    /**
     * Position
     */
    position: string;
    /**
     * Round
     */
    round: number;
    /**
     * Sleeper Id
     */
    sleeper_id?: string | null;
    /**
     * Te Ryptpa Final
     */
    te_ryptpa_final?: number | null;
    /**
     * Te Yards Per Reception Career
     */
    te_yards_per_reception_career?: number | null;
};

/**
 * QBContextCard
 *
 * F2: explicitly typed; extra fields forbidden (no provenance/market backdoor).
 */
export type QbContextCard = {
    /**
     * Context Role
     */
    context_role?: 'context_signal';
    /**
     * Cpoe
     */
    cpoe?: number | null;
    /**
     * Dakota
     */
    dakota?: number | null;
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * Dropback Count
     */
    dropback_count?: number | null;
    /**
     * Epa Per Dropback
     */
    epa_per_dropback?: number | null;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Identity Coverage
     */
    identity_coverage: 'FULL' | 'PARTIAL' | 'NONE';
    /**
     * Pass Attempts
     */
    pass_attempts?: number | null;
    /**
     * Player Id
     */
    player_id: string;
    /**
     * Qb Context Annotations
     */
    qb_context_annotations?: Array<string>;
    /**
     * Qb Context Caveats
     */
    qb_context_caveats?: Array<string>;
    /**
     * Source Qb Context Annotations
     */
    source_qb_context_annotations: string;
};

/**
 * RankStat
 *
 * A rank-correlation statistic with its BCa confidence interval (both nullable
 * until a cohort clears the statistical power floor).
 */
export type RankStat = {
    /**
     * Bca Ci
     */
    bca_ci?: Array<number> | null;
    /**
     * Value
     */
    value?: number | null;
};

/**
 * RealizedOutcomeScorecardErrorResponse
 *
 * Structured 503 body: the scorecard artifact is present but could not be
 * served (malformed, wrong-root, wrong-schema, non-finite, or verdict-shaped).
 *
 * Absent artifact is NOT an error — it is the healthy off-season ``inactive`` 200.
 */
export type RealizedOutcomeScorecardErrorResponse = {
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * Error
     */
    error: string;
    /**
     * Message
     */
    message: string;
};

/**
 * RealizedOutcomeScorecardResponse
 *
 * Read-only serve of the latest realized-outcome scorecard.
 *
 * ``status`` is ``inactive`` (no artifact yet — the healthy off-season state) or
 * ``ok`` (a produced scorecard). ``settlement_status`` is ``unsettled`` until the
 * 2-year horizon. Leads with within-position rank accuracy + Model Input Fidelity;
 * market data is excluded from scoring.
 */
export type RealizedOutcomeScorecardResponse = {
    /**
     * As Of Week
     */
    as_of_week?: number | null;
    /**
     * Cohort Metrics
     */
    cohort_metrics?: {
        [key: string]: CohortMetric;
    };
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Excluded Counts
     */
    excluded_counts?: {
        [key: string]: number;
    };
    /**
     * Maturity Pct
     */
    maturity_pct?: number | null;
    /**
     * Settlement Status
     */
    settlement_status: string;
    /**
     * Status
     */
    status: string;
    /**
     * Status Reason
     */
    status_reason?: string | null;
    /**
     * Tracking Rows
     */
    tracking_rows?: Array<TrackingRow>;
};

/**
 * ReportHealth
 */
export type ReportHealth = {
    /**
     * Age Seconds
     */
    age_seconds: number | null;
    /**
     * Artifact Id
     */
    artifact_id: string;
    /**
     * Artifact Path
     */
    artifact_path: string;
    /**
     * Basis
     */
    basis: string;
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Disclosures
     */
    disclosures: Array<string>;
    /**
     * Observed At
     */
    observed_at: string | null;
    /**
     * Producer
     */
    producer: string;
    /**
     * Status
     */
    status: 'fresh' | 'freshness_overdue' | 'stale' | 'corrupt_or_empty' | 'dormant' | 'missing';
    /**
     * Tier
     */
    tier: 'core_substrate' | 'daily_diagnostics' | 'auxiliary';
};

/**
 * RosterAuditPlayer
 */
export type RosterAuditPlayer = {
    /**
     * Age
     */
    age?: number | null;
    /**
     * Caveats
     */
    caveats?: Array<string>;
    counter_argument: CounterArgumentField;
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * Draft Class
     */
    draft_class?: number | null;
    /**
     * Dvs Engine
     */
    dvs_engine?: 'A' | 'B' | 'blend' | null;
    /**
     * Dvs Pct
     */
    dvs_pct?: number | null;
    /**
     * Dynasty Value Score
     */
    dynasty_value_score?: number | null;
    /**
     * Engine Used
     */
    engine_used?: string | null;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Inputs Missing
     */
    inputs_missing?: Array<string>;
    /**
     * Inputs Present
     */
    inputs_present?: Array<string>;
    /**
     * Is Prospect
     */
    is_prospect?: boolean;
    /**
     * Model Grade
     */
    model_grade: string;
    /**
     * Model Status Applies
     */
    model_status_applies?: boolean;
    /**
     * Model Version
     */
    model_version?: string | null;
    /**
     * Nfl Draft Pick
     */
    nfl_draft_pick?: number | null;
    /**
     * Nfl Draft Round
     */
    nfl_draft_round?: number | null;
    /**
     * Nfl Team
     */
    nfl_team?: string | null;
    /**
     * Player Id
     */
    player_id: string;
    /**
     * Position
     */
    position: string;
    /**
     * Projection 1Y
     */
    projection_1y?: number | null;
    /**
     * Projection 2Y
     */
    projection_2y?: number | null;
    /**
     * Projection 3Y
     */
    projection_3y?: number | null;
    risk_flags: EvidenceListField;
    roster_audit?: RosterAuditSignalsView | null;
    /**
     * Signal Completeness
     */
    signal_completeness?: number;
    /**
     * Sleeper Id
     */
    sleeper_id?: string | null;
    top_drivers: EvidenceListField;
    /**
     * Xvar
     */
    xvar?: number | null;
};

/**
 * RosterAuditResponse
 */
export type RosterAuditResponse = {
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * Dropped Player Count
     */
    dropped_player_count?: number;
    /**
     * Engine
     */
    engine: string;
    /**
     * Model Status By Position
     */
    model_status_by_position: {
        [key: string]: 'VALIDATED' | 'PROVISIONAL' | 'EXPERIMENTAL';
    };
    /**
     * Players
     */
    players?: Array<RosterAuditPlayer>;
    /**
     * Qb Context Cards
     */
    qb_context_cards?: Array<QbContextCard>;
    /**
     * Reason
     */
    reason: string;
    /**
     * Status
     */
    status: 'active' | 'degraded';
};

/**
 * RosterAuditSignalsView
 *
 * F3: curated signals view; nested decision_supported can never leak true.
 */
export type RosterAuditSignalsView = {
    /**
     * Age Cliff Risk
     */
    age_cliff_risk?: number | null;
    /**
     * Age Value Context
     */
    age_value_context?: string | null;
    /**
     * Biological Debt Score
     */
    biological_debt_score?: number | null;
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Cliff Age
     */
    cliff_age?: number | null;
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * Liquidity Risk
     */
    liquidity_risk?: string | null;
    /**
     * Signal
     */
    signal?: string | null;
    /**
     * Signal Drivers
     */
    signal_drivers?: Array<string>;
    /**
     * Years To Cliff
     */
    years_to_cliff?: number | null;
};

/**
 * RosterCapacityErrorResponse
 *
 * Structured 503 body: the artifact could not be served.
 *
 * Even the failure is descriptive — `decision_supported` stays False so a
 * consumer never reads an error as a directive.
 */
export type RosterCapacityErrorResponse = {
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * Error
     */
    error: string;
    /**
     * Message
     */
    message: string;
};

/**
 * RosterCapacityResponse
 *
 * Read-only serve of the enriched capacity scorecard artifact.
 *
 * `artifact_status` is the route's own read of the served state
 * (`ok` / `degraded` / `blocked`), DISTINCT from the core `status`. No field
 * averages, tightens, or nominates: ranges pass through unclamped and signed,
 * and `marginal_next_candidate_cost` stays a range with no player identifier.
 */
export type RosterCapacityResponse = {
    /**
     * Artifact Status
     */
    artifact_status: 'ok' | 'degraded' | 'blocked';
    /**
     * Candidates
     */
    candidates?: Array<CapacityCandidate>;
    capacity_health: CapacityHealth | null;
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Created At
     */
    created_at: string | null;
    /**
     * Decision Supported
     */
    decision_supported?: false;
    /**
     * Excluded Counts
     */
    excluded_counts?: {
        [key: string]: number;
    };
    /**
     * Scenarios
     */
    scenarios?: Array<ScenarioResult>;
    /**
     * Sleeper Snapshot Captured At
     */
    sleeper_snapshot_captured_at: string | null;
    /**
     * Status
     */
    status: 'ok' | 'blocked';
    /**
     * Unrostered Pool Range
     */
    unrostered_pool_range?: {
        [key: string]: PoolRange;
    };
};

/**
 * RosterPenaltySummary
 */
export type RosterPenaltySummary = {
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Forced Cut Candidates
     */
    forced_cut_candidates: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Forced Cut Penalty Xvar
     */
    forced_cut_penalty_xvar: number;
    /**
     * Forced Cut Recovery Range
     */
    forced_cut_recovery_range?: [
        number,
        number
    ] | null;
    /**
     * Forced Cut Value At Risk Range
     */
    forced_cut_value_at_risk_range?: [
        number,
        number
    ] | null;
    /**
     * Penalty Caveats
     */
    penalty_caveats: Array<string>;
    /**
     * Penalty Status
     */
    penalty_status?: 'ok' | 'uncertain_pool_unavailable' | 'blocked';
    /**
     * Pool Deficits
     */
    pool_deficits?: {
        [key: string]: number;
    };
    /**
     * Post Trade Overflow
     */
    post_trade_overflow: number;
    /**
     * Post Trade Total Players
     */
    post_trade_total_players: number;
};

/**
 * ScenarioResult
 *
 * The descriptive consequences of one cut hypothesis — no verdict.
 *
 * `cumulative_value_at_risk` is depletion-aware (NOT N x a single-player gap):
 * the wire depletes as you claim players, so the bound is summed per position
 * from N-deep pool slices. Orientation is pinned `(best_case, worst_case)` and
 * cannot invert; negatives are left UNCLAMPED (a cut that is a net upgrade
 * reads negative). `pool_deficits` records, per position, how many cut spots
 * have NO replacement candidate — a fact, never a do-not-cut verdict.
 * `marginal_next_candidate_cost` is the value-at-risk RANGE of the next
 * capacity-ordered candidate not in the cut set; it carries NO player
 * identifier (it nominates no target).
 */
export type ScenarioResult = {
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Cumulative Value At Risk
     */
    cumulative_value_at_risk: [
        number,
        number
    ];
    /**
     * Cut Set
     */
    cut_set?: Array<string>;
    /**
     * Marginal Next Candidate Cost
     */
    marginal_next_candidate_cost: [
        number,
        number
    ] | null;
    /**
     * Per Position Depth Impact
     */
    per_position_depth_impact?: {
        [key: string]: {
            [key: string]: number;
        };
    };
    /**
     * Pool Deficits
     */
    pool_deficits?: {
        [key: string]: number;
    };
};

/**
 * StabilityResult
 */
export type StabilityResult = {
    /**
     * Dm Hln Pvalue
     */
    dm_hln_pvalue?: number | null;
    /**
     * Dm Hln Statistic
     */
    dm_hln_statistic?: number | null;
    /**
     * Dm Method
     */
    dm_method?: string;
    /**
     * Dm Passes
     */
    dm_passes?: boolean | null;
    /**
     * Rmse Cv
     */
    rmse_cv: number;
    /**
     * Rmse Max Deviation Pct
     */
    rmse_max_deviation_pct: number;
    /**
     * Rmse Mean
     */
    rmse_mean: number;
    /**
     * Rmse Per Fold
     */
    rmse_per_fold: Array<number>;
};

/**
 * StatusExplanation
 *
 * Auditable record of why a model_status was assigned (Step 0.5 spec §6.5).
 *
 * Records which folds failed each validity predicate and whether the cold-start
 * fold was excused, so the status is a documented decision rather than a vibe.
 */
export type StatusExplanation = {
    /**
     * Cold Start Fold Index
     */
    cold_start_fold_index?: number | null;
    /**
     * Cold Start Tolerated
     */
    cold_start_tolerated?: boolean;
    /**
     * Failed Ci Folds
     */
    failed_ci_folds?: Array<number>;
    /**
     * Failed Rank Folds
     */
    failed_rank_folds?: Array<number>;
    /**
     * Leakage Clean
     */
    leakage_clean?: boolean | null;
    /**
     * Most Recent Fold Index
     */
    most_recent_fold_index?: number | null;
    /**
     * Most Recent Fold Pass
     */
    most_recent_fold_pass?: boolean | null;
    /**
     * Null Coverage Min
     */
    null_coverage_min?: number | null;
    /**
     * Reason
     */
    reason?: string;
};

/**
 * StoreDensity
 */
export type StoreDensity = {
    /**
     * Baseline Median Rows
     */
    baseline_median_rows: number | null;
    /**
     * Baseline Window
     */
    baseline_window: number;
    /**
     * Floor Pct
     */
    floor_pct: number;
    /**
     * Sub Floor Dates
     */
    sub_floor_dates: Array<string>;
};

/**
 * StoreFlags
 */
export type StoreFlags = {
    /**
     * Warn Basis
     */
    warn_basis: string;
    /**
     * Warn Missing
     */
    warn_missing: boolean;
    /**
     * Window Risk
     */
    window_risk: boolean;
    /**
     * Window Risk Basis
     */
    window_risk_basis: string;
};

/**
 * StoreHealth
 */
export type StoreHealth = {
    /**
     * Caveats
     */
    caveats: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported: false;
    density: StoreDensity;
    flags: StoreFlags;
    staleness: StoreStaleness;
    /**
     * Store Id
     */
    store_id: string;
    /**
     * Store Presence
     */
    store_presence: 'present' | 'absent';
    /**
     * Store Status
     */
    store_status: 'ok' | 'degraded';
    timeline: StoreTimeline;
};

/**
 * StoreStaleness
 */
export type StoreStaleness = {
    /**
     * Expected By
     */
    expected_by: string;
    /**
     * Grace Hours
     */
    grace_hours: number;
    /**
     * Last Capture Date
     */
    last_capture_date: string | null;
    /**
     * Stale
     */
    stale: boolean;
};

/**
 * StoreTimeline
 */
export type StoreTimeline = {
    /**
     * Capture Start Date
     */
    capture_start_date: string;
    /**
     * Consecutive Days Current
     */
    consecutive_days_current: number;
    /**
     * Expected Days
     */
    expected_days: number;
    /**
     * First Date
     */
    first_date: string | null;
    /**
     * Last Date
     */
    last_date: string | null;
    /**
     * Max Contiguous Gap Days
     */
    max_contiguous_gap_days: number;
    /**
     * Missing Dates Count
     */
    missing_dates_count: number;
    /**
     * Missing Ranges
     */
    missing_ranges: Array<MissingRange>;
    /**
     * Missing Ranges Total
     */
    missing_ranges_total: number;
    /**
     * Present Days
     */
    present_days: number;
};

/**
 * SubsystemHealth
 */
export type SubsystemHealth = {
    /**
     * Basis
     */
    basis: string;
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Status
     */
    status: 'ok' | 'degraded' | 'unavailable';
    /**
     * Subsystem Id
     */
    subsystem_id: string;
    /**
     * Tier
     */
    tier: 'core_substrate' | 'daily_diagnostics' | 'auxiliary';
};

/**
 * SurfaceReadiness
 *
 * Runtime readiness for one surface. Root-level dormancy disclosure is
 * mandatory (R2): the headline `_limited` status plus machine-readable
 * counts, so a UI can never render an unqualified badge over dormant
 * components.
 */
export type SurfaceReadiness = {
    /**
     * All Components Evaluable
     */
    all_components_evaluable: boolean;
    /**
     * Basis
     */
    basis: string;
    /**
     * Components
     */
    components: Array<ComponentReadiness>;
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Insufficient Data Components
     */
    insufficient_data_components: Array<string>;
    /**
     * Insufficient Data Count
     */
    insufficient_data_count: number;
    /**
     * Live Preconditions
     */
    live_preconditions: {
        [key: string]: string;
    };
    /**
     * Surface Id
     */
    surface_id: string;
    /**
     * Tier Status
     */
    tier_status: 'diagnostic_grade_active' | 'diagnostic_grade_active_limited' | 'preconditions_degraded' | 'not_graduated';
};

/**
 * SystemHealthErrorResponse
 */
export type SystemHealthErrorResponse = {
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Error
     */
    error: string;
    /**
     * Message
     */
    message: string;
};

/**
 * SystemHealthResponse
 */
export type SystemHealthResponse = {
    /**
     * Checked At
     */
    checked_at: string;
    /**
     * Config Version
     */
    config_version: number;
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Disclaimer
     */
    disclaimer: 'System health reflects pipeline completion, artifact freshness, and model provenance verification. It does not evaluate model accuracy or guarantee trade edge.';
    /**
     * Overall Status
     */
    overall_status: 'ok' | 'degraded';
    /**
     * Reports
     */
    reports: Array<ReportHealth>;
    /**
     * Subsystems
     */
    subsystems: Array<SubsystemHealth>;
    /**
     * Worst Affected Tier
     */
    worst_affected_tier: 'core_substrate' | 'daily_diagnostics' | 'auxiliary' | null;
};

/**
 * TierReadinessErrorResponse
 */
export type TierReadinessErrorResponse = {
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Error
     */
    error: string;
    /**
     * Message
     */
    message: string;
};

/**
 * TierReadinessResponse
 */
export type TierReadinessResponse = {
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Overall Status
     */
    overall_status: 'ok' | 'degraded';
    /**
     * Registry Version
     */
    registry_version: number;
    /**
     * Surfaces
     */
    surfaces: Array<SurfaceReadiness>;
};

/**
 * TopKResult
 */
export type TopKResult = {
    /**
     * Diff Wilson Ci95
     */
    diff_wilson_ci95: [
        number,
        number
    ];
    /**
     * K
     */
    k: number;
    /**
     * Market Hit Rate
     */
    market_hit_rate: number;
    /**
     * Model Hit Rate
     */
    model_hit_rate: number;
};

/**
 * TrackingRow
 *
 * One player's predicted vs realized PPG plus its input-fidelity audit.
 */
export type TrackingRow = {
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Gsis Id
     */
    gsis_id: string;
    /**
     * Maturity Pct
     */
    maturity_pct?: number | null;
    /**
     * Model Input Fidelity
     */
    model_input_fidelity?: {
        [key: string]: MifField;
    };
    /**
     * Position
     */
    position?: string | null;
    /**
     * Predicted Ppg
     */
    predicted_ppg?: number | null;
    /**
     * Realized Outcome Status
     */
    realized_outcome_status: string;
    /**
     * Realized Ppg To Date
     */
    realized_ppg_to_date?: number | null;
    /**
     * Realized Vs Expected Delta
     */
    realized_vs_expected_delta?: number | null;
    /**
     * Settlement Status
     */
    settlement_status: string;
};

/**
 * TradeAsset
 */
export type TradeAsset = {
    /**
     * Caveat
     */
    caveat?: string | null;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Dvs
     */
    dvs?: number | null;
    /**
     * Dvs Engine
     */
    dvs_engine?: string | null;
    /**
     * Is Prospect
     */
    is_prospect?: boolean;
    /**
     * Player Id
     */
    player_id: string;
    /**
     * Position
     */
    position: string;
    /**
     * Xvar
     */
    xvar: number | null;
};

/**
 * TradeAssetCatalogEntry
 *
 * A single selectable asset, pre-shaped in both payload forms.
 */
export type TradeAssetCatalogEntry = {
    /**
     * Asset Id
     */
    asset_id: string;
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Kind
     */
    kind: 'player' | 'future_pick';
    /**
     * Label
     */
    label: string;
    market_ref: MarketAssetRef;
    model_payload: TradeAsset;
    /**
     * Position
     */
    position?: string | null;
    /**
     * Roster Owner Id
     */
    roster_owner_id?: number | null;
    /**
     * Roster Owner Name
     */
    roster_owner_name?: string | null;
};

/**
 * TradeAssetCatalogResponse
 *
 * The catalog envelope for a single search query.
 */
export type TradeAssetCatalogResponse = {
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Query
     */
    query: string;
    /**
     * Results
     */
    results?: Array<TradeAssetCatalogEntry>;
    /**
     * Source Timestamp
     */
    source_timestamp?: string | null;
};

/**
 * TradeEvaluateRequest
 */
export type TradeEvaluateRequest = {
    /**
     * Side A
     */
    side_a: Array<TradeAsset>;
    /**
     * Side B
     */
    side_b: Array<TradeAsset>;
};

/**
 * TradeEvaluation
 */
export type TradeEvaluation = {
    /**
     * Caveats
     */
    caveats: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Fairness Delta
     */
    fairness_delta: number;
    /**
     * Favors
     */
    favors: string | null;
    /**
     * Favors Xvar Margin
     */
    favors_xvar_margin: number | null;
    side_a: TradeSide;
    side_b: TradeSide;
    /**
     * Within Parity Band
     */
    within_parity_band: boolean;
};

/**
 * TradeMarketReconciliation
 */
export type TradeMarketReconciliation = {
    /**
     * Adjusted Market Received
     */
    adjusted_market_received: number;
    /**
     * Adjusted Market Sent
     */
    adjusted_market_sent: number;
    /**
     * Caveats
     */
    caveats: Array<string>;
    counterparty_forced_cut_penalty: MarketRosterPenalty | null;
    /**
     * Counterparty Market Penalty Status
     */
    counterparty_market_penalty_status?: 'not_requested' | 'available' | 'unavailable';
    /**
     * Coverage Gaps
     */
    coverage_gaps: Array<string>;
    david_forced_cut_penalty: MarketRosterPenalty | null;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Format Key
     */
    format_key: string;
    /**
     * Market Delta For David
     */
    market_delta_for_david: number;
    /**
     * Market Received Raw
     */
    market_received_raw: number;
    /**
     * Market Sent Raw
     */
    market_sent_raw: number;
    /**
     * Market Source
     */
    market_source: 'fantasycalc';
    /**
     * Realism Warnings
     */
    realism_warnings?: Array<MarketRealismWarning>;
    /**
     * Received Assets
     */
    received_assets: Array<MarketAssetOverlay>;
    /**
     * Sent Assets
     */
    sent_assets: Array<MarketAssetOverlay>;
    /**
     * Source Timestamp
     */
    source_timestamp: string | null;
};

/**
 * TradeReconcileRequest
 */
export type TradeReconcileRequest = {
    /**
     * David Assets
     */
    david_assets: Array<TradeAsset>;
    /**
     * Received Assets
     */
    received_assets: Array<TradeAsset>;
};

/**
 * TradeRequest
 */
export type TradeRequest = {
    /**
     * My Assets
     */
    my_assets: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Their Assets
     */
    their_assets: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * TradeRosterReconciliation
 */
export type TradeRosterReconciliation = {
    /**
     * Adjusted David Received Value
     */
    adjusted_david_received_value: number;
    /**
     * Adjusted Fairness Delta
     */
    adjusted_fairness_delta: number;
    /**
     * Adjusted Fairness Delta Range
     */
    adjusted_fairness_delta_range?: [
        number,
        number
    ] | null;
    /**
     * Adjusted Favors
     */
    adjusted_favors: string;
    /**
     * Adjusted Favors Status
     */
    adjusted_favors_status?: 'neutral' | 'david' | 'counterparty' | 'uncertain_range_crosses_parity';
    /**
     * Adjusted Received Value Range
     */
    adjusted_received_value_range?: [
        number,
        number
    ] | null;
    /**
     * Adjusted Within Parity Band
     */
    adjusted_within_parity_band: boolean;
    base_evaluation: TradeEvaluation;
    /**
     * Caveats
     */
    caveats: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    roster_penalty: RosterPenaltySummary;
};

/**
 * TradeSide
 */
export type TradeSide = {
    /**
     * Assets
     */
    assets: Array<TradeAsset>;
    /**
     * Consolidation Factor
     */
    consolidation_factor: number;
    /**
     * Side Value
     */
    side_value: number;
    /**
     * Xvar Sum
     */
    xvar_sum: number;
};

/**
 * TrustSurfaceResponse
 *
 * Typed Trust Surface contract: the full BacktestResult plus the hoisted,
 * consumer-facing fields. Non-breaking superset of the prior dict response, so the
 * frontend Hey API codegen has a real OpenAPI schema (no untyped object).
 */
export type TrustSurfaceResponse = {
    divergence_validity?: DivergenceResult | null;
    /**
     * Experimental
     */
    experimental: boolean;
    /**
     * Folds
     */
    folds: Array<FoldResult>;
    /**
     * Git Sha
     */
    git_sha?: string | null;
    /**
     * Market Snapshot Dates
     */
    market_snapshot_dates?: {
        [key: string]: string;
    } | null;
    /**
     * Market Source
     */
    market_source: 'fc_native' | 'dp_archive' | 'ktc_community_csv' | 'unavailable';
    /**
     * Market Source Label
     */
    market_source_label?: 'fantasycalc_native' | 'dynastyprocess_ecr_2qb' | 'ktc_community_csv' | 'unavailable';
    /**
     * Model Artifact Hash
     */
    model_artifact_hash: string;
    /**
     * Model Card Available
     */
    model_card_available: boolean;
    model_reliability?: ModelReliability | null;
    /**
     * Model Status
     */
    model_status: string;
    /**
     * Model Version
     */
    model_version: string;
    /**
     * Overall Grade
     */
    overall_grade: string;
    /**
     * Position
     */
    position: 'QB' | 'RB' | 'WR' | 'TE';
    promotion_gate: GateResult;
    /**
     * Retrain Mode
     */
    retrain_mode: 'refit_per_fold_fixed_alpha' | 'frozen_retrospective';
    /**
     * Ridge Alpha
     */
    ridge_alpha: number;
    rmse_stability: StabilityResult;
    /**
     * Run Date
     */
    run_date: string;
    /**
     * Run Id
     */
    run_id?: string;
    /**
     * Schema Version
     */
    schema_version?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WhatChangedBaselineRosterRow
 *
 * Increment-1 quiet-day row: identity + flat lanes (0 by definition).
 */
export type WhatChangedBaselineRosterRow = {
    /**
     * Market Lane Value
     */
    market_lane_value: 0;
    /**
     * Model Lane Value
     */
    model_lane_value: 0;
    /**
     * Player Name
     */
    player_name?: string | null;
    /**
     * Position
     */
    position?: string | null;
    /**
     * Sleeper Id
     */
    sleeper_id: string;
    /**
     * Team Id
     */
    team_id?: string | null;
};

/**
 * WhatChangedCard
 */
export type WhatChangedCard = {
    /**
     * Asset Name
     */
    asset_name?: string | null;
    /**
     * Card Id
     */
    card_id?: string | null;
    /**
     * Card Type
     */
    card_type?: string | null;
    roster_capacity_context?: WhatChangedRosterCapacityContext | null;
};

/**
 * WhatChangedCutCandidate
 */
export type WhatChangedCutCandidate = {
    /**
     * Cut Priority
     */
    cut_priority?: number | null;
    /**
     * Dvs
     */
    dvs?: number | null;
    /**
     * Player Name
     */
    player_name?: string | null;
    /**
     * Position
     */
    position?: string | null;
    /**
     * Sleeper Player Id
     */
    sleeper_player_id?: string | null;
    /**
     * Xvar Pct
     */
    xvar_pct?: number | null;
};

/**
 * WhatChangedDailyDiff
 */
export type WhatChangedDailyDiff = {
    /**
     * Decision Supported
     */
    decision_supported: false;
    market: WhatChangedMarketSection;
    model: WhatChangedModelSection;
    /**
     * Overall Status
     */
    overall_status: string;
};

/**
 * WhatChangedDropSummary
 */
export type WhatChangedDropSummary = {
    /**
     * Cuts Required
     */
    cuts_required?: number | null;
    /**
     * Roster Id
     */
    roster_id?: number | null;
    /**
     * Total Capacity
     */
    total_capacity?: number | null;
    /**
     * Total Players
     */
    total_players?: number | null;
};

/**
 * WhatChangedEnteredExited
 */
export type WhatChangedEnteredExited = {
    /**
     * Player Key
     */
    player_key: string;
    /**
     * Sleeper Id
     */
    sleeper_id: string;
};

/**
 * WhatChangedMarketDelta
 */
export type WhatChangedMarketDelta = {
    /**
     * Market Series
     */
    market_series?: {
        [key: string]: unknown;
    } | null;
    /**
     * Model Series
     */
    model_series?: {
        [key: string]: unknown;
    } | null;
    /**
     * Overall Rank Delta
     */
    overall_rank_delta: number;
    /**
     * Overall Rank Delta Direction
     */
    overall_rank_delta_direction: string;
    /**
     * Player Key
     */
    player_key: string;
    /**
     * Player Name
     */
    player_name?: string | null;
    /**
     * Position
     */
    position?: string | null;
    /**
     * Position Rank Delta
     */
    position_rank_delta: number;
    /**
     * Position Rank Delta Direction
     */
    position_rank_delta_direction: string;
    /**
     * Sleeper Id
     */
    sleeper_id: string;
    /**
     * Team Id
     */
    team_id?: string | null;
    /**
     * Value Delta
     */
    value_delta: number;
    /**
     * Value Delta Direction
     */
    value_delta_direction: string;
};

/**
 * WhatChangedMarketSection
 */
export type WhatChangedMarketSection = {
    /**
     * Aborted Reason
     */
    aborted_reason?: string | null;
    /**
     * Comparison Window
     */
    comparison_window?: {
        [key: string]: unknown;
    } | null;
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Entered
     */
    entered?: Array<WhatChangedEnteredExited> | null;
    /**
     * Exited
     */
    exited?: Array<WhatChangedEnteredExited> | null;
    /**
     * Market Source
     */
    market_source: string;
    /**
     * Roster Deltas
     */
    roster_deltas?: Array<WhatChangedMarketDelta> | null;
    /**
     * Status
     */
    status: string;
    /**
     * Top Movers
     */
    top_movers?: Array<WhatChangedMarketDelta> | null;
    /**
     * Total Movers Count
     */
    total_movers_count?: number | null;
};

/**
 * WhatChangedModelComparisonWindow
 *
 * Allowlisted, shape-closed model window — no market key can hide on it.
 *
 * Admits ONLY the three honest model window shapes:
 * 1. ``{status: insufficient_history}`` — status alone.
 * 2. ``{status: model_multi_vintage_ambiguous, from_date, to_date, ambiguous_dates}``.
 * 3. ``{from_date, to_date, from_vintage, to_vintage}`` — clean two-date window, no status.
 *
 * ``extra="forbid"`` (via ``_Strict``) rejects unknown keys (incl. a nested
 * ``market_overlay``); the ``Literal`` status rejects unknown states; and the
 * post-validator rejects mixed/partial combinations so the window is fully closed.
 */
export type WhatChangedModelComparisonWindow = {
    /**
     * Ambiguous Dates
     */
    ambiguous_dates?: Array<string> | null;
    /**
     * From Date
     */
    from_date?: string | null;
    from_vintage?: WhatChangedVintage | null;
    /**
     * Status
     */
    status?: 'insufficient_history' | 'model_multi_vintage_ambiguous' | null;
    /**
     * To Date
     */
    to_date?: string | null;
    to_vintage?: WhatChangedVintage | null;
};

/**
 * WhatChangedModelDelta
 */
export type WhatChangedModelDelta = {
    /**
     * Dvs Pct Delta
     */
    dvs_pct_delta: number;
    /**
     * Dynasty Value Score Delta
     */
    dynasty_value_score_delta: number;
    /**
     * Dynasty Value Score Delta Direction
     */
    dynasty_value_score_delta_direction: string;
    /**
     * Market Series
     */
    market_series?: {
        [key: string]: unknown;
    } | null;
    /**
     * Model Series
     */
    model_series?: {
        [key: string]: unknown;
    } | null;
    /**
     * Player Key
     */
    player_key: string;
    /**
     * Player Name
     */
    player_name?: string | null;
    /**
     * Position
     */
    position?: string | null;
    /**
     * Sleeper Id
     */
    sleeper_id?: string | null;
    /**
     * Team Id
     */
    team_id?: string | null;
    /**
     * Xvar Delta
     */
    xvar_delta: number;
};

/**
 * WhatChangedModelFeatureFreshness
 *
 * Descriptive engine_b feature-source freshness for the model section.
 *
 * Discloses which feature CSV backed the model vintage (a published runtime vs the
 * committed seed) and its hashes/as-of label, so the daily digest can show that captured
 * vintages are genuinely moving. Carries NO market field and certifies no decision.
 */
export type WhatChangedModelFeatureFreshness = {
    /**
     * Aborted Reason
     */
    aborted_reason?: string | null;
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Feature Csv Path
     */
    feature_csv_path?: string | null;
    /**
     * Feature Csv Sha256
     */
    feature_csv_sha256?: string | null;
    /**
     * Feature Source Kind
     */
    feature_source_kind?: 'runtime' | 'seed' | null;
    /**
     * Feature Source Status
     */
    feature_source_status?: 'not_ready' | null;
    /**
     * Published Seed Sha256
     */
    published_seed_sha256?: string | null;
    /**
     * Source As Of
     */
    source_as_of?: string | null;
};

/**
 * WhatChangedModelPvoSeedStaleness
 *
 * Descriptive seed-vs-runtime drift summary — the §3.6 manual-promotion tripwire.
 *
 * Surfaced ONLY when ``promotion_review_threshold_crossed`` is True (silent on quiet drift).
 * The field states the descriptive FACT that drift crossed the model-promotion review
 * threshold — it directs no action (David, the operator, decides). The count of
 * model-supported players drifted >5% and the coverage-count change are the stable triggers;
 * ``mean_abs_value_delta`` / ``p95_abs_value_delta`` are DISCLOSURE-only (never promotion
 * triggers — market-noise-sensitive). Carries no market field; certifies no decision.
 */
export type WhatChangedModelPvoSeedStaleness = {
    /**
     * Baseline Status
     */
    baseline_status?: string | null;
    /**
     * Count Model Supported Players Drifted Gt 5Pct
     */
    count_model_supported_players_drifted_gt_5pct: number;
    /**
     * Count Players Drifted Gt 5Pct
     */
    count_players_drifted_gt_5pct: number;
    /**
     * Coverage Count Deltas
     */
    coverage_count_deltas: {
        [key: string]: number;
    };
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Mean Abs Value Delta
     */
    mean_abs_value_delta: number;
    /**
     * P95 Abs Value Delta
     */
    p95_abs_value_delta: number;
    /**
     * Promotion Review Threshold Crossed
     */
    promotion_review_threshold_crossed: boolean;
    /**
     * Review Triggers
     */
    review_triggers?: Array<string> | null;
    /**
     * Seed Age Days
     */
    seed_age_days?: number | null;
    /**
     * Seed As Of
     */
    seed_as_of?: string | null;
};

/**
 * WhatChangedModelPvoStaleness
 *
 * Descriptive PVO source provenance for the model section + passive seed-staleness.
 *
 * Provenance (source kind / hashes / as-of / paths) is ALWAYS disclosed so the digest can
 * show which artifact backed the vintage. The ``seed_staleness`` block appears only on the
 * promotion tripwire. A present-but-unverified runtime surfaces as ``not_ready`` (kind None
 * + ``aborted_reason``), never hidden. Closed vocabularies so the API cannot report a
 * phantom source kind/status. Carries NO market field and certifies no decision.
 */
export type WhatChangedModelPvoStaleness = {
    /**
     * Aborted Reason
     */
    aborted_reason?: string | null;
    /**
     * Coverage Path
     */
    coverage_path?: string | null;
    /**
     * Coverage Sha256
     */
    coverage_sha256?: string | null;
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Pvo Path
     */
    pvo_path?: string | null;
    /**
     * Pvo Sha256
     */
    pvo_sha256?: string | null;
    /**
     * Pvo Source Kind
     */
    pvo_source_kind?: 'runtime' | 'seed' | null;
    /**
     * Pvo Source Status
     */
    pvo_source_status?: 'not_ready' | null;
    seed_staleness?: WhatChangedModelPvoSeedStaleness | null;
    /**
     * Source As Of
     */
    source_as_of?: string | null;
};

/**
 * WhatChangedModelSection
 */
export type WhatChangedModelSection = {
    comparison_window?: WhatChangedModelComparisonWindow | null;
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Deltas
     */
    deltas?: Array<WhatChangedModelDelta> | null;
    feature_freshness?: WhatChangedModelFeatureFreshness | null;
    pvo_staleness?: WhatChangedModelPvoStaleness | null;
    /**
     * Status
     */
    status: string;
    /**
     * Vintage Changed
     */
    vintage_changed?: boolean | null;
};

/**
 * WhatChangedPartnerRanking
 */
export type WhatChangedPartnerRanking = {
    /**
     * Counterparty Roster Id
     */
    counterparty_roster_id?: number | null;
    /**
     * Counterparty Team Name
     */
    counterparty_team_name?: string | null;
    /**
     * Matched Positions
     */
    matched_positions?: Array<string> | null;
    /**
     * Partner Score
     */
    partner_score?: number | null;
};

/**
 * WhatChangedResponse
 */
export type WhatChangedResponse = {
    daily_diff: WhatChangedDailyDiff;
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * Generated At
     */
    generated_at: string;
    /**
     * Overall Status
     */
    overall_status: string;
    /**
     * Schema Version
     */
    schema_version: string;
    structural_context: WhatChangedStructuralContext;
};

/**
 * WhatChangedRosterCapacityContext
 */
export type WhatChangedRosterCapacityContext = {
    /**
     * Candidate Count
     */
    candidate_count?: number | null;
    /**
     * Hard Conflict Count
     */
    hard_conflict_count?: number | null;
    /**
     * Pool Status
     */
    pool_status?: string | null;
};

/**
 * WhatChangedStalenessCaveat
 */
export type WhatChangedStalenessCaveat = {
    /**
     * Age Hours
     */
    age_hours: number;
    /**
     * Basis
     */
    basis: string;
    /**
     * Is Stale
     */
    is_stale: boolean;
    /**
     * Report Generated At
     */
    report_generated_at: string;
};

/**
 * WhatChangedStructuralContext
 */
export type WhatChangedStructuralContext = {
    /**
     * Baseline Roster Rows
     */
    baseline_roster_rows?: Array<WhatChangedBaselineRosterRow> | null;
    /**
     * Current Not Delta
     */
    current_not_delta: boolean;
    /**
     * Decision Supported
     */
    decision_supported: false;
    sections: WhatChangedStructuralSections;
    /**
     * Status
     */
    status: string;
};

/**
 * WhatChangedStructuralSection
 */
export type WhatChangedStructuralSection = {
    /**
     * Aborted Reason
     */
    aborted_reason?: string | null;
    /**
     * Captured At
     */
    captured_at?: string | null;
    /**
     * Current Not Delta
     */
    current_not_delta: boolean;
    /**
     * David Posture
     */
    david_posture?: string | null;
    /**
     * David Roster Id
     */
    david_roster_id?: number | null;
    /**
     * David Roster Player Count
     */
    david_roster_player_count?: number | null;
    /**
     * David Team Name
     */
    david_team_name?: string | null;
    david_value_summary?: WhatChangedTeamValueSummary | null;
    /**
     * Decision Supported
     */
    decision_supported: false;
    /**
     * League Roster Count
     */
    league_roster_count?: number | null;
    /**
     * Source Path
     */
    source_path?: string | null;
    staleness_caveat?: WhatChangedStalenessCaveat | null;
    /**
     * Status
     */
    status: string;
    summary?: WhatChangedDropSummary | null;
    /**
     * Team Count
     */
    team_count?: number | null;
    /**
     * Top Candidates
     */
    top_candidates?: Array<WhatChangedCutCandidate> | null;
    /**
     * Top Cards
     */
    top_cards?: Array<WhatChangedCard> | null;
    /**
     * Top Partner Rankings
     */
    top_partner_rankings?: Array<WhatChangedPartnerRanking> | null;
};

/**
 * WhatChangedStructuralSections
 */
export type WhatChangedStructuralSections = {
    drop_pressure: WhatChangedStructuralSection;
    league_opportunity: WhatChangedStructuralSection;
    sleeper_snapshot: WhatChangedStructuralSection;
    team_posture: WhatChangedStructuralSection;
    team_value: WhatChangedStructuralSection;
};

/**
 * WhatChangedTeamValueSummary
 */
export type WhatChangedTeamValueSummary = {
    /**
     * Depth Credit Xvar
     */
    depth_credit_xvar?: number | null;
    /**
     * Lineup Xvar
     */
    lineup_xvar?: number | null;
    /**
     * Posture Label
     */
    posture_label?: string | null;
    /**
     * Roster Id
     */
    roster_id?: number | null;
    /**
     * Starter Weighted Xvar
     */
    starter_weighted_xvar?: number | null;
    /**
     * Team Name
     */
    team_name?: string | null;
    /**
     * Top N Xvar
     */
    top_n_xvar?: number | null;
    /**
     * Total Xvar Capped
     */
    total_xvar_capped?: number | null;
};

/**
 * WhatChangedVintage
 *
 * A complete model vintage — both hashes required and non-blank.
 *
 * A vintage is the identity of a model output; a partial/empty vintage is never an
 * honest shape, so both fields are required (not Optional) and rejected if blank.
 */
export type WhatChangedVintage = {
    /**
     * Provenance Hash
     */
    provenance_hash: string;
    /**
     * Semantic Output Hash
     */
    semantic_output_hash: string;
};

export type GetEngineBScoresApiEngineBScoresGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/engine-b/scores';
};

export type GetEngineBScoresApiEngineBScoresGetResponses = {
    /**
     * Response Get Engine B Scores Api Engine B Scores Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetEngineBScoresApiEngineBScoresGetResponse = GetEngineBScoresApiEngineBScoresGetResponses[keyof GetEngineBScoresApiEngineBScoresGetResponses];

export type GetSystemHealthApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetSystemHealthApiHealthGetErrors = {
    /**
     * Service Unavailable
     */
    503: SystemHealthErrorResponse;
};

export type GetSystemHealthApiHealthGetError = GetSystemHealthApiHealthGetErrors[keyof GetSystemHealthApiHealthGetErrors];

export type GetSystemHealthApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: SystemHealthResponse;
};

export type GetSystemHealthApiHealthGetResponse = GetSystemHealthApiHealthGetResponses[keyof GetSystemHealthApiHealthGetResponses];

export type LeaguePulseSurfaceApiLeaguePulseGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/league/pulse';
};

export type LeaguePulseSurfaceApiLeaguePulseGetResponses = {
    /**
     * Successful Response
     */
    200: LeaguePulseResponse;
};

export type LeaguePulseSurfaceApiLeaguePulseGetResponse = LeaguePulseSurfaceApiLeaguePulseGetResponses[keyof LeaguePulseSurfaceApiLeaguePulseGetResponses];

export type WhatChangedSurfaceApiLeagueWhatChangedGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/league/what-changed';
};

export type WhatChangedSurfaceApiLeagueWhatChangedGetResponses = {
    /**
     * Successful Response
     */
    200: WhatChangedResponse;
};

export type WhatChangedSurfaceApiLeagueWhatChangedGetResponse = WhatChangedSurfaceApiLeagueWhatChangedGetResponses[keyof WhatChangedSurfaceApiLeagueWhatChangedGetResponses];

export type GetPlayerDetailApiPlayersSleeperIdGetData = {
    body?: never;
    path: {
        /**
         * Sleeper Id
         */
        sleeper_id: string;
    };
    query?: never;
    url: '/api/players/{sleeper_id}';
};

export type GetPlayerDetailApiPlayersSleeperIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPlayerDetailApiPlayersSleeperIdGetError = GetPlayerDetailApiPlayersSleeperIdGetErrors[keyof GetPlayerDetailApiPlayersSleeperIdGetErrors];

export type GetPlayerDetailApiPlayersSleeperIdGetResponses = {
    /**
     * Successful Response
     */
    200: PlayerDetailResponse;
};

export type GetPlayerDetailApiPlayersSleeperIdGetResponse = GetPlayerDetailApiPlayersSleeperIdGetResponses[keyof GetPlayerDetailApiPlayersSleeperIdGetResponses];

export type RealizedOutcomeScorecardApiRealizedOutcomeScorecardGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/realized-outcome/scorecard';
};

export type RealizedOutcomeScorecardApiRealizedOutcomeScorecardGetErrors = {
    /**
     * Service Unavailable
     */
    503: RealizedOutcomeScorecardErrorResponse;
};

export type RealizedOutcomeScorecardApiRealizedOutcomeScorecardGetError = RealizedOutcomeScorecardApiRealizedOutcomeScorecardGetErrors[keyof RealizedOutcomeScorecardApiRealizedOutcomeScorecardGetErrors];

export type RealizedOutcomeScorecardApiRealizedOutcomeScorecardGetResponses = {
    /**
     * Successful Response
     */
    200: RealizedOutcomeScorecardResponse;
};

export type RealizedOutcomeScorecardApiRealizedOutcomeScorecardGetResponse = RealizedOutcomeScorecardApiRealizedOutcomeScorecardGetResponses[keyof RealizedOutcomeScorecardApiRealizedOutcomeScorecardGetResponses];

export type ScoreSingleApiRookiesScorePostData = {
    body: ProspectRequest;
    path?: never;
    query?: never;
    url: '/api/rookies/score';
};

export type ScoreSingleApiRookiesScorePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScoreSingleApiRookiesScorePostError = ScoreSingleApiRookiesScorePostErrors[keyof ScoreSingleApiRookiesScorePostErrors];

export type ScoreSingleApiRookiesScorePostResponses = {
    /**
     * Response Score Single Api Rookies Score Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ScoreSingleApiRookiesScorePostResponse = ScoreSingleApiRookiesScorePostResponses[keyof ScoreSingleApiRookiesScorePostResponses];

export type ScoreClassApiRookiesScoreClassPostData = {
    /**
     * Prospects
     */
    body: Array<ProspectRequest>;
    path?: never;
    query?: never;
    url: '/api/rookies/score-class';
};

export type ScoreClassApiRookiesScoreClassPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScoreClassApiRookiesScoreClassPostError = ScoreClassApiRookiesScoreClassPostErrors[keyof ScoreClassApiRookiesScoreClassPostErrors];

export type ScoreClassApiRookiesScoreClassPostResponses = {
    /**
     * Response Score Class Api Rookies Score Class Post
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ScoreClassApiRookiesScoreClassPostResponse = ScoreClassApiRookiesScoreClassPostResponses[keyof ScoreClassApiRookiesScoreClassPostResponses];

export type AuditRosterApiRosterAuditGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/roster/audit';
};

export type AuditRosterApiRosterAuditGetResponses = {
    /**
     * Successful Response
     */
    200: RosterAuditResponse;
};

export type AuditRosterApiRosterAuditGetResponse = AuditRosterApiRosterAuditGetResponses[keyof AuditRosterApiRosterAuditGetResponses];

export type RosterCapacitySurfaceApiRosterCapacityGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/roster/capacity';
};

export type RosterCapacitySurfaceApiRosterCapacityGetErrors = {
    /**
     * Service Unavailable
     */
    503: RosterCapacityErrorResponse;
};

export type RosterCapacitySurfaceApiRosterCapacityGetError = RosterCapacitySurfaceApiRosterCapacityGetErrors[keyof RosterCapacitySurfaceApiRosterCapacityGetErrors];

export type RosterCapacitySurfaceApiRosterCapacityGetResponses = {
    /**
     * Successful Response
     */
    200: RosterCapacityResponse;
};

export type RosterCapacitySurfaceApiRosterCapacityGetResponse = RosterCapacitySurfaceApiRosterCapacityGetResponses[keyof RosterCapacitySurfaceApiRosterCapacityGetResponses];

export type GetCaptureHealthApiSystemCaptureHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/capture-health';
};

export type GetCaptureHealthApiSystemCaptureHealthGetErrors = {
    /**
     * Service Unavailable
     */
    503: CaptureHealthErrorResponse;
};

export type GetCaptureHealthApiSystemCaptureHealthGetError = GetCaptureHealthApiSystemCaptureHealthGetErrors[keyof GetCaptureHealthApiSystemCaptureHealthGetErrors];

export type GetCaptureHealthApiSystemCaptureHealthGetResponses = {
    /**
     * Successful Response
     */
    200: CaptureHealthResponse;
};

export type GetCaptureHealthApiSystemCaptureHealthGetResponse = GetCaptureHealthApiSystemCaptureHealthGetResponses[keyof GetCaptureHealthApiSystemCaptureHealthGetResponses];

export type GetModelProvenanceApiSystemModelProvenanceGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/model-provenance';
};

export type GetModelProvenanceApiSystemModelProvenanceGetErrors = {
    /**
     * Service Unavailable
     */
    503: ModelProvenanceErrorResponse;
};

export type GetModelProvenanceApiSystemModelProvenanceGetError = GetModelProvenanceApiSystemModelProvenanceGetErrors[keyof GetModelProvenanceApiSystemModelProvenanceGetErrors];

export type GetModelProvenanceApiSystemModelProvenanceGetResponses = {
    /**
     * Successful Response
     */
    200: ModelProvenanceResponse;
};

export type GetModelProvenanceApiSystemModelProvenanceGetResponse = GetModelProvenanceApiSystemModelProvenanceGetResponses[keyof GetModelProvenanceApiSystemModelProvenanceGetResponses];

export type GetTierReadinessApiSystemTierReadinessGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/system/tier-readiness';
};

export type GetTierReadinessApiSystemTierReadinessGetErrors = {
    /**
     * Service Unavailable
     */
    503: TierReadinessErrorResponse;
};

export type GetTierReadinessApiSystemTierReadinessGetError = GetTierReadinessApiSystemTierReadinessGetErrors[keyof GetTierReadinessApiSystemTierReadinessGetErrors];

export type GetTierReadinessApiSystemTierReadinessGetResponses = {
    /**
     * Successful Response
     */
    200: TierReadinessResponse;
};

export type GetTierReadinessApiSystemTierReadinessGetResponse = GetTierReadinessApiSystemTierReadinessGetResponses[keyof GetTierReadinessApiSystemTierReadinessGetResponses];

export type AnalyzeApiTradeAnalyzePostData = {
    body: TradeRequest;
    path?: never;
    query?: never;
    url: '/api/trade/analyze';
};

export type AnalyzeApiTradeAnalyzePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyzeApiTradeAnalyzePostError = AnalyzeApiTradeAnalyzePostErrors[keyof AnalyzeApiTradeAnalyzePostErrors];

export type AnalyzeApiTradeAnalyzePostResponses = {
    /**
     * Response Analyze Api Trade Analyze Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AnalyzeApiTradeAnalyzePostResponse = AnalyzeApiTradeAnalyzePostResponses[keyof AnalyzeApiTradeAnalyzePostResponses];

export type TradeAssetsApiTradeAssetsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/trade/assets';
};

export type TradeAssetsApiTradeAssetsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TradeAssetsApiTradeAssetsGetError = TradeAssetsApiTradeAssetsGetErrors[keyof TradeAssetsApiTradeAssetsGetErrors];

export type TradeAssetsApiTradeAssetsGetResponses = {
    /**
     * Successful Response
     */
    200: TradeAssetCatalogResponse;
};

export type TradeAssetsApiTradeAssetsGetResponse = TradeAssetsApiTradeAssetsGetResponses[keyof TradeAssetsApiTradeAssetsGetResponses];

export type EvaluateTradeEndpointApiTradeEvaluatePostData = {
    body: TradeEvaluateRequest;
    path?: never;
    query?: never;
    url: '/api/trade/evaluate';
};

export type EvaluateTradeEndpointApiTradeEvaluatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EvaluateTradeEndpointApiTradeEvaluatePostError = EvaluateTradeEndpointApiTradeEvaluatePostErrors[keyof EvaluateTradeEndpointApiTradeEvaluatePostErrors];

export type EvaluateTradeEndpointApiTradeEvaluatePostResponses = {
    /**
     * Successful Response
     */
    200: TradeEvaluation;
};

export type EvaluateTradeEndpointApiTradeEvaluatePostResponse = EvaluateTradeEndpointApiTradeEvaluatePostResponses[keyof EvaluateTradeEndpointApiTradeEvaluatePostResponses];

export type ReconcileTradeEndpointApiTradeReconcilePostData = {
    body: TradeReconcileRequest;
    path?: never;
    query?: never;
    url: '/api/trade/reconcile';
};

export type ReconcileTradeEndpointApiTradeReconcilePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReconcileTradeEndpointApiTradeReconcilePostError = ReconcileTradeEndpointApiTradeReconcilePostErrors[keyof ReconcileTradeEndpointApiTradeReconcilePostErrors];

export type ReconcileTradeEndpointApiTradeReconcilePostResponses = {
    /**
     * Successful Response
     */
    200: TradeRosterReconciliation;
};

export type ReconcileTradeEndpointApiTradeReconcilePostResponse = ReconcileTradeEndpointApiTradeReconcilePostResponses[keyof ReconcileTradeEndpointApiTradeReconcilePostResponses];

export type ReconcileTradeMarketEndpointApiTradeReconcileMarketPostData = {
    body: MarketReconcileRequest;
    path?: never;
    query?: never;
    url: '/api/trade/reconcile/market';
};

export type ReconcileTradeMarketEndpointApiTradeReconcileMarketPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReconcileTradeMarketEndpointApiTradeReconcileMarketPostError = ReconcileTradeMarketEndpointApiTradeReconcileMarketPostErrors[keyof ReconcileTradeMarketEndpointApiTradeReconcileMarketPostErrors];

export type ReconcileTradeMarketEndpointApiTradeReconcileMarketPostResponses = {
    /**
     * Successful Response
     */
    200: TradeMarketReconciliation;
};

export type ReconcileTradeMarketEndpointApiTradeReconcileMarketPostResponse = ReconcileTradeMarketEndpointApiTradeReconcileMarketPostResponses[keyof ReconcileTradeMarketEndpointApiTradeReconcileMarketPostResponses];

export type GetTrustSurfaceApiTrustSurfacePositionGetData = {
    body?: never;
    path: {
        /**
         * Position
         */
        position: string;
    };
    query?: never;
    url: '/api/trust-surface/{position}';
};

export type GetTrustSurfaceApiTrustSurfacePositionGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTrustSurfaceApiTrustSurfacePositionGetError = GetTrustSurfaceApiTrustSurfacePositionGetErrors[keyof GetTrustSurfaceApiTrustSurfacePositionGetErrors];

export type GetTrustSurfaceApiTrustSurfacePositionGetResponses = {
    /**
     * Successful Response
     */
    200: TrustSurfaceResponse;
};

export type GetTrustSurfaceApiTrustSurfacePositionGetResponse = GetTrustSurfaceApiTrustSurfacePositionGetResponses[keyof GetTrustSurfaceApiTrustSurfacePositionGetResponses];

export type GetModelCardApiTrustSurfacePositionModelCardGetData = {
    body?: never;
    path: {
        /**
         * Position
         */
        position: string;
    };
    query?: never;
    url: '/api/trust-surface/{position}/model-card';
};

export type GetModelCardApiTrustSurfacePositionModelCardGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetModelCardApiTrustSurfacePositionModelCardGetError = GetModelCardApiTrustSurfacePositionModelCardGetErrors[keyof GetModelCardApiTrustSurfacePositionModelCardGetErrors];

export type GetModelCardApiTrustSurfacePositionModelCardGetResponses = {
    /**
     * Successful Response
     */
    200: ModelCardResponse;
};

export type GetModelCardApiTrustSurfacePositionModelCardGetResponse = GetModelCardApiTrustSurfacePositionModelCardGetResponses[keyof GetModelCardApiTrustSurfacePositionModelCardGetResponses];
