// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * DivergenceResult
 *
 * Gate 4. Populated only when sufficient FC snapshots and flagged player data exist.
 */
export type DivergenceResult = {
    /**
     * Diff Bca Ci95
     */
    diff_bca_ci95: [
        number,
        number
    ];
    /**
     * Forward Horizon Days
     */
    forward_horizon_days: number;
    /**
     * Hit Rate
     */
    hit_rate: number;
    /**
     * Hit Rate Wilson Ci95
     */
    hit_rate_wilson_ci95: [
        number,
        number
    ];
    /**
     * Mann Whitney Method
     */
    mann_whitney_method: string;
    /**
     * Mann Whitney P
     */
    mann_whitney_p: number;
    /**
     * Mann Whitney U
     */
    mann_whitney_u: number;
    /**
     * Mean Alpha Control
     */
    mean_alpha_control: number;
    /**
     * Mean Alpha Flagged
     */
    mean_alpha_flagged: number;
    /**
     * N Excluded Injury
     */
    n_excluded_injury: number;
    /**
     * N Flagged
     */
    n_flagged: number;
    /**
     * N Matched Controls Per Flag
     */
    n_matched_controls_per_flag?: number;
    /**
     * Position Beta
     */
    position_beta: number;
};

/**
 * FoldResult
 */
export type FoldResult = {
    /**
     * Calibration By Decile
     */
    calibration_by_decile?: Array<number> | null;
    /**
     * Feature Coefficients
     */
    feature_coefficients?: {
        [key: string]: number;
    } | null;
    /**
     * Fold Index
     */
    fold_index: number;
    /**
     * Kendall Tau
     */
    kendall_tau: number;
    /**
     * Kendall Tau Bca Ci95
     */
    kendall_tau_bca_ci95: [
        number,
        number
    ];
    /**
     * Mae
     */
    mae: number;
    /**
     * Market Pool N
     */
    market_pool_n?: number | null;
    /**
     * Metric Caveats
     */
    metric_caveats?: Array<string>;
    /**
     * N Excluded Injury
     */
    n_excluded_injury?: number;
    /**
     * N Test
     */
    n_test: number;
    /**
     * N Train
     */
    n_train: number;
    /**
     * Ndcg At 12 Market
     */
    ndcg_at_12_market?: number | null;
    /**
     * Ndcg At 12 Model
     */
    ndcg_at_12_model?: number | null;
    /**
     * Ndcg At 24 Market
     */
    ndcg_at_24_market?: number | null;
    /**
     * Ndcg At 24 Model
     */
    ndcg_at_24_model?: number | null;
    /**
     * Ndcg Diff Bca Ci95
     */
    ndcg_diff_bca_ci95?: [
        number,
        number
    ] | null;
    /**
     * Ndcg Diff Primary K
     */
    ndcg_diff_primary_k?: number | null;
    /**
     * Outcome Seasons
     */
    outcome_seasons: Array<number>;
    /**
     * Precision At K
     */
    precision_at_k?: {
        [key: string]: TopKResult;
    } | null;
    /**
     * Primary K
     */
    primary_k?: number | null;
    /**
     * R2 Oos
     */
    r2_oos?: number | null;
    /**
     * Rank Ic
     */
    rank_ic: number;
    /**
     * Regime Notes
     */
    regime_notes?: string | null;
    /**
     * Rmse
     */
    rmse: number;
    /**
     * Spearman Rho
     */
    spearman_rho: number;
    /**
     * Spearman Rho Bca Ci95
     */
    spearman_rho_bca_ci95: [
        number,
        number
    ];
    /**
     * Test Year
     */
    test_year: number;
    /**
     * Train Years
     */
    train_years: Array<number>;
};

/**
 * GateResult
 */
export type GateResult = {
    /**
     * G1 Rank Correlation Pass
     */
    g1_rank_correlation_pass: boolean;
    /**
     * G2 Rmse Stability Pass
     */
    g2_rmse_stability_pass: boolean;
    /**
     * G3 Market Superiority Pass
     */
    g3_market_superiority_pass: true | false | 'deferred';
    /**
     * G4 Divergence Validity Pass
     */
    g4_divergence_validity_pass: true | false | 'deferred' | 'insufficient_data';
    /**
     * Gate Version
     */
    gate_version?: string;
    /**
     * Overall Grade
     */
    overall_grade: 'PRE_MODEL' | 'EXPERIMENTAL' | 'ACTIVE_B' | 'ACTIVE_B_VALIDATED' | 'DECISION_GRADE';
    /**
     * Promotion Justification
     */
    promotion_justification: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MarketReconcileRequest
 */
export type MarketReconcileRequest = {
    /**
     * Counterparty Roster Id
     */
    counterparty_roster_id?: number | null;
    /**
     * Current Draft Year
     */
    current_draft_year?: number;
    /**
     * Format Key
     */
    format_key?: string;
    /**
     * Received Assets
     */
    received_assets: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Sent Assets
     */
    sent_assets: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * ModelReliability
 *
 * QB-only descriptive model-reliability stamp (measured uncertainty, no verdict).
 */
export type ModelReliability = {
    /**
     * Caveat
     */
    caveat: string;
    /**
     * Position
     */
    position: string;
    /**
     * R2 Oos Mean
     */
    r2_oos_mean?: number | null;
    /**
     * Spearman Rho Mean
     */
    spearman_rho_mean?: number | null;
};

/**
 * ProspectRequest
 */
export type ProspectRequest = {
    /**
     * Age
     */
    age: number;
    /**
     * Draft Class
     */
    draft_class?: number | null;
    /**
     * Final College Age
     */
    final_college_age?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Pick
     */
    pick: number;
    /**
     * Position
     */
    position: string;
    /**
     * Round
     */
    round: number;
    /**
     * Sleeper Id
     */
    sleeper_id?: string | null;
    /**
     * Te Ryptpa Final
     */
    te_ryptpa_final?: number | null;
    /**
     * Te Yards Per Reception Career
     */
    te_yards_per_reception_career?: number | null;
};

/**
 * StabilityResult
 */
export type StabilityResult = {
    /**
     * Dm Hln Pvalue
     */
    dm_hln_pvalue?: number | null;
    /**
     * Dm Hln Statistic
     */
    dm_hln_statistic?: number | null;
    /**
     * Dm Method
     */
    dm_method?: string;
    /**
     * Dm Passes
     */
    dm_passes?: boolean | null;
    /**
     * Rmse Cv
     */
    rmse_cv: number;
    /**
     * Rmse Max Deviation Pct
     */
    rmse_max_deviation_pct: number;
    /**
     * Rmse Mean
     */
    rmse_mean: number;
    /**
     * Rmse Per Fold
     */
    rmse_per_fold: Array<number>;
};

/**
 * TopKResult
 */
export type TopKResult = {
    /**
     * Diff Wilson Ci95
     */
    diff_wilson_ci95: [
        number,
        number
    ];
    /**
     * K
     */
    k: number;
    /**
     * Market Hit Rate
     */
    market_hit_rate: number;
    /**
     * Model Hit Rate
     */
    model_hit_rate: number;
};

/**
 * TradeEvaluateRequest
 */
export type TradeEvaluateRequest = {
    /**
     * Side A
     */
    side_a: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Side B
     */
    side_b: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * TradeReconcileRequest
 */
export type TradeReconcileRequest = {
    /**
     * David Assets
     */
    david_assets: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Received Assets
     */
    received_assets: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * TradeRequest
 */
export type TradeRequest = {
    /**
     * My Assets
     */
    my_assets: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Their Assets
     */
    their_assets: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * TrustSurfaceResponse
 *
 * Typed Trust Surface contract: the full BacktestResult plus the hoisted,
 * consumer-facing fields. Non-breaking superset of the prior dict response, so the
 * frontend Hey API codegen has a real OpenAPI schema (no untyped object).
 */
export type TrustSurfaceResponse = {
    divergence_validity?: DivergenceResult | null;
    /**
     * Experimental
     */
    experimental: boolean;
    /**
     * Folds
     */
    folds: Array<FoldResult>;
    /**
     * Git Sha
     */
    git_sha?: string | null;
    /**
     * Market Snapshot Dates
     */
    market_snapshot_dates?: {
        [key: string]: string;
    } | null;
    /**
     * Market Source
     */
    market_source: 'fc_native' | 'dp_archive' | 'ktc_community_csv' | 'unavailable';
    /**
     * Market Source Label
     */
    market_source_label?: 'fantasycalc_native' | 'dynastyprocess_ecr_2qb' | 'ktc_community_csv' | 'unavailable';
    /**
     * Model Artifact Hash
     */
    model_artifact_hash: string;
    /**
     * Model Card Available
     */
    model_card_available: boolean;
    model_reliability?: ModelReliability | null;
    /**
     * Model Version
     */
    model_version: string;
    /**
     * Overall Grade
     */
    overall_grade: string;
    /**
     * Position
     */
    position: 'QB' | 'RB' | 'WR' | 'TE';
    promotion_gate: GateResult;
    /**
     * Retrain Mode
     */
    retrain_mode: 'refit_per_fold_fixed_alpha' | 'frozen_retrospective';
    /**
     * Ridge Alpha
     */
    ridge_alpha: number;
    rmse_stability: StabilityResult;
    /**
     * Run Date
     */
    run_date: string;
    /**
     * Run Id
     */
    run_id?: string;
    /**
     * Schema Version
     */
    schema_version?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetEngineBScoresApiEngineBScoresGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/engine-b/scores';
};

export type GetEngineBScoresApiEngineBScoresGetResponses = {
    /**
     * Response Get Engine B Scores Api Engine B Scores Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetEngineBScoresApiEngineBScoresGetResponse = GetEngineBScoresApiEngineBScoresGetResponses[keyof GetEngineBScoresApiEngineBScoresGetResponses];

export type ScoreSingleApiRookiesScorePostData = {
    body: ProspectRequest;
    path?: never;
    query?: never;
    url: '/api/rookies/score';
};

export type ScoreSingleApiRookiesScorePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScoreSingleApiRookiesScorePostError = ScoreSingleApiRookiesScorePostErrors[keyof ScoreSingleApiRookiesScorePostErrors];

export type ScoreSingleApiRookiesScorePostResponses = {
    /**
     * Response Score Single Api Rookies Score Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ScoreSingleApiRookiesScorePostResponse = ScoreSingleApiRookiesScorePostResponses[keyof ScoreSingleApiRookiesScorePostResponses];

export type ScoreClassApiRookiesScoreClassPostData = {
    /**
     * Prospects
     */
    body: Array<ProspectRequest>;
    path?: never;
    query?: never;
    url: '/api/rookies/score-class';
};

export type ScoreClassApiRookiesScoreClassPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScoreClassApiRookiesScoreClassPostError = ScoreClassApiRookiesScoreClassPostErrors[keyof ScoreClassApiRookiesScoreClassPostErrors];

export type ScoreClassApiRookiesScoreClassPostResponses = {
    /**
     * Response Score Class Api Rookies Score Class Post
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ScoreClassApiRookiesScoreClassPostResponse = ScoreClassApiRookiesScoreClassPostResponses[keyof ScoreClassApiRookiesScoreClassPostResponses];

export type AuditRosterApiRosterAuditGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/roster/audit';
};

export type AuditRosterApiRosterAuditGetResponses = {
    /**
     * Response Audit Roster Api Roster Audit Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AuditRosterApiRosterAuditGetResponse = AuditRosterApiRosterAuditGetResponses[keyof AuditRosterApiRosterAuditGetResponses];

export type AnalyzeApiTradeAnalyzePostData = {
    body: TradeRequest;
    path?: never;
    query?: never;
    url: '/api/trade/analyze';
};

export type AnalyzeApiTradeAnalyzePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyzeApiTradeAnalyzePostError = AnalyzeApiTradeAnalyzePostErrors[keyof AnalyzeApiTradeAnalyzePostErrors];

export type AnalyzeApiTradeAnalyzePostResponses = {
    /**
     * Response Analyze Api Trade Analyze Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AnalyzeApiTradeAnalyzePostResponse = AnalyzeApiTradeAnalyzePostResponses[keyof AnalyzeApiTradeAnalyzePostResponses];

export type EvaluateTradeEndpointApiTradeEvaluatePostData = {
    body: TradeEvaluateRequest;
    path?: never;
    query?: never;
    url: '/api/trade/evaluate';
};

export type EvaluateTradeEndpointApiTradeEvaluatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EvaluateTradeEndpointApiTradeEvaluatePostError = EvaluateTradeEndpointApiTradeEvaluatePostErrors[keyof EvaluateTradeEndpointApiTradeEvaluatePostErrors];

export type EvaluateTradeEndpointApiTradeEvaluatePostResponses = {
    /**
     * Response Evaluate Trade Endpoint Api Trade Evaluate Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type EvaluateTradeEndpointApiTradeEvaluatePostResponse = EvaluateTradeEndpointApiTradeEvaluatePostResponses[keyof EvaluateTradeEndpointApiTradeEvaluatePostResponses];

export type ReconcileTradeEndpointApiTradeReconcilePostData = {
    body: TradeReconcileRequest;
    path?: never;
    query?: never;
    url: '/api/trade/reconcile';
};

export type ReconcileTradeEndpointApiTradeReconcilePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReconcileTradeEndpointApiTradeReconcilePostError = ReconcileTradeEndpointApiTradeReconcilePostErrors[keyof ReconcileTradeEndpointApiTradeReconcilePostErrors];

export type ReconcileTradeEndpointApiTradeReconcilePostResponses = {
    /**
     * Response Reconcile Trade Endpoint Api Trade Reconcile Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ReconcileTradeEndpointApiTradeReconcilePostResponse = ReconcileTradeEndpointApiTradeReconcilePostResponses[keyof ReconcileTradeEndpointApiTradeReconcilePostResponses];

export type ReconcileTradeMarketEndpointApiTradeReconcileMarketPostData = {
    body: MarketReconcileRequest;
    path?: never;
    query?: never;
    url: '/api/trade/reconcile/market';
};

export type ReconcileTradeMarketEndpointApiTradeReconcileMarketPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReconcileTradeMarketEndpointApiTradeReconcileMarketPostError = ReconcileTradeMarketEndpointApiTradeReconcileMarketPostErrors[keyof ReconcileTradeMarketEndpointApiTradeReconcileMarketPostErrors];

export type ReconcileTradeMarketEndpointApiTradeReconcileMarketPostResponses = {
    /**
     * Response Reconcile Trade Market Endpoint Api Trade Reconcile Market Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ReconcileTradeMarketEndpointApiTradeReconcileMarketPostResponse = ReconcileTradeMarketEndpointApiTradeReconcileMarketPostResponses[keyof ReconcileTradeMarketEndpointApiTradeReconcileMarketPostResponses];

export type GetTrustSurfaceApiTrustSurfacePositionGetData = {
    body?: never;
    path: {
        /**
         * Position
         */
        position: string;
    };
    query?: never;
    url: '/api/trust-surface/{position}';
};

export type GetTrustSurfaceApiTrustSurfacePositionGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTrustSurfaceApiTrustSurfacePositionGetError = GetTrustSurfaceApiTrustSurfacePositionGetErrors[keyof GetTrustSurfaceApiTrustSurfacePositionGetErrors];

export type GetTrustSurfaceApiTrustSurfacePositionGetResponses = {
    /**
     * Successful Response
     */
    200: TrustSurfaceResponse;
};

export type GetTrustSurfaceApiTrustSurfacePositionGetResponse = GetTrustSurfaceApiTrustSurfacePositionGetResponses[keyof GetTrustSurfaceApiTrustSurfacePositionGetResponses];

export type GetModelCardApiTrustSurfacePositionModelCardGetData = {
    body?: never;
    path: {
        /**
         * Position
         */
        position: string;
    };
    query?: never;
    url: '/api/trust-surface/{position}/model-card';
};

export type GetModelCardApiTrustSurfacePositionModelCardGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetModelCardApiTrustSurfacePositionModelCardGetError = GetModelCardApiTrustSurfacePositionModelCardGetErrors[keyof GetModelCardApiTrustSurfacePositionModelCardGetErrors];

export type GetModelCardApiTrustSurfacePositionModelCardGetResponses = {
    /**
     * Response Get Model Card Api Trust Surface  Position  Model Card Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetModelCardApiTrustSurfacePositionModelCardGetResponse = GetModelCardApiTrustSurfacePositionModelCardGetResponses[keyof GetModelCardApiTrustSurfacePositionModelCardGetResponses];
