// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * CounterArgumentField
 */
export type CounterArgumentField = {
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Status
     */
    status: string;
    /**
     * Text
     */
    text: string | null;
};

/**
 * DegradationField
 */
export type DegradationField = {
    /**
     * Message
     */
    message: string;
};

/**
 * DivergenceField
 */
export type DivergenceField = {
    /**
     * Delta
     */
    delta: number | null;
    /**
     * Status
     */
    status: string;
};

/**
 * DivergenceResult
 *
 * Gate 4. Populated only when sufficient FC snapshots and flagged player data exist.
 */
export type DivergenceResult = {
    /**
     * Diff Bca Ci95
     */
    diff_bca_ci95: [
        number,
        number
    ];
    /**
     * Forward Horizon Days
     */
    forward_horizon_days: number;
    /**
     * Hit Rate
     */
    hit_rate: number;
    /**
     * Hit Rate Wilson Ci95
     */
    hit_rate_wilson_ci95: [
        number,
        number
    ];
    /**
     * Mann Whitney Method
     */
    mann_whitney_method: string;
    /**
     * Mann Whitney P
     */
    mann_whitney_p: number;
    /**
     * Mann Whitney U
     */
    mann_whitney_u: number;
    /**
     * Mean Alpha Control
     */
    mean_alpha_control: number;
    /**
     * Mean Alpha Flagged
     */
    mean_alpha_flagged: number;
    /**
     * N Excluded Injury
     */
    n_excluded_injury: number;
    /**
     * N Flagged
     */
    n_flagged: number;
    /**
     * N Matched Controls Per Flag
     */
    n_matched_controls_per_flag?: number;
    /**
     * Position Beta
     */
    position_beta: number;
};

/**
 * EvidenceListField
 */
export type EvidenceListField = {
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Items
     */
    items?: Array<string>;
};

/**
 * FoldResult
 */
export type FoldResult = {
    /**
     * Calibration By Decile
     */
    calibration_by_decile?: Array<number> | null;
    /**
     * Feature Coefficients
     */
    feature_coefficients?: {
        [key: string]: number;
    } | null;
    /**
     * Fold Index
     */
    fold_index: number;
    /**
     * Kendall Tau
     */
    kendall_tau: number;
    /**
     * Kendall Tau Bca Ci95
     */
    kendall_tau_bca_ci95: [
        number,
        number
    ];
    /**
     * Mae
     */
    mae: number;
    /**
     * Market Pool N
     */
    market_pool_n?: number | null;
    /**
     * Metric Caveats
     */
    metric_caveats?: Array<string>;
    /**
     * N Excluded Injury
     */
    n_excluded_injury?: number;
    /**
     * N Test
     */
    n_test: number;
    /**
     * N Train
     */
    n_train: number;
    /**
     * Ndcg At 12 Market
     */
    ndcg_at_12_market?: number | null;
    /**
     * Ndcg At 12 Model
     */
    ndcg_at_12_model?: number | null;
    /**
     * Ndcg At 24 Market
     */
    ndcg_at_24_market?: number | null;
    /**
     * Ndcg At 24 Model
     */
    ndcg_at_24_model?: number | null;
    /**
     * Ndcg Diff Bca Ci95
     */
    ndcg_diff_bca_ci95?: [
        number,
        number
    ] | null;
    /**
     * Ndcg Diff Primary K
     */
    ndcg_diff_primary_k?: number | null;
    /**
     * Null Coverage
     */
    null_coverage?: number | null;
    /**
     * Outcome Seasons
     */
    outcome_seasons: Array<number>;
    /**
     * Precision At K
     */
    precision_at_k?: {
        [key: string]: TopKResult;
    } | null;
    /**
     * Primary K
     */
    primary_k?: number | null;
    /**
     * R2 Oos
     */
    r2_oos?: number | null;
    /**
     * Rank Ic
     */
    rank_ic: number;
    /**
     * Regime Notes
     */
    regime_notes?: string | null;
    /**
     * Rmse
     */
    rmse: number;
    /**
     * Spearman Rho
     */
    spearman_rho: number;
    /**
     * Spearman Rho Bca Ci95
     */
    spearman_rho_bca_ci95: [
        number,
        number
    ];
    /**
     * Test Year
     */
    test_year: number;
    /**
     * Train Years
     */
    train_years: Array<number>;
};

/**
 * GateResult
 */
export type GateResult = {
    /**
     * G1 Rank Correlation Pass
     */
    g1_rank_correlation_pass: boolean;
    /**
     * G2 Rmse Stability Pass
     */
    g2_rmse_stability_pass: boolean;
    /**
     * G3 Market Superiority Pass
     */
    g3_market_superiority_pass: true | false | 'deferred';
    /**
     * G4 Divergence Validity Pass
     */
    g4_divergence_validity_pass: true | false | 'deferred' | 'insufficient_data';
    /**
     * Gate Version
     */
    gate_version?: string;
    /**
     * Model Status
     */
    model_status?: 'VALIDATED' | 'PROVISIONAL' | 'EXPERIMENTAL';
    /**
     * Null Coverage Min
     */
    null_coverage_min?: number | null;
    /**
     * Overall Grade
     */
    overall_grade: 'PRE_MODEL' | 'EXPERIMENTAL' | 'ACTIVE_B' | 'ACTIVE_B_VALIDATED' | 'DECISION_GRADE';
    /**
     * Promotion Justification
     */
    promotion_justification: string;
    status_explanation?: StatusExplanation | null;
    /**
     * Status Version
     */
    status_version?: string;
    /**
     * Validity Ci Adequacy Pass
     */
    validity_ci_adequacy_pass?: boolean;
    /**
     * Validity Cold Start Fold Index
     */
    validity_cold_start_fold_index?: number | null;
    /**
     * Validity Cold Start Tolerated
     */
    validity_cold_start_tolerated?: boolean;
    /**
     * Validity Leakage Pass
     */
    validity_leakage_pass?: boolean;
    /**
     * Validity Most Recent Fold Index
     */
    validity_most_recent_fold_index?: number | null;
    /**
     * Validity Most Recent Fold Pass
     */
    validity_most_recent_fold_pass?: boolean | null;
    /**
     * Validity Null Coverage Pass
     */
    validity_null_coverage_pass?: boolean;
    /**
     * Validity R2 Pass
     */
    validity_r2_pass?: boolean;
    /**
     * Validity Rmse Stability Pass
     */
    validity_rmse_stability_pass?: boolean;
    /**
     * Validity Spearman Pass
     */
    validity_spearman_pass?: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MarketAssetOverlay
 */
export type MarketAssetOverlay = {
    asset_ref: MarketAssetRef;
    /**
     * Caveats
     */
    caveats: Array<string>;
    /**
     * Coverage Gap
     */
    coverage_gap: string | null;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    divergence_context?: MarketDivergenceContext | null;
    /**
     * Format Key
     */
    format_key: string;
    /**
     * Label
     */
    label: string;
    /**
     * Market Value
     */
    market_value: number | null;
    /**
     * Market Volatility
     */
    market_volatility?: number | null;
    /**
     * Resolution
     */
    resolution: 'player_sleeper_id' | 'pick_exact_slot' | 'pick_generic_year_round' | 'unresolved';
    /**
     * Source
     */
    source: 'fantasycalc';
    /**
     * Source Timestamp
     */
    source_timestamp?: string | null;
    /**
     * Trend 30D
     */
    trend_30d?: number | null;
};

/**
 * MarketAssetRef
 */
export type MarketAssetRef = {
    /**
     * Asset Kind
     */
    asset_kind: 'player' | 'prospect_player' | 'future_pick';
    /**
     * Bucket
     */
    bucket?: 'early' | 'mid' | 'late' | null;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Player Id
     */
    player_id?: string | null;
    /**
     * Quantity Id
     */
    quantity_id?: string | null;
    /**
     * Round
     */
    round?: number | null;
    /**
     * Sleeper Id
     */
    sleeper_id?: string | null;
    /**
     * Slot
     */
    slot?: number | null;
    /**
     * Year
     */
    year?: number | null;
};

/**
 * MarketDivergenceContext
 */
export type MarketDivergenceContext = {
    /**
     * Caveats
     */
    caveats: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Percentile Delta
     */
    percentile_delta: number | null;
    /**
     * Sigma Threshold
     */
    sigma_threshold: number;
    /**
     * Signal Label
     */
    signal_label: 'model_higher_than_market' | 'model_lower_than_market' | 'inside_band' | 'unavailable';
    /**
     * Source Signal Status
     */
    source_signal_status: string | null;
};

/**
 * MarketRealismWarning
 */
export type MarketRealismWarning = {
    /**
     * Caveats
     */
    caveats: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Metrics
     */
    metrics: {
        [key: string]: number;
    };
    /**
     * Severity
     */
    severity: 'advisory';
    /**
     * Warning Type
     */
    warning_type: 'package_dilution_warning' | 'roster_filler_warning' | 'market_package_requires_manual_review';
};

/**
 * MarketReconcileRequest
 */
export type MarketReconcileRequest = {
    /**
     * Counterparty Roster Id
     */
    counterparty_roster_id?: number | null;
    /**
     * Current Draft Year
     */
    current_draft_year?: number;
    /**
     * Format Key
     */
    format_key?: string;
    /**
     * Received Assets
     */
    received_assets: Array<MarketAssetRef>;
    /**
     * Sent Assets
     */
    sent_assets: Array<MarketAssetRef>;
};

/**
 * MarketRosterPenalty
 */
export type MarketRosterPenalty = {
    /**
     * Caveats
     */
    caveats: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Forced Cut Candidates
     */
    forced_cut_candidates: Array<MarketAssetOverlay>;
    /**
     * Penalty Market Value
     */
    penalty_market_value: number;
    /**
     * Post Trade Overflow
     */
    post_trade_overflow: number;
    /**
     * Roster Id
     */
    roster_id: number;
    /**
     * Unresolved Cut Count
     */
    unresolved_cut_count: number;
};

/**
 * ModelCardResponse
 *
 * Curated PUBLIC model-card contract — the 8 safety/identity fields only.
 *
 * Provenance fields (model_version / model_artifact_hash / git_sha) live on the
 * audit-internal PublishedModelCardSource artifact and are deliberately NOT exposed
 * here, so the public surface never leaks the 9-section ModelCard internals.
 */
export type ModelCardResponse = {
    /**
     * Backtest Run Id
     */
    backtest_run_id: string | null;
    /**
     * Caveats
     */
    caveats: Array<string>;
    /**
     * Generated At
     */
    generated_at: string | null;
    /**
     * Intended Use
     */
    intended_use: string;
    /**
     * Is Experimental
     */
    is_experimental: boolean;
    /**
     * Known Failure Modes
     */
    known_failure_modes: Array<string>;
    /**
     * Out Of Scope Uses
     */
    out_of_scope_uses: Array<string>;
    /**
     * Position
     */
    position: string;
};

/**
 * ModelReliability
 *
 * QB-only descriptive model-reliability stamp (measured uncertainty, no verdict).
 */
export type ModelReliability = {
    /**
     * Caveat
     */
    caveat: string;
    /**
     * Position
     */
    position: string;
    /**
     * R2 Oos Mean
     */
    r2_oos_mean?: number | null;
    /**
     * Spearman Rho Mean
     */
    spearman_rho_mean?: number | null;
};

/**
 * PlayerDetailResponse
 */
export type PlayerDetailResponse = {
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: false;
    degradation: DegradationField | null;
    divergence: DivergenceField;
    evidence: PlayerEvidence | null;
    identity: PlayerIdentity;
    market: PlayerMarketLane;
    model: PlayerModelLane | null;
    /**
     * Model Status
     */
    model_status: string;
    /**
     * Sleeper Id
     */
    sleeper_id: string;
    /**
     * Source Timestamps
     */
    source_timestamps: {
        [key: string]: string | null;
    };
};

/**
 * PlayerEvidence
 */
export type PlayerEvidence = {
    caveats: EvidenceListField;
    counter_argument: CounterArgumentField;
    risk_flags: EvidenceListField;
    top_drivers: EvidenceListField;
};

/**
 * PlayerIdentity
 */
export type PlayerIdentity = {
    /**
     * Age
     */
    age: number | null;
    /**
     * Draft Class
     */
    draft_class: number | null;
    /**
     * Name
     */
    name: string | null;
    /**
     * Nfl Draft Pick
     */
    nfl_draft_pick: number | null;
    /**
     * Nfl Draft Round
     */
    nfl_draft_round: number | null;
    /**
     * Position
     */
    position: string | null;
    /**
     * Sleeper Id
     */
    sleeper_id: string;
    /**
     * Team
     */
    team: string | null;
};

/**
 * PlayerMarketLane
 */
export type PlayerMarketLane = {
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Market Rank Overall
     */
    market_rank_overall: number | null;
    /**
     * Market Rank Position
     */
    market_rank_position: number | null;
    /**
     * Market Value
     */
    market_value: number | null;
    /**
     * Source
     */
    source: string | null;
    /**
     * Source Timestamp
     */
    source_timestamp: string | null;
    /**
     * Status
     */
    status: string;
};

/**
 * PlayerModelLane
 */
export type PlayerModelLane = {
    /**
     * Dynasty Value Score
     */
    dynasty_value_score: number | null;
    /**
     * Engine Path
     */
    engine_path: string | null;
    /**
     * Model Grade
     */
    model_grade: string | null;
    /**
     * Model Version
     */
    model_version: string | null;
    /**
     * Projection 1Y
     */
    projection_1y: number | null;
    /**
     * Projection 2Y
     */
    projection_2y: number | null;
    /**
     * Projection 3Y
     */
    projection_3y: number | null;
    /**
     * Xvar
     */
    xvar: number | null;
    /**
     * Xvar Percentile Position
     */
    xvar_percentile_position: number | null;
};

/**
 * ProspectRequest
 */
export type ProspectRequest = {
    /**
     * Age
     */
    age: number;
    /**
     * Draft Class
     */
    draft_class?: number | null;
    /**
     * Final College Age
     */
    final_college_age?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Pick
     */
    pick: number;
    /**
     * Position
     */
    position: string;
    /**
     * Round
     */
    round: number;
    /**
     * Sleeper Id
     */
    sleeper_id?: string | null;
    /**
     * Te Ryptpa Final
     */
    te_ryptpa_final?: number | null;
    /**
     * Te Yards Per Reception Career
     */
    te_yards_per_reception_career?: number | null;
};

/**
 * RosterPenaltySummary
 */
export type RosterPenaltySummary = {
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Forced Cut Candidates
     */
    forced_cut_candidates: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Forced Cut Penalty Xvar
     */
    forced_cut_penalty_xvar: number;
    /**
     * Penalty Caveats
     */
    penalty_caveats: Array<string>;
    /**
     * Post Trade Overflow
     */
    post_trade_overflow: number;
    /**
     * Post Trade Total Players
     */
    post_trade_total_players: number;
};

/**
 * StabilityResult
 */
export type StabilityResult = {
    /**
     * Dm Hln Pvalue
     */
    dm_hln_pvalue?: number | null;
    /**
     * Dm Hln Statistic
     */
    dm_hln_statistic?: number | null;
    /**
     * Dm Method
     */
    dm_method?: string;
    /**
     * Dm Passes
     */
    dm_passes?: boolean | null;
    /**
     * Rmse Cv
     */
    rmse_cv: number;
    /**
     * Rmse Max Deviation Pct
     */
    rmse_max_deviation_pct: number;
    /**
     * Rmse Mean
     */
    rmse_mean: number;
    /**
     * Rmse Per Fold
     */
    rmse_per_fold: Array<number>;
};

/**
 * StatusExplanation
 *
 * Auditable record of why a model_status was assigned (Step 0.5 spec §6.5).
 *
 * Records which folds failed each validity predicate and whether the cold-start
 * fold was excused, so the status is a documented decision rather than a vibe.
 */
export type StatusExplanation = {
    /**
     * Cold Start Fold Index
     */
    cold_start_fold_index?: number | null;
    /**
     * Cold Start Tolerated
     */
    cold_start_tolerated?: boolean;
    /**
     * Failed Ci Folds
     */
    failed_ci_folds?: Array<number>;
    /**
     * Failed Rank Folds
     */
    failed_rank_folds?: Array<number>;
    /**
     * Leakage Clean
     */
    leakage_clean?: boolean | null;
    /**
     * Most Recent Fold Index
     */
    most_recent_fold_index?: number | null;
    /**
     * Most Recent Fold Pass
     */
    most_recent_fold_pass?: boolean | null;
    /**
     * Null Coverage Min
     */
    null_coverage_min?: number | null;
    /**
     * Reason
     */
    reason?: string;
};

/**
 * TopKResult
 */
export type TopKResult = {
    /**
     * Diff Wilson Ci95
     */
    diff_wilson_ci95: [
        number,
        number
    ];
    /**
     * K
     */
    k: number;
    /**
     * Market Hit Rate
     */
    market_hit_rate: number;
    /**
     * Model Hit Rate
     */
    model_hit_rate: number;
};

/**
 * TradeAsset
 */
export type TradeAsset = {
    /**
     * Caveat
     */
    caveat?: string | null;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Dvs
     */
    dvs?: number | null;
    /**
     * Dvs Engine
     */
    dvs_engine?: string | null;
    /**
     * Is Prospect
     */
    is_prospect?: boolean;
    /**
     * Player Id
     */
    player_id: string;
    /**
     * Position
     */
    position: string;
    /**
     * Xvar
     */
    xvar: number | null;
};

/**
 * TradeAssetCatalogEntry
 *
 * A single selectable asset, pre-shaped in both payload forms.
 */
export type TradeAssetCatalogEntry = {
    /**
     * Asset Id
     */
    asset_id: string;
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Kind
     */
    kind: 'player' | 'future_pick';
    /**
     * Label
     */
    label: string;
    market_ref: MarketAssetRef;
    model_payload: TradeAsset;
    /**
     * Position
     */
    position?: string | null;
    /**
     * Roster Owner Id
     */
    roster_owner_id?: number | null;
    /**
     * Roster Owner Name
     */
    roster_owner_name?: string | null;
};

/**
 * TradeAssetCatalogResponse
 *
 * The catalog envelope for a single search query.
 */
export type TradeAssetCatalogResponse = {
    /**
     * Caveats
     */
    caveats?: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Query
     */
    query: string;
    /**
     * Results
     */
    results?: Array<TradeAssetCatalogEntry>;
    /**
     * Source Timestamp
     */
    source_timestamp?: string | null;
};

/**
 * TradeEvaluateRequest
 */
export type TradeEvaluateRequest = {
    /**
     * Side A
     */
    side_a: Array<TradeAsset>;
    /**
     * Side B
     */
    side_b: Array<TradeAsset>;
};

/**
 * TradeEvaluation
 */
export type TradeEvaluation = {
    /**
     * Caveats
     */
    caveats: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Fairness Delta
     */
    fairness_delta: number;
    /**
     * Favors
     */
    favors: string | null;
    /**
     * Favors Xvar Margin
     */
    favors_xvar_margin: number | null;
    side_a: TradeSide;
    side_b: TradeSide;
    /**
     * Within Parity Band
     */
    within_parity_band: boolean;
};

/**
 * TradeMarketReconciliation
 */
export type TradeMarketReconciliation = {
    /**
     * Adjusted Market Received
     */
    adjusted_market_received: number;
    /**
     * Adjusted Market Sent
     */
    adjusted_market_sent: number;
    /**
     * Caveats
     */
    caveats: Array<string>;
    counterparty_forced_cut_penalty: MarketRosterPenalty | null;
    /**
     * Counterparty Market Penalty Status
     */
    counterparty_market_penalty_status?: 'not_requested' | 'available' | 'unavailable';
    /**
     * Coverage Gaps
     */
    coverage_gaps: Array<string>;
    david_forced_cut_penalty: MarketRosterPenalty | null;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    /**
     * Format Key
     */
    format_key: string;
    /**
     * Market Delta For David
     */
    market_delta_for_david: number;
    /**
     * Market Received Raw
     */
    market_received_raw: number;
    /**
     * Market Sent Raw
     */
    market_sent_raw: number;
    /**
     * Market Source
     */
    market_source: 'fantasycalc';
    /**
     * Realism Warnings
     */
    realism_warnings?: Array<MarketRealismWarning>;
    /**
     * Received Assets
     */
    received_assets: Array<MarketAssetOverlay>;
    /**
     * Sent Assets
     */
    sent_assets: Array<MarketAssetOverlay>;
    /**
     * Source Timestamp
     */
    source_timestamp: string | null;
};

/**
 * TradeReconcileRequest
 */
export type TradeReconcileRequest = {
    /**
     * David Assets
     */
    david_assets: Array<TradeAsset>;
    /**
     * Received Assets
     */
    received_assets: Array<TradeAsset>;
};

/**
 * TradeRequest
 */
export type TradeRequest = {
    /**
     * My Assets
     */
    my_assets: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Their Assets
     */
    their_assets: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * TradeRosterReconciliation
 */
export type TradeRosterReconciliation = {
    /**
     * Adjusted David Received Value
     */
    adjusted_david_received_value: number;
    /**
     * Adjusted Fairness Delta
     */
    adjusted_fairness_delta: number;
    /**
     * Adjusted Favors
     */
    adjusted_favors: string;
    /**
     * Adjusted Within Parity Band
     */
    adjusted_within_parity_band: boolean;
    base_evaluation: TradeEvaluation;
    /**
     * Caveats
     */
    caveats: Array<string>;
    /**
     * Decision Supported
     */
    decision_supported?: boolean;
    roster_penalty: RosterPenaltySummary;
};

/**
 * TradeSide
 */
export type TradeSide = {
    /**
     * Assets
     */
    assets: Array<TradeAsset>;
    /**
     * Consolidation Factor
     */
    consolidation_factor: number;
    /**
     * Side Value
     */
    side_value: number;
    /**
     * Xvar Sum
     */
    xvar_sum: number;
};

/**
 * TrustSurfaceResponse
 *
 * Typed Trust Surface contract: the full BacktestResult plus the hoisted,
 * consumer-facing fields. Non-breaking superset of the prior dict response, so the
 * frontend Hey API codegen has a real OpenAPI schema (no untyped object).
 */
export type TrustSurfaceResponse = {
    divergence_validity?: DivergenceResult | null;
    /**
     * Experimental
     */
    experimental: boolean;
    /**
     * Folds
     */
    folds: Array<FoldResult>;
    /**
     * Git Sha
     */
    git_sha?: string | null;
    /**
     * Market Snapshot Dates
     */
    market_snapshot_dates?: {
        [key: string]: string;
    } | null;
    /**
     * Market Source
     */
    market_source: 'fc_native' | 'dp_archive' | 'ktc_community_csv' | 'unavailable';
    /**
     * Market Source Label
     */
    market_source_label?: 'fantasycalc_native' | 'dynastyprocess_ecr_2qb' | 'ktc_community_csv' | 'unavailable';
    /**
     * Model Artifact Hash
     */
    model_artifact_hash: string;
    /**
     * Model Card Available
     */
    model_card_available: boolean;
    model_reliability?: ModelReliability | null;
    /**
     * Model Status
     */
    model_status: string;
    /**
     * Model Version
     */
    model_version: string;
    /**
     * Overall Grade
     */
    overall_grade: string;
    /**
     * Position
     */
    position: 'QB' | 'RB' | 'WR' | 'TE';
    promotion_gate: GateResult;
    /**
     * Retrain Mode
     */
    retrain_mode: 'refit_per_fold_fixed_alpha' | 'frozen_retrospective';
    /**
     * Ridge Alpha
     */
    ridge_alpha: number;
    rmse_stability: StabilityResult;
    /**
     * Run Date
     */
    run_date: string;
    /**
     * Run Id
     */
    run_id?: string;
    /**
     * Schema Version
     */
    schema_version?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetEngineBScoresApiEngineBScoresGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/engine-b/scores';
};

export type GetEngineBScoresApiEngineBScoresGetResponses = {
    /**
     * Response Get Engine B Scores Api Engine B Scores Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetEngineBScoresApiEngineBScoresGetResponse = GetEngineBScoresApiEngineBScoresGetResponses[keyof GetEngineBScoresApiEngineBScoresGetResponses];

export type GetPlayerDetailApiPlayersSleeperIdGetData = {
    body?: never;
    path: {
        /**
         * Sleeper Id
         */
        sleeper_id: string;
    };
    query?: never;
    url: '/api/players/{sleeper_id}';
};

export type GetPlayerDetailApiPlayersSleeperIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPlayerDetailApiPlayersSleeperIdGetError = GetPlayerDetailApiPlayersSleeperIdGetErrors[keyof GetPlayerDetailApiPlayersSleeperIdGetErrors];

export type GetPlayerDetailApiPlayersSleeperIdGetResponses = {
    /**
     * Successful Response
     */
    200: PlayerDetailResponse;
};

export type GetPlayerDetailApiPlayersSleeperIdGetResponse = GetPlayerDetailApiPlayersSleeperIdGetResponses[keyof GetPlayerDetailApiPlayersSleeperIdGetResponses];

export type ScoreSingleApiRookiesScorePostData = {
    body: ProspectRequest;
    path?: never;
    query?: never;
    url: '/api/rookies/score';
};

export type ScoreSingleApiRookiesScorePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScoreSingleApiRookiesScorePostError = ScoreSingleApiRookiesScorePostErrors[keyof ScoreSingleApiRookiesScorePostErrors];

export type ScoreSingleApiRookiesScorePostResponses = {
    /**
     * Response Score Single Api Rookies Score Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ScoreSingleApiRookiesScorePostResponse = ScoreSingleApiRookiesScorePostResponses[keyof ScoreSingleApiRookiesScorePostResponses];

export type ScoreClassApiRookiesScoreClassPostData = {
    /**
     * Prospects
     */
    body: Array<ProspectRequest>;
    path?: never;
    query?: never;
    url: '/api/rookies/score-class';
};

export type ScoreClassApiRookiesScoreClassPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScoreClassApiRookiesScoreClassPostError = ScoreClassApiRookiesScoreClassPostErrors[keyof ScoreClassApiRookiesScoreClassPostErrors];

export type ScoreClassApiRookiesScoreClassPostResponses = {
    /**
     * Response Score Class Api Rookies Score Class Post
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ScoreClassApiRookiesScoreClassPostResponse = ScoreClassApiRookiesScoreClassPostResponses[keyof ScoreClassApiRookiesScoreClassPostResponses];

export type AuditRosterApiRosterAuditGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/roster/audit';
};

export type AuditRosterApiRosterAuditGetResponses = {
    /**
     * Response Audit Roster Api Roster Audit Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AuditRosterApiRosterAuditGetResponse = AuditRosterApiRosterAuditGetResponses[keyof AuditRosterApiRosterAuditGetResponses];

export type AnalyzeApiTradeAnalyzePostData = {
    body: TradeRequest;
    path?: never;
    query?: never;
    url: '/api/trade/analyze';
};

export type AnalyzeApiTradeAnalyzePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyzeApiTradeAnalyzePostError = AnalyzeApiTradeAnalyzePostErrors[keyof AnalyzeApiTradeAnalyzePostErrors];

export type AnalyzeApiTradeAnalyzePostResponses = {
    /**
     * Response Analyze Api Trade Analyze Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AnalyzeApiTradeAnalyzePostResponse = AnalyzeApiTradeAnalyzePostResponses[keyof AnalyzeApiTradeAnalyzePostResponses];

export type TradeAssetsApiTradeAssetsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/trade/assets';
};

export type TradeAssetsApiTradeAssetsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TradeAssetsApiTradeAssetsGetError = TradeAssetsApiTradeAssetsGetErrors[keyof TradeAssetsApiTradeAssetsGetErrors];

export type TradeAssetsApiTradeAssetsGetResponses = {
    /**
     * Successful Response
     */
    200: TradeAssetCatalogResponse;
};

export type TradeAssetsApiTradeAssetsGetResponse = TradeAssetsApiTradeAssetsGetResponses[keyof TradeAssetsApiTradeAssetsGetResponses];

export type EvaluateTradeEndpointApiTradeEvaluatePostData = {
    body: TradeEvaluateRequest;
    path?: never;
    query?: never;
    url: '/api/trade/evaluate';
};

export type EvaluateTradeEndpointApiTradeEvaluatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EvaluateTradeEndpointApiTradeEvaluatePostError = EvaluateTradeEndpointApiTradeEvaluatePostErrors[keyof EvaluateTradeEndpointApiTradeEvaluatePostErrors];

export type EvaluateTradeEndpointApiTradeEvaluatePostResponses = {
    /**
     * Successful Response
     */
    200: TradeEvaluation;
};

export type EvaluateTradeEndpointApiTradeEvaluatePostResponse = EvaluateTradeEndpointApiTradeEvaluatePostResponses[keyof EvaluateTradeEndpointApiTradeEvaluatePostResponses];

export type ReconcileTradeEndpointApiTradeReconcilePostData = {
    body: TradeReconcileRequest;
    path?: never;
    query?: never;
    url: '/api/trade/reconcile';
};

export type ReconcileTradeEndpointApiTradeReconcilePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReconcileTradeEndpointApiTradeReconcilePostError = ReconcileTradeEndpointApiTradeReconcilePostErrors[keyof ReconcileTradeEndpointApiTradeReconcilePostErrors];

export type ReconcileTradeEndpointApiTradeReconcilePostResponses = {
    /**
     * Successful Response
     */
    200: TradeRosterReconciliation;
};

export type ReconcileTradeEndpointApiTradeReconcilePostResponse = ReconcileTradeEndpointApiTradeReconcilePostResponses[keyof ReconcileTradeEndpointApiTradeReconcilePostResponses];

export type ReconcileTradeMarketEndpointApiTradeReconcileMarketPostData = {
    body: MarketReconcileRequest;
    path?: never;
    query?: never;
    url: '/api/trade/reconcile/market';
};

export type ReconcileTradeMarketEndpointApiTradeReconcileMarketPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReconcileTradeMarketEndpointApiTradeReconcileMarketPostError = ReconcileTradeMarketEndpointApiTradeReconcileMarketPostErrors[keyof ReconcileTradeMarketEndpointApiTradeReconcileMarketPostErrors];

export type ReconcileTradeMarketEndpointApiTradeReconcileMarketPostResponses = {
    /**
     * Successful Response
     */
    200: TradeMarketReconciliation;
};

export type ReconcileTradeMarketEndpointApiTradeReconcileMarketPostResponse = ReconcileTradeMarketEndpointApiTradeReconcileMarketPostResponses[keyof ReconcileTradeMarketEndpointApiTradeReconcileMarketPostResponses];

export type GetTrustSurfaceApiTrustSurfacePositionGetData = {
    body?: never;
    path: {
        /**
         * Position
         */
        position: string;
    };
    query?: never;
    url: '/api/trust-surface/{position}';
};

export type GetTrustSurfaceApiTrustSurfacePositionGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTrustSurfaceApiTrustSurfacePositionGetError = GetTrustSurfaceApiTrustSurfacePositionGetErrors[keyof GetTrustSurfaceApiTrustSurfacePositionGetErrors];

export type GetTrustSurfaceApiTrustSurfacePositionGetResponses = {
    /**
     * Successful Response
     */
    200: TrustSurfaceResponse;
};

export type GetTrustSurfaceApiTrustSurfacePositionGetResponse = GetTrustSurfaceApiTrustSurfacePositionGetResponses[keyof GetTrustSurfaceApiTrustSurfacePositionGetResponses];

export type GetModelCardApiTrustSurfacePositionModelCardGetData = {
    body?: never;
    path: {
        /**
         * Position
         */
        position: string;
    };
    query?: never;
    url: '/api/trust-surface/{position}/model-card';
};

export type GetModelCardApiTrustSurfacePositionModelCardGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetModelCardApiTrustSurfacePositionModelCardGetError = GetModelCardApiTrustSurfacePositionModelCardGetErrors[keyof GetModelCardApiTrustSurfacePositionModelCardGetErrors];

export type GetModelCardApiTrustSurfacePositionModelCardGetResponses = {
    /**
     * Successful Response
     */
    200: ModelCardResponse;
};

export type GetModelCardApiTrustSurfacePositionModelCardGetResponse = GetModelCardApiTrustSurfacePositionModelCardGetResponses[keyof GetModelCardApiTrustSurfacePositionModelCardGetResponses];
