// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * ArtifactProvenance
 */
export const zArtifactProvenance = z.object({
    artifact_id: z.string(),
    decision_supported: z.literal(false),
    expected_kind: z.enum(['tracked_seed', 'local_operational']),
    load_verification_status: z.enum(['not_verified', 'verified']),
    observed_status: z.enum([
        'ok',
        'local_override',
        'unregistered_local',
        'hash_mismatch',
        'missing_required',
        'local_artifact_missing_ci',
        'expected_hash_missing'
    ]),
    path: z.string(),
    pointer_status: z.enum([
        'referenced',
        'pointer_missing',
        'pointer_malformed',
        'pointer_mismatch',
        'not_applicable'
    ]),
    promotion_status: z.enum([
        'active',
        'candidate',
        'parked'
    ]),
    serving_allowed: z.boolean(),
    severity: z.enum([
        'info',
        'caveat',
        'integrity'
    ])
});

/**
 * CapacityCandidate
 *
 * One roster player surfaced in the capacity-ordered review list.
 *
 * Raw value fields are re-joined from the universe PVO (the cut engine exposes
 * only percentile/dvs). Each field carries a provenance status so a consumer
 * can tell an "ok" join from an "unavailable"/"pre_model"/"unknown_position"
 * one without guessing from a null.
 */
export const zCapacityCandidate = z.object({
    candidate_source: z.enum(['forced_review', 'capacity_ordered']),
    cut_priority: z.int(),
    dvs: z.number().nullable(),
    full_name: z.string(),
    median_projection_2y: z.number().nullable(),
    position: z.string(),
    raw_xvar: z.number().nullable(),
    sleeper_player_id: z.string(),
    value_field_status: z.record(z.string(), z.string()),
    xvar_pct: z.number().nullable()
});

/**
 * CapacityHealth
 *
 * League-shape capacity summary for David's roster.
 *
 * `total_capacity_cuts_required` and `active_slot_overflow` are DISTINCT:
 * the former is roster-wide (players over total capacity, incl. reserve/taxi),
 * the latter is active-slot pressure (non-reserve, non-taxi players over the
 * active starter slots). A roster can be active-slot heavy while total-capacity
 * compliant (stash slots absorb the excess).
 */
export const zCapacityHealth = z.object({
    active_slot_overflow: z.int(),
    by_slot_class: z.record(z.string(), z.int()),
    reserve_unrestricted: z.boolean(),
    total_capacity: z.int(),
    total_capacity_cuts_required: z.int(),
    total_players: z.int()
});

/**
 * CaptureHealthErrorResponse
 */
export const zCaptureHealthErrorResponse = z.object({
    decision_supported: z.literal(false),
    error: z.string(),
    message: z.string()
});

/**
 * ComponentReadiness
 */
export const zComponentReadiness = z.object({
    basis: z.string(),
    component: z.string(),
    component_status: z.enum([
        'pass',
        'insufficient_data',
        'fail',
        'not_applicable'
    ]),
    decision_supported: z.literal(false)
});

/**
 * CounterArgumentField
 */
export const zCounterArgumentField = z.object({
    caveats: z.array(z.string()).optional().default([]),
    status: z.string(),
    text: z.string().nullable()
});

/**
 * DegradationField
 */
export const zDegradationField = z.object({
    message: z.string()
});

/**
 * DivergenceField
 */
export const zDivergenceField = z.object({
    delta: z.number().nullable(),
    status: z.string()
});

/**
 * DivergenceResult
 *
 * Gate 4. Populated only when sufficient FC snapshots and flagged player data exist.
 */
export const zDivergenceResult = z.object({
    diff_bca_ci95: z.tuple([z.number(), z.number()]),
    forward_horizon_days: z.int(),
    hit_rate: z.number(),
    hit_rate_wilson_ci95: z.tuple([z.number(), z.number()]),
    mann_whitney_method: z.string(),
    mann_whitney_p: z.number(),
    mann_whitney_u: z.number(),
    mean_alpha_control: z.number(),
    mean_alpha_flagged: z.number(),
    n_excluded_injury: z.int(),
    n_flagged: z.int(),
    n_matched_controls_per_flag: z.int().optional().default(3),
    position_beta: z.number()
});

/**
 * EvidenceListField
 */
export const zEvidenceListField = z.object({
    caveats: z.array(z.string()).optional().default([]),
    items: z.array(z.string()).optional().default([])
});

/**
 * LeaguePulseCapacityCandidate
 *
 * One descriptive roster-capacity candidate. No nomination: the surface
 * lists every candidate that could free capacity; it never selects one.
 */
export const zLeaguePulseCapacityCandidate = z.object({
    capacity_conflict_status: z.enum(['hard_roster_rules_conflict', 'roster_capacity_pressure']),
    caveats: z.array(z.string()).optional().default([]),
    decision_supported: z.literal(false).optional().default(false),
    dvs: z.number().nullish(),
    full_name: z.string(),
    position: z.string(),
    rule_conflict_label: z.string().nullish(),
    sleeper_player_id: z.string(),
    value_status: z.enum(['valued', 'unvalued']),
    xvar_pct: z.number().nullish()
});

/**
 * LeaguePulseCapacityCandidatePool
 *
 * Descriptive pool that replaces the old tool-selected single-drop field.
 * Exposes roster-capacity constraints (full candidate set, hard-rule
 * conflicts, single-candidate pressure, empty) without nominating an action.
 * ``selection_rule`` is fixed to a no-tool-selection marker (v2-only: T4c
 * dropped the transitional v1-compat migration state).
 */
export const zLeaguePulseCapacityCandidatePool = z.object({
    caveats: z.array(z.string()).optional().default([]),
    decision_supported: z.literal(false).optional().default(false),
    items: z.array(zLeaguePulseCapacityCandidate).optional().default([]),
    narrowing_rule: z.string(),
    pool_status: z.enum([
        'available',
        'constrained_single_candidate',
        'empty'
    ]),
    selection_rule: z.string(),
    sort_key: z.string()
});

/**
 * LeaguePulseCard
 *
 * Model-native opportunity card. Rejects market evidence/score keys.
 */
export const zLeaguePulseCard = z.object({
    card_id: z.string(),
    card_type: z.literal('ROSTER_SURPLUS_DEFICIT_MATCH'),
    caveats: z.array(z.string()).optional().default([]),
    decision_supported: z.literal(false).optional().default(false),
    evidence: z.record(z.string(), z.unknown()),
    evidence_status: z.enum([
        'evidence_complete',
        'evidence_gated',
        'inputs_unavailable'
    ]),
    rationale_primary: z.string(),
    rationale_secondary: z.array(z.string()).optional().default([]),
    score_components: z.record(z.string(), z.number()),
    sort_key: z.string(),
    sort_value: z.number()
});

/**
 * LeaguePulseCardSectionCount
 */
export const zLeaguePulseCardSectionCount = z.object({
    decision_supported: z.literal(false).optional().default(false),
    section_cap: z.int(),
    shown_count: z.int(),
    sort_key: z.string(),
    total_count: z.int()
});

/**
 * LeaguePulseDropCounts
 */
export const zLeaguePulseDropCounts = z.object({
    decision_supported: z.literal(false).optional().default(false),
    market_overlay_cards: z.int().optional().default(0),
    model_native_cards: z.int().optional().default(0),
    partner_rankings: z.int().optional().default(0),
    roster_capacity_candidate_pools: z.int().optional().default(0),
    team_postures: z.int().optional().default(0),
    team_values: z.int().optional().default(0)
});

/**
 * LeaguePulseMarketCard
 *
 * Labeled market-overlay card (Q3=B). Admits market evidence/score keys.
 */
export const zLeaguePulseMarketCard = z.object({
    card_id: z.string(),
    card_type: z.enum([
        'UNROSTERED_MODEL_MARKET_DIVERGENCE',
        'DIVERGENCE_MODEL_HIGH',
        'DIVERGENCE_MARKET_HIGH',
        'TAXI_LONG_TERM_VALUE_PRESENT'
    ]),
    caveats: z.array(z.string()).optional().default([]),
    decision_supported: z.literal(false).optional().default(false),
    evidence: z.record(z.string(), z.unknown()),
    evidence_status: z.enum([
        'evidence_complete',
        'evidence_gated',
        'inputs_unavailable'
    ]),
    rationale_primary: z.string(),
    rationale_secondary: z.array(z.string()).optional().default([]),
    roster_capacity_candidates: zLeaguePulseCapacityCandidatePool.nullish(),
    score_components: z.record(z.string(), z.number()),
    sort_key: z.string(),
    sort_value: z.number()
});

/**
 * LeaguePulsePartnerRanking
 */
export const zLeaguePulsePartnerRanking = z.object({
    caveats: z.array(z.string()).optional().default([]),
    counterparty_roster_id: z.int(),
    counterparty_team_name: z.string().nullable(),
    decision_supported: z.literal(false).optional().default(false),
    evidence: z.record(z.string(), z.unknown()),
    market_influenced: z.literal(true).optional().default(true),
    matched_positions: z.array(z.string()),
    partner_score: z.number(),
    score_components: z.record(z.string(), z.number())
});

/**
 * LeaguePulseSources
 */
export const zLeaguePulseSources = z.object({
    decision_supported: z.literal(false).optional().default(false),
    league_opportunity: z.record(z.string(), z.unknown()),
    team_posture: z.record(z.string(), z.unknown()),
    team_value_matrix: z.record(z.string(), z.unknown())
});

/**
 * LeaguePulseTeamPosture
 */
export const zLeaguePulseTeamPosture = z.object({
    caveats: z.array(z.string()).optional().default([]),
    components: z.record(z.string(), z.number()),
    decision_supported: z.literal(false).optional().default(false),
    posture_label: z.enum([
        'CONTENDER',
        'REBUILDING',
        'ASCENDING',
        'BALANCED',
        'TRANSITIONAL'
    ]),
    roster_id: z.int(),
    score: z.number(),
    team_name: z.string().nullable()
});

/**
 * LeaguePulseValueViews
 */
export const zLeaguePulseValueViews = z.object({
    decision_supported: z.literal(false).optional().default(false),
    depth_credit_xvar: z.number(),
    lineup_xvar: z.number(),
    starter_weighted_xvar: z.number(),
    top_n_xvar: z.number(),
    total_xvar_capped: z.number()
});

/**
 * LeaguePulseTeamValue
 */
export const zLeaguePulseTeamValue = z.object({
    age_profile: z.record(z.string(), z.number()),
    decision_supported: z.literal(false).optional().default(false),
    future_picks: z.record(z.string(), z.unknown()),
    positional_summary: z.record(z.string(), z.unknown()),
    roster_id: z.int(),
    team_name: z.string().nullable(),
    value_views: zLeaguePulseValueViews
});

/**
 * LeaguePulseResponse
 */
export const zLeaguePulseResponse = z.object({
    captured_at: z.string(),
    card_section_counts: z.array(zLeaguePulseCardSectionCount),
    caveats: z.array(z.string()).optional().default([]),
    decision_supported: z.literal(false).optional().default(false),
    dropped: zLeaguePulseDropCounts,
    market_overlay_cards: z.array(zLeaguePulseMarketCard).optional().default([]),
    model_native_cards: z.array(zLeaguePulseCard).optional().default([]),
    partner_rankings: z.array(zLeaguePulsePartnerRanking).optional().default([]),
    perspective_roster_id: z.int(),
    source_artifacts: zLeaguePulseSources,
    status: z.enum(['active', 'degraded']),
    team_postures: z.array(zLeaguePulseTeamPosture).optional().default([]),
    team_values: z.array(zLeaguePulseTeamValue).optional().default([])
});

/**
 * MarketAssetRef
 */
export const zMarketAssetRef = z.object({
    asset_kind: z.enum([
        'player',
        'prospect_player',
        'future_pick'
    ]),
    bucket: z.enum([
        'early',
        'mid',
        'late'
    ]).nullish(),
    decision_supported: z.boolean().optional().default(false),
    player_id: z.string().nullish(),
    quantity_id: z.string().nullish(),
    round: z.int().nullish(),
    sleeper_id: z.string().nullish(),
    slot: z.int().nullish(),
    year: z.int().nullish()
});

/**
 * MarketDivergenceContext
 */
export const zMarketDivergenceContext = z.object({
    caveats: z.array(z.string()),
    decision_supported: z.boolean().optional().default(false),
    percentile_delta: z.number().nullable(),
    sigma_threshold: z.number(),
    signal_label: z.enum([
        'model_higher_than_market',
        'model_lower_than_market',
        'inside_band',
        'unavailable'
    ]),
    source_signal_status: z.string().nullable()
});

/**
 * MarketAssetOverlay
 */
export const zMarketAssetOverlay = z.object({
    asset_ref: zMarketAssetRef,
    caveats: z.array(z.string()),
    coverage_gap: z.string().nullable(),
    decision_supported: z.boolean().optional().default(false),
    divergence_context: zMarketDivergenceContext.nullish(),
    format_key: z.string(),
    label: z.string(),
    market_value: z.int().nullable(),
    market_volatility: z.number().nullish(),
    resolution: z.enum([
        'player_sleeper_id',
        'pick_exact_slot',
        'pick_generic_year_round',
        'unresolved'
    ]),
    source: z.literal('fantasycalc'),
    source_timestamp: z.string().nullish(),
    trend_30d: z.int().nullish()
});

/**
 * MarketRealismWarning
 */
export const zMarketRealismWarning = z.object({
    caveats: z.array(z.string()),
    decision_supported: z.boolean().optional().default(false),
    message: z.string(),
    metrics: z.record(z.string(), z.number()),
    severity: z.literal('advisory'),
    warning_type: z.enum([
        'package_dilution_warning',
        'roster_filler_warning',
        'market_package_requires_manual_review'
    ])
});

/**
 * MarketReconcileRequest
 */
export const zMarketReconcileRequest = z.object({
    counterparty_roster_id: z.int().nullish(),
    current_draft_year: z.int().optional().default(2026),
    format_key: z.string().optional().default('dynasty_sf_ppr'),
    received_assets: z.array(zMarketAssetRef),
    sent_assets: z.array(zMarketAssetRef)
});

/**
 * MarketRosterPenalty
 */
export const zMarketRosterPenalty = z.object({
    caveats: z.array(z.string()),
    decision_supported: z.boolean().optional().default(false),
    forced_cut_candidates: z.array(zMarketAssetOverlay),
    forced_cut_market_recovery_range: z.tuple([z.number(), z.number()]).nullish(),
    forced_cut_market_value_at_risk_range: z.tuple([z.number(), z.number()]).nullish(),
    market_penalty_status: z.enum([
        'ok',
        'uncertain_pool_unavailable',
        'blocked'
    ]).optional().default('ok'),
    penalty_market_value: z.int(),
    post_trade_overflow: z.int(),
    roster_id: z.int(),
    unresolved_cut_count: z.int()
});

/**
 * MifField
 *
 * Model Input Fidelity for one utilization field — a diagnostic audit of a
 * model INPUT (does realized usage match the model's assumption), NOT a player
 * verdict. ``delta`` is only populated when ``status == "ok"``.
 */
export const zMifField = z.object({
    delta: z.number().nullish(),
    status: z.string()
});

/**
 * MissingRange
 *
 * One contiguous missing-date range; display list is capped, totals never.
 */
export const zMissingRange = z.object({
    days: z.int(),
    from: z.string(),
    to: z.string()
});

/**
 * ModelCardResponse
 *
 * Curated PUBLIC model-card contract — the 8 safety/identity fields only.
 *
 * Provenance fields (model_version / model_artifact_hash / git_sha) live on the
 * audit-internal PublishedModelCardSource artifact and are deliberately NOT exposed
 * here, so the public surface never leaks the 9-section ModelCard internals.
 */
export const zModelCardResponse = z.object({
    backtest_run_id: z.string().nullable(),
    caveats: z.array(z.string()),
    generated_at: z.string().nullable(),
    intended_use: z.string(),
    is_experimental: z.boolean(),
    known_failure_modes: z.array(z.string()),
    out_of_scope_uses: z.array(z.string()),
    position: z.string()
});

/**
 * ModelProvenanceErrorResponse
 */
export const zModelProvenanceErrorResponse = z.object({
    decision_supported: z.literal(false),
    error: z.string(),
    message: z.string()
});

/**
 * ModelProvenanceResponse
 */
export const zModelProvenanceResponse = z.object({
    artifacts: z.array(zArtifactProvenance),
    decision_supported: z.literal(false),
    environment: z.enum([
        'development',
        'ci',
        'serving',
        'production'
    ]),
    overall_status: z.enum([
        'ok',
        'degraded',
        'blocked'
    ]),
    registry_version: z.int()
});

/**
 * ModelReliability
 *
 * QB-only descriptive model-reliability stamp (measured uncertainty, no verdict).
 */
export const zModelReliability = z.object({
    caveat: z.string(),
    position: z.string(),
    r2_oos_mean: z.number().nullish(),
    spearman_rho_mean: z.number().nullish()
});

/**
 * NdcgStat
 */
export const zNdcgStat = z.object({
    value: z.number().nullish()
});

/**
 * PlayerEvidence
 */
export const zPlayerEvidence = z.object({
    caveats: zEvidenceListField,
    counter_argument: zCounterArgumentField,
    risk_flags: zEvidenceListField,
    top_drivers: zEvidenceListField
});

/**
 * PlayerIdentity
 */
export const zPlayerIdentity = z.object({
    age: z.number().nullable(),
    draft_class: z.int().nullable(),
    name: z.string().nullable(),
    nfl_draft_pick: z.int().nullable(),
    nfl_draft_round: z.int().nullable(),
    position: z.string().nullable(),
    sleeper_id: z.string(),
    team: z.string().nullable()
});

/**
 * PlayerMarketLane
 */
export const zPlayerMarketLane = z.object({
    caveats: z.array(z.string()).optional().default([]),
    market_rank_overall: z.int().nullable(),
    market_rank_position: z.int().nullable(),
    market_value: z.number().nullable(),
    source: z.string().nullable(),
    source_timestamp: z.string().nullable(),
    status: z.string()
});

/**
 * PlayerModelLane
 */
export const zPlayerModelLane = z.object({
    dynasty_value_score: z.number().nullable(),
    engine_path: z.string().nullable(),
    model_grade: z.string().nullable(),
    model_version: z.string().nullable(),
    projection_1y: z.number().nullable(),
    projection_2y: z.number().nullable(),
    projection_3y: z.number().nullable(),
    xvar: z.number().nullable(),
    xvar_percentile_position: z.number().nullable()
});

/**
 * PlayerDetailResponse
 */
export const zPlayerDetailResponse = z.object({
    caveats: z.array(z.string()).optional().default([]),
    decision_supported: z.literal(false).optional().default(false),
    degradation: zDegradationField.nullable(),
    divergence: zDivergenceField,
    evidence: zPlayerEvidence.nullable(),
    identity: zPlayerIdentity,
    market: zPlayerMarketLane,
    model: zPlayerModelLane.nullable(),
    model_status: z.string(),
    sleeper_id: z.string(),
    source_timestamps: z.record(z.string(), z.string().nullable())
});

/**
 * PoolRange
 *
 * The unrostered (waiver) replacement range for one position.
 *
 * Deliberately WIDE, not a confidence interval: `low`/`high` are the min/max of
 * the position's display top-K unrostered values — an honest band over a
 * volatile wire, never a tightened point estimate. `top_k_values` carries the
 * ordered (descending) raw values themselves, retained out to the largest
 * requested scenario so T3's depletion math has every per-member value it
 * needs (it may be LONGER than the K that low/high are computed over).
 *
 * `status == "waiver_range_unavailable"` fails closed (stale snapshot,
 * incomplete roster coverage, pool below `min_pool`, valuation coverage below
 * floor); a genuinely barren-but-valid pool stays `ok` with a loud caveat.
 */
export const zPoolRange = z.object({
    caveats: z.array(z.string()).optional(),
    high: z.number().nullable(),
    low: z.number().nullable(),
    pool_size: z.int().nullable(),
    status: z.enum(['ok', 'waiver_range_unavailable']),
    top_k_values: z.array(z.number()).optional()
});

/**
 * PrecisionAtK
 */
export const zPrecisionAtK = z.object({
    hits: z.int().nullish(),
    k: z.int().nullish(),
    truth_def: z.string().nullish(),
    value: z.number().nullish()
});

/**
 * ProspectRequest
 */
export const zProspectRequest = z.object({
    age: z.number(),
    draft_class: z.int().nullish(),
    final_college_age: z.number().nullish(),
    name: z.string(),
    pick: z.int(),
    position: z.string(),
    round: z.int(),
    sleeper_id: z.string().nullish(),
    te_ryptpa_final: z.number().nullish(),
    te_yards_per_reception_career: z.number().nullish()
});

/**
 * QBContextCard
 *
 * F2: explicitly typed; extra fields forbidden (no provenance/market backdoor).
 */
export const zQbContextCard = z.object({
    context_role: z.literal('context_signal').optional().default('context_signal'),
    cpoe: z.number().nullish(),
    dakota: z.number().nullish(),
    decision_supported: z.literal(false).optional().default(false),
    dropback_count: z.number().nullish(),
    epa_per_dropback: z.number().nullish(),
    full_name: z.string(),
    identity_coverage: z.enum([
        'FULL',
        'PARTIAL',
        'NONE'
    ]),
    pass_attempts: z.number().nullish(),
    player_id: z.string(),
    qb_context_annotations: z.array(z.string()).optional(),
    qb_context_caveats: z.array(z.string()).optional(),
    source_qb_context_annotations: z.string()
});

/**
 * RankStat
 *
 * A rank-correlation statistic with its BCa confidence interval (both nullable
 * until a cohort clears the statistical power floor).
 */
export const zRankStat = z.object({
    bca_ci: z.array(z.number()).nullish(),
    value: z.number().nullish()
});

/**
 * CohortMetric
 *
 * Within-position rank-accuracy metrics for one position cohort. ``status`` is
 * ``power_floor_not_met`` (correlations suppressed) or ``ok``.
 */
export const zCohortMetric = z.object({
    decision_supported: z.literal(false),
    eligible_count: z.int().nullish(),
    kendall: zRankStat,
    ndcg: zNdcgStat,
    precision_at_k: zPrecisionAtK,
    spearman: zRankStat,
    status: z.string()
});

/**
 * RealizedOutcomeScorecardErrorResponse
 *
 * Structured 503 body: the scorecard artifact is present but could not be
 * served (malformed, wrong-root, wrong-schema, non-finite, or verdict-shaped).
 *
 * Absent artifact is NOT an error — it is the healthy off-season ``inactive`` 200.
 */
export const zRealizedOutcomeScorecardErrorResponse = z.object({
    decision_supported: z.literal(false).optional().default(false),
    error: z.string(),
    message: z.string()
});

/**
 * ReportHealth
 */
export const zReportHealth = z.object({
    age_seconds: z.int().nullable(),
    artifact_id: z.string(),
    artifact_path: z.string(),
    basis: z.string(),
    decision_supported: z.literal(false),
    disclosures: z.array(z.string()),
    observed_at: z.string().nullable(),
    producer: z.string(),
    status: z.enum([
        'fresh',
        'freshness_overdue',
        'stale',
        'corrupt_or_empty',
        'dormant',
        'missing'
    ]),
    tier: z.enum([
        'core_substrate',
        'daily_diagnostics',
        'auxiliary'
    ])
});

/**
 * RosterAuditSignalsView
 *
 * F3: curated signals view; nested decision_supported can never leak true.
 */
export const zRosterAuditSignalsView = z.object({
    age_cliff_risk: z.number().nullish(),
    age_value_context: z.string().nullish(),
    biological_debt_score: z.number().nullish(),
    caveats: z.array(z.string()).optional(),
    cliff_age: z.int().nullish(),
    decision_supported: z.literal(false).optional().default(false),
    liquidity_risk: z.string().nullish(),
    signal: z.string().nullish(),
    signal_drivers: z.array(z.string()).optional(),
    years_to_cliff: z.int().nullish()
});

/**
 * RosterAuditPlayer
 */
export const zRosterAuditPlayer = z.object({
    age: z.number().nullish(),
    caveats: z.array(z.string()).optional(),
    counter_argument: zCounterArgumentField,
    decision_supported: z.literal(false).optional().default(false),
    draft_class: z.int().nullish(),
    dvs_engine: z.enum([
        'A',
        'B',
        'blend'
    ]).nullish(),
    dvs_pct: z.number().nullish(),
    dynasty_value_score: z.number().nullish(),
    engine_used: z.string().nullish(),
    full_name: z.string(),
    inputs_missing: z.array(z.string()).optional(),
    inputs_present: z.array(z.string()).optional(),
    is_prospect: z.boolean().optional().default(false),
    model_grade: z.string(),
    model_status_applies: z.boolean().optional().default(false),
    model_version: z.string().nullish(),
    nfl_draft_pick: z.int().nullish(),
    nfl_draft_round: z.int().nullish(),
    nfl_team: z.string().nullish(),
    player_id: z.string(),
    position: z.string(),
    projection_1y: z.number().nullish(),
    projection_2y: z.number().nullish(),
    projection_3y: z.number().nullish(),
    risk_flags: zEvidenceListField,
    roster_audit: zRosterAuditSignalsView.nullish(),
    signal_completeness: z.number().optional().default(0),
    sleeper_id: z.string().nullish(),
    top_drivers: zEvidenceListField,
    xvar: z.number().nullish()
});

/**
 * RosterAuditResponse
 */
export const zRosterAuditResponse = z.object({
    caveats: z.array(z.string()).optional(),
    decision_supported: z.literal(false).optional().default(false),
    dropped_player_count: z.int().optional().default(0),
    engine: z.string(),
    model_status_by_position: z.record(z.string(), z.enum([
        'VALIDATED',
        'PROVISIONAL',
        'EXPERIMENTAL'
    ])),
    players: z.array(zRosterAuditPlayer).optional(),
    qb_context_cards: z.array(zQbContextCard).optional(),
    reason: z.string(),
    status: z.enum(['active', 'degraded'])
});

/**
 * RosterCapacityErrorResponse
 *
 * Structured 503 body: the artifact could not be served.
 *
 * Even the failure is descriptive — `decision_supported` stays False so a
 * consumer never reads an error as a directive.
 */
export const zRosterCapacityErrorResponse = z.object({
    decision_supported: z.literal(false).optional().default(false),
    error: z.string(),
    message: z.string()
});

/**
 * RosterPenaltySummary
 */
export const zRosterPenaltySummary = z.object({
    decision_supported: z.boolean().optional().default(false),
    forced_cut_candidates: z.array(z.record(z.string(), z.unknown())),
    forced_cut_penalty_xvar: z.number(),
    forced_cut_recovery_range: z.tuple([z.number(), z.number()]).nullish(),
    forced_cut_value_at_risk_range: z.tuple([z.number(), z.number()]).nullish(),
    penalty_caveats: z.array(z.string()),
    penalty_status: z.enum([
        'ok',
        'uncertain_pool_unavailable',
        'blocked'
    ]).optional().default('ok'),
    pool_deficits: z.record(z.string(), z.int()).optional().default({}),
    post_trade_overflow: z.int(),
    post_trade_total_players: z.int()
});

/**
 * ScenarioResult
 *
 * The descriptive consequences of one cut hypothesis — no verdict.
 *
 * `cumulative_value_at_risk` is depletion-aware (NOT N x a single-player gap):
 * the wire depletes as you claim players, so the bound is summed per position
 * from N-deep pool slices. Orientation is pinned `(best_case, worst_case)` and
 * cannot invert; negatives are left UNCLAMPED (a cut that is a net upgrade
 * reads negative). `pool_deficits` records, per position, how many cut spots
 * have NO replacement candidate — a fact, never a do-not-cut verdict.
 * `marginal_next_candidate_cost` is the value-at-risk RANGE of the next
 * capacity-ordered candidate not in the cut set; it carries NO player
 * identifier (it nominates no target).
 */
export const zScenarioResult = z.object({
    caveats: z.array(z.string()).optional(),
    cumulative_value_at_risk: z.tuple([z.number(), z.number()]),
    cut_set: z.array(z.string()).optional(),
    marginal_next_candidate_cost: z.tuple([z.number(), z.number()]).nullable(),
    per_position_depth_impact: z.record(z.string(), z.record(z.string(), z.int())).optional(),
    pool_deficits: z.record(z.string(), z.int()).optional()
});

/**
 * RosterCapacityResponse
 *
 * Read-only serve of the enriched capacity scorecard artifact.
 *
 * `artifact_status` is the route's own read of the served state
 * (`ok` / `degraded` / `blocked`), DISTINCT from the core `status`. No field
 * averages, tightens, or nominates: ranges pass through unclamped and signed,
 * and `marginal_next_candidate_cost` stays a range with no player identifier.
 */
export const zRosterCapacityResponse = z.object({
    artifact_status: z.enum([
        'ok',
        'degraded',
        'blocked'
    ]),
    candidates: z.array(zCapacityCandidate).optional(),
    capacity_health: zCapacityHealth.nullable(),
    caveats: z.array(z.string()).optional(),
    created_at: z.string().nullable(),
    decision_supported: z.literal(false).optional().default(false),
    excluded_counts: z.record(z.string(), z.int()).optional(),
    scenarios: z.array(zScenarioResult).optional(),
    sleeper_snapshot_captured_at: z.string().nullable(),
    status: z.enum(['ok', 'blocked']),
    unrostered_pool_range: z.record(z.string(), zPoolRange).optional()
});

/**
 * StabilityResult
 */
export const zStabilityResult = z.object({
    dm_hln_pvalue: z.number().nullish(),
    dm_hln_statistic: z.number().nullish(),
    dm_method: z.string().optional().default('harvey_leybourne_newbold_1997'),
    dm_passes: z.boolean().nullish(),
    rmse_cv: z.number(),
    rmse_max_deviation_pct: z.number(),
    rmse_mean: z.number(),
    rmse_per_fold: z.array(z.number())
});

/**
 * StatusExplanation
 *
 * Auditable record of why a model_status was assigned (Step 0.5 spec §6.5).
 *
 * Records which folds failed each validity predicate and whether the cold-start
 * fold was excused, so the status is a documented decision rather than a vibe.
 */
export const zStatusExplanation = z.object({
    cold_start_fold_index: z.int().nullish(),
    cold_start_tolerated: z.boolean().optional().default(false),
    failed_ci_folds: z.array(z.int()).optional(),
    failed_rank_folds: z.array(z.int()).optional(),
    leakage_clean: z.boolean().nullish(),
    most_recent_fold_index: z.int().nullish(),
    most_recent_fold_pass: z.boolean().nullish(),
    null_coverage_min: z.number().nullish(),
    reason: z.string().optional().default('')
});

/**
 * GateResult
 */
export const zGateResult = z.object({
    g1_rank_correlation_pass: z.boolean(),
    g2_rmse_stability_pass: z.boolean(),
    g3_market_superiority_pass: z.union([
        z.literal(true),
        z.literal(false),
        z.literal('deferred')
    ]),
    g4_divergence_validity_pass: z.union([
        z.literal(true),
        z.literal(false),
        z.literal('deferred'),
        z.literal('insufficient_data')
    ]),
    gate_version: z.string().optional().default('1.0'),
    model_status: z.enum([
        'VALIDATED',
        'PROVISIONAL',
        'EXPERIMENTAL'
    ]).optional().default('EXPERIMENTAL'),
    null_coverage_min: z.number().nullish(),
    overall_grade: z.enum([
        'PRE_MODEL',
        'EXPERIMENTAL',
        'ACTIVE_B',
        'ACTIVE_B_VALIDATED',
        'DECISION_GRADE'
    ]),
    promotion_justification: z.string(),
    status_explanation: zStatusExplanation.nullish(),
    status_version: z.string().optional().default('0.5.0'),
    validity_ci_adequacy_pass: z.boolean().optional().default(false),
    validity_cold_start_fold_index: z.int().nullish(),
    validity_cold_start_tolerated: z.boolean().optional().default(false),
    validity_leakage_pass: z.boolean().optional().default(false),
    validity_most_recent_fold_index: z.int().nullish(),
    validity_most_recent_fold_pass: z.boolean().nullish(),
    validity_null_coverage_pass: z.boolean().optional().default(false),
    validity_r2_pass: z.boolean().optional().default(false),
    validity_rmse_stability_pass: z.boolean().optional().default(false),
    validity_spearman_pass: z.boolean().optional().default(false)
});

/**
 * StoreDensity
 */
export const zStoreDensity = z.object({
    baseline_median_rows: z.int().nullable(),
    baseline_window: z.int(),
    floor_pct: z.int(),
    sub_floor_dates: z.array(z.string())
});

/**
 * StoreFlags
 */
export const zStoreFlags = z.object({
    warn_basis: z.string(),
    warn_missing: z.boolean(),
    window_risk: z.boolean(),
    window_risk_basis: z.string()
});

/**
 * StoreStaleness
 */
export const zStoreStaleness = z.object({
    expected_by: z.string(),
    grace_hours: z.int(),
    last_capture_date: z.string().nullable(),
    stale: z.boolean()
});

/**
 * StoreTimeline
 */
export const zStoreTimeline = z.object({
    capture_start_date: z.string(),
    consecutive_days_current: z.int(),
    expected_days: z.int(),
    first_date: z.string().nullable(),
    last_date: z.string().nullable(),
    max_contiguous_gap_days: z.int(),
    missing_dates_count: z.int(),
    missing_ranges: z.array(zMissingRange),
    missing_ranges_total: z.int(),
    present_days: z.int()
});

/**
 * StoreHealth
 */
export const zStoreHealth = z.object({
    caveats: z.array(z.string()),
    decision_supported: z.literal(false),
    density: zStoreDensity,
    flags: zStoreFlags,
    staleness: zStoreStaleness,
    store_id: z.string(),
    store_presence: z.enum(['present', 'absent']),
    store_status: z.enum(['ok', 'degraded']),
    timeline: zStoreTimeline
});

/**
 * CaptureHealthResponse
 */
export const zCaptureHealthResponse = z.object({
    checked_at: z.string(),
    config_version: z.int(),
    decision_supported: z.literal(false),
    overall_status: z.enum(['ok', 'degraded']),
    stores: z.array(zStoreHealth)
});

/**
 * SubsystemHealth
 */
export const zSubsystemHealth = z.object({
    basis: z.string(),
    decision_supported: z.literal(false),
    status: z.enum([
        'ok',
        'degraded',
        'unavailable'
    ]),
    subsystem_id: z.string(),
    tier: z.enum([
        'core_substrate',
        'daily_diagnostics',
        'auxiliary'
    ])
});

/**
 * SurfaceReadiness
 *
 * Runtime readiness for one surface. Root-level dormancy disclosure is
 * mandatory (R2): the headline `_limited` status plus machine-readable
 * counts, so a UI can never render an unqualified badge over dormant
 * components.
 */
export const zSurfaceReadiness = z.object({
    all_components_evaluable: z.boolean(),
    basis: z.string().min(1),
    components: z.array(zComponentReadiness),
    decision_supported: z.literal(false),
    display_name: z.string(),
    insufficient_data_components: z.array(z.string()),
    insufficient_data_count: z.int(),
    live_preconditions: z.record(z.string(), z.string()),
    surface_id: z.string(),
    tier_status: z.enum([
        'diagnostic_grade_active',
        'diagnostic_grade_active_limited',
        'preconditions_degraded',
        'not_graduated'
    ])
});

/**
 * SystemHealthErrorResponse
 */
export const zSystemHealthErrorResponse = z.object({
    decision_supported: z.literal(false),
    error: z.string(),
    message: z.string()
});

/**
 * SystemHealthResponse
 */
export const zSystemHealthResponse = z.object({
    checked_at: z.string(),
    config_version: z.int(),
    decision_supported: z.literal(false),
    disclaimer: z.literal('System health reflects pipeline completion, artifact freshness, and model provenance verification. It does not evaluate model accuracy or guarantee trade edge.'),
    overall_status: z.enum(['ok', 'degraded']),
    reports: z.array(zReportHealth),
    subsystems: z.array(zSubsystemHealth),
    worst_affected_tier: z.enum([
        'core_substrate',
        'daily_diagnostics',
        'auxiliary'
    ]).nullable()
});

/**
 * TierReadinessErrorResponse
 */
export const zTierReadinessErrorResponse = z.object({
    decision_supported: z.literal(false),
    error: z.string(),
    message: z.string()
});

/**
 * TierReadinessResponse
 */
export const zTierReadinessResponse = z.object({
    decision_supported: z.literal(false),
    overall_status: z.enum(['ok', 'degraded']),
    registry_version: z.int(),
    surfaces: z.array(zSurfaceReadiness)
});

/**
 * TopKResult
 */
export const zTopKResult = z.object({
    diff_wilson_ci95: z.tuple([z.number(), z.number()]),
    k: z.int(),
    market_hit_rate: z.number(),
    model_hit_rate: z.number()
});

/**
 * FoldResult
 */
export const zFoldResult = z.object({
    calibration_by_decile: z.array(z.number()).nullish(),
    feature_coefficients: z.record(z.string(), z.number()).nullish(),
    fold_index: z.int(),
    kendall_tau: z.number(),
    kendall_tau_bca_ci95: z.tuple([z.number(), z.number()]),
    mae: z.number(),
    market_pool_n: z.int().nullish(),
    metric_caveats: z.array(z.string()).optional(),
    n_excluded_injury: z.int().optional().default(0),
    n_test: z.int(),
    n_train: z.int(),
    ndcg_at_12_market: z.number().nullish(),
    ndcg_at_12_model: z.number().nullish(),
    ndcg_at_24_market: z.number().nullish(),
    ndcg_at_24_model: z.number().nullish(),
    ndcg_diff_bca_ci95: z.tuple([z.number(), z.number()]).nullish(),
    ndcg_diff_primary_k: z.number().nullish(),
    null_coverage: z.number().nullish(),
    outcome_seasons: z.array(z.int()),
    precision_at_k: z.record(z.string(), zTopKResult).nullish(),
    primary_k: z.int().nullish(),
    r2_oos: z.number().nullish(),
    rank_ic: z.number(),
    regime_notes: z.string().nullish(),
    rmse: z.number(),
    spearman_rho: z.number(),
    spearman_rho_bca_ci95: z.tuple([z.number(), z.number()]),
    test_year: z.int(),
    train_years: z.array(z.int())
});

/**
 * TrackingRow
 *
 * One player's predicted vs realized PPG plus its input-fidelity audit.
 */
export const zTrackingRow = z.object({
    decision_supported: z.literal(false),
    gsis_id: z.string(),
    maturity_pct: z.number().nullish(),
    model_input_fidelity: z.record(z.string(), zMifField).optional(),
    position: z.string().nullish(),
    predicted_ppg: z.number().nullish(),
    realized_outcome_status: z.string(),
    realized_ppg_to_date: z.number().nullish(),
    realized_vs_expected_delta: z.number().nullish(),
    settlement_status: z.string()
});

/**
 * RealizedOutcomeScorecardResponse
 *
 * Read-only serve of the latest realized-outcome scorecard.
 *
 * ``status`` is ``inactive`` (no artifact yet — the healthy off-season state) or
 * ``ok`` (a produced scorecard). ``settlement_status`` is ``unsettled`` until the
 * 2-year horizon. Leads with within-position rank accuracy + Model Input Fidelity;
 * market data is excluded from scoring.
 */
export const zRealizedOutcomeScorecardResponse = z.object({
    as_of_week: z.int().nullish(),
    cohort_metrics: z.record(z.string(), zCohortMetric).optional(),
    decision_supported: z.literal(false),
    excluded_counts: z.record(z.string(), z.int()).optional(),
    maturity_pct: z.number().nullish(),
    settlement_status: z.string(),
    status: z.string(),
    status_reason: z.string().nullish(),
    tracking_rows: z.array(zTrackingRow).optional()
});

/**
 * TradeAsset
 */
export const zTradeAsset = z.object({
    caveat: z.string().nullish(),
    decision_supported: z.boolean().optional().default(false),
    dvs: z.number().nullish(),
    dvs_engine: z.string().nullish(),
    is_prospect: z.boolean().optional().default(false),
    player_id: z.string(),
    position: z.string(),
    xvar: z.number().nullable()
});

/**
 * TradeAssetCatalogEntry
 *
 * A single selectable asset, pre-shaped in both payload forms.
 */
export const zTradeAssetCatalogEntry = z.object({
    asset_id: z.string(),
    caveats: z.array(z.string()).optional().default([]),
    decision_supported: z.boolean().optional().default(false),
    kind: z.enum(['player', 'future_pick']),
    label: z.string(),
    market_ref: zMarketAssetRef,
    model_payload: zTradeAsset,
    position: z.string().nullish(),
    roster_owner_id: z.int().nullish(),
    roster_owner_name: z.string().nullish()
});

/**
 * TradeAssetCatalogResponse
 *
 * The catalog envelope for a single search query.
 */
export const zTradeAssetCatalogResponse = z.object({
    caveats: z.array(z.string()).optional().default([]),
    decision_supported: z.boolean().optional().default(false),
    query: z.string(),
    results: z.array(zTradeAssetCatalogEntry).optional().default([]),
    source_timestamp: z.string().nullish()
});

/**
 * TradeEvaluateRequest
 */
export const zTradeEvaluateRequest = z.object({
    side_a: z.array(zTradeAsset),
    side_b: z.array(zTradeAsset)
});

/**
 * TradeMarketReconciliation
 */
export const zTradeMarketReconciliation = z.object({
    adjusted_market_received: z.int(),
    adjusted_market_sent: z.int(),
    caveats: z.array(z.string()),
    counterparty_forced_cut_penalty: zMarketRosterPenalty.nullable(),
    counterparty_market_penalty_status: z.enum([
        'not_requested',
        'available',
        'unavailable'
    ]).optional().default('not_requested'),
    coverage_gaps: z.array(z.string()),
    david_forced_cut_penalty: zMarketRosterPenalty.nullable(),
    decision_supported: z.boolean().optional().default(false),
    format_key: z.string(),
    market_delta_for_david: z.int(),
    market_received_raw: z.int(),
    market_sent_raw: z.int(),
    market_source: z.literal('fantasycalc'),
    realism_warnings: z.array(zMarketRealismWarning).optional().default([]),
    received_assets: z.array(zMarketAssetOverlay),
    sent_assets: z.array(zMarketAssetOverlay),
    source_timestamp: z.string().nullable()
});

/**
 * TradeReconcileRequest
 */
export const zTradeReconcileRequest = z.object({
    david_assets: z.array(zTradeAsset),
    received_assets: z.array(zTradeAsset)
});

/**
 * TradeRequest
 */
export const zTradeRequest = z.object({
    my_assets: z.array(z.record(z.string(), z.unknown())),
    their_assets: z.array(z.record(z.string(), z.unknown()))
});

/**
 * TradeSide
 */
export const zTradeSide = z.object({
    assets: z.array(zTradeAsset),
    consolidation_factor: z.number(),
    side_value: z.number(),
    xvar_sum: z.number()
});

/**
 * TradeEvaluation
 */
export const zTradeEvaluation = z.object({
    caveats: z.array(z.string()),
    decision_supported: z.boolean().optional().default(false),
    fairness_delta: z.number(),
    favors: z.string().nullable(),
    favors_xvar_margin: z.number().nullable(),
    side_a: zTradeSide,
    side_b: zTradeSide,
    within_parity_band: z.boolean()
});

/**
 * TradeRosterReconciliation
 */
export const zTradeRosterReconciliation = z.object({
    adjusted_david_received_value: z.number(),
    adjusted_fairness_delta: z.number(),
    adjusted_fairness_delta_range: z.tuple([z.number(), z.number()]).nullish(),
    adjusted_favors: z.string(),
    adjusted_favors_status: z.enum([
        'neutral',
        'david',
        'counterparty',
        'uncertain_range_crosses_parity'
    ]).optional().default('neutral'),
    adjusted_received_value_range: z.tuple([z.number(), z.number()]).nullish(),
    adjusted_within_parity_band: z.boolean(),
    base_evaluation: zTradeEvaluation,
    caveats: z.array(z.string()),
    decision_supported: z.boolean().optional().default(false),
    roster_penalty: zRosterPenaltySummary
});

/**
 * TrustSurfaceResponse
 *
 * Typed Trust Surface contract: the full BacktestResult plus the hoisted,
 * consumer-facing fields. Non-breaking superset of the prior dict response, so the
 * frontend Hey API codegen has a real OpenAPI schema (no untyped object).
 */
export const zTrustSurfaceResponse = z.object({
    divergence_validity: zDivergenceResult.nullish(),
    experimental: z.boolean(),
    folds: z.array(zFoldResult),
    git_sha: z.string().nullish(),
    market_snapshot_dates: z.record(z.string(), z.string()).nullish(),
    market_source: z.enum([
        'fc_native',
        'dp_archive',
        'ktc_community_csv',
        'unavailable'
    ]),
    market_source_label: z.enum([
        'fantasycalc_native',
        'dynastyprocess_ecr_2qb',
        'ktc_community_csv',
        'unavailable'
    ]).optional().default('unavailable'),
    model_artifact_hash: z.string(),
    model_card_available: z.boolean(),
    model_reliability: zModelReliability.nullish(),
    model_status: z.string(),
    model_version: z.string(),
    overall_grade: z.string(),
    position: z.enum([
        'QB',
        'RB',
        'WR',
        'TE'
    ]),
    promotion_gate: zGateResult,
    retrain_mode: z.enum(['refit_per_fold_fixed_alpha', 'frozen_retrospective']),
    ridge_alpha: z.number(),
    rmse_stability: zStabilityResult,
    run_date: z.iso.datetime(),
    run_id: z.uuid().optional(),
    schema_version: z.string().optional().default('1.0.0')
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    ctx: z.record(z.string(), z.unknown()).optional(),
    input: z.unknown().optional(),
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * WhatChangedCutCandidate
 */
export const zWhatChangedCutCandidate = z.object({
    cut_priority: z.int().nullish(),
    dvs: z.number().nullish(),
    player_name: z.string().nullish(),
    position: z.string().nullish(),
    sleeper_player_id: z.string().nullish(),
    xvar_pct: z.number().nullish()
});

/**
 * WhatChangedDropSummary
 */
export const zWhatChangedDropSummary = z.object({
    cuts_required: z.int().nullish(),
    roster_id: z.int().nullish(),
    total_capacity: z.int().nullish(),
    total_players: z.int().nullish()
});

/**
 * WhatChangedEnteredExited
 */
export const zWhatChangedEnteredExited = z.object({
    player_key: z.string(),
    sleeper_id: z.string()
});

/**
 * WhatChangedMarketDelta
 */
export const zWhatChangedMarketDelta = z.object({
    overall_rank_delta: z.int(),
    overall_rank_delta_direction: z.string(),
    player_key: z.string(),
    player_name: z.string().nullish(),
    position: z.string().nullish(),
    position_rank_delta: z.int(),
    position_rank_delta_direction: z.string(),
    sleeper_id: z.string(),
    value_delta: z.int(),
    value_delta_direction: z.string()
});

/**
 * WhatChangedMarketSection
 */
export const zWhatChangedMarketSection = z.object({
    aborted_reason: z.string().nullish(),
    comparison_window: z.record(z.string(), z.unknown()).nullish(),
    decision_supported: z.literal(false),
    entered: z.array(zWhatChangedEnteredExited).nullish(),
    exited: z.array(zWhatChangedEnteredExited).nullish(),
    market_source: z.string(),
    roster_deltas: z.array(zWhatChangedMarketDelta).nullish(),
    status: z.string(),
    top_movers: z.array(zWhatChangedMarketDelta).nullish(),
    total_movers_count: z.int().nullish()
});

/**
 * WhatChangedModelDelta
 */
export const zWhatChangedModelDelta = z.object({
    dvs_pct_delta: z.number(),
    dynasty_value_score_delta: z.number(),
    dynasty_value_score_delta_direction: z.string(),
    player_key: z.string(),
    player_name: z.string().nullish(),
    position: z.string().nullish(),
    sleeper_id: z.string().nullish(),
    xvar_delta: z.number()
});

/**
 * WhatChangedModelFeatureFreshness
 *
 * Descriptive engine_b feature-source freshness for the model section.
 *
 * Discloses which feature CSV backed the model vintage (a published runtime vs the
 * committed seed) and its hashes/as-of label, so the daily digest can show that captured
 * vintages are genuinely moving. Carries NO market field and certifies no decision.
 */
export const zWhatChangedModelFeatureFreshness = z.object({
    aborted_reason: z.string().nullish(),
    decision_supported: z.literal(false),
    feature_csv_path: z.string().nullish(),
    feature_csv_sha256: z.string().nullish(),
    feature_source_kind: z.enum(['runtime', 'seed']).nullish(),
    feature_source_status: z.literal('not_ready').nullish(),
    published_seed_sha256: z.string().nullish(),
    source_as_of: z.string().nullish()
});

/**
 * WhatChangedModelPvoSeedStaleness
 *
 * Descriptive seed-vs-runtime drift summary — the §3.6 manual-promotion tripwire.
 *
 * Surfaced ONLY when ``promotion_review_threshold_crossed`` is True (silent on quiet drift).
 * The field states the descriptive FACT that drift crossed the model-promotion review
 * threshold — it directs no action (David, the operator, decides). The count of
 * model-supported players drifted >5% and the coverage-count change are the stable triggers;
 * ``mean_abs_value_delta`` / ``p95_abs_value_delta`` are DISCLOSURE-only (never promotion
 * triggers — market-noise-sensitive). Carries no market field; certifies no decision.
 */
export const zWhatChangedModelPvoSeedStaleness = z.object({
    baseline_status: z.string().nullish(),
    count_model_supported_players_drifted_gt_5pct: z.int(),
    count_players_drifted_gt_5pct: z.int(),
    coverage_count_deltas: z.record(z.string(), z.int()),
    decision_supported: z.literal(false),
    mean_abs_value_delta: z.number(),
    p95_abs_value_delta: z.number(),
    promotion_review_threshold_crossed: z.boolean(),
    review_triggers: z.array(z.string()).nullish(),
    seed_age_days: z.number().nullish(),
    seed_as_of: z.string().nullish()
});

/**
 * WhatChangedModelPvoStaleness
 *
 * Descriptive PVO source provenance for the model section + passive seed-staleness.
 *
 * Provenance (source kind / hashes / as-of / paths) is ALWAYS disclosed so the digest can
 * show which artifact backed the vintage. The ``seed_staleness`` block appears only on the
 * promotion tripwire. A present-but-unverified runtime surfaces as ``not_ready`` (kind None
 * + ``aborted_reason``), never hidden. Closed vocabularies so the API cannot report a
 * phantom source kind/status. Carries NO market field and certifies no decision.
 */
export const zWhatChangedModelPvoStaleness = z.object({
    aborted_reason: z.string().nullish(),
    coverage_path: z.string().nullish(),
    coverage_sha256: z.string().nullish(),
    decision_supported: z.literal(false),
    pvo_path: z.string().nullish(),
    pvo_sha256: z.string().nullish(),
    pvo_source_kind: z.enum(['runtime', 'seed']).nullish(),
    pvo_source_status: z.literal('not_ready').nullish(),
    seed_staleness: zWhatChangedModelPvoSeedStaleness.nullish(),
    source_as_of: z.string().nullish()
});

/**
 * WhatChangedPartnerRanking
 */
export const zWhatChangedPartnerRanking = z.object({
    counterparty_roster_id: z.int().nullish(),
    counterparty_team_name: z.string().nullish(),
    matched_positions: z.array(z.string()).nullish(),
    partner_score: z.number().nullish()
});

/**
 * WhatChangedRosterCapacityContext
 */
export const zWhatChangedRosterCapacityContext = z.object({
    candidate_count: z.int().nullish(),
    hard_conflict_count: z.int().nullish(),
    pool_status: z.string().nullish()
});

/**
 * WhatChangedCard
 */
export const zWhatChangedCard = z.object({
    asset_name: z.string().nullish(),
    card_id: z.string().nullish(),
    card_type: z.string().nullish(),
    roster_capacity_context: zWhatChangedRosterCapacityContext.nullish()
});

/**
 * WhatChangedStalenessCaveat
 */
export const zWhatChangedStalenessCaveat = z.object({
    age_hours: z.number(),
    basis: z.string(),
    is_stale: z.boolean(),
    report_generated_at: z.string()
});

/**
 * WhatChangedTeamValueSummary
 */
export const zWhatChangedTeamValueSummary = z.object({
    depth_credit_xvar: z.number().nullish(),
    lineup_xvar: z.number().nullish(),
    posture_label: z.string().nullish(),
    roster_id: z.int().nullish(),
    starter_weighted_xvar: z.number().nullish(),
    team_name: z.string().nullish(),
    top_n_xvar: z.number().nullish(),
    total_xvar_capped: z.number().nullish()
});

/**
 * WhatChangedStructuralSection
 */
export const zWhatChangedStructuralSection = z.object({
    aborted_reason: z.string().nullish(),
    captured_at: z.string().nullish(),
    current_not_delta: z.boolean(),
    david_posture: z.string().nullish(),
    david_roster_id: z.int().nullish(),
    david_roster_player_count: z.int().nullish(),
    david_team_name: z.string().nullish(),
    david_value_summary: zWhatChangedTeamValueSummary.nullish(),
    decision_supported: z.literal(false),
    league_roster_count: z.int().nullish(),
    source_path: z.string().nullish(),
    staleness_caveat: zWhatChangedStalenessCaveat.nullish(),
    status: z.string(),
    summary: zWhatChangedDropSummary.nullish(),
    team_count: z.int().nullish(),
    top_candidates: z.array(zWhatChangedCutCandidate).nullish(),
    top_cards: z.array(zWhatChangedCard).nullish(),
    top_partner_rankings: z.array(zWhatChangedPartnerRanking).nullish()
});

/**
 * WhatChangedStructuralSections
 */
export const zWhatChangedStructuralSections = z.object({
    drop_pressure: zWhatChangedStructuralSection,
    league_opportunity: zWhatChangedStructuralSection,
    sleeper_snapshot: zWhatChangedStructuralSection,
    team_posture: zWhatChangedStructuralSection,
    team_value: zWhatChangedStructuralSection
});

/**
 * WhatChangedStructuralContext
 */
export const zWhatChangedStructuralContext = z.object({
    current_not_delta: z.boolean(),
    decision_supported: z.literal(false),
    sections: zWhatChangedStructuralSections,
    status: z.string()
});

/**
 * WhatChangedVintage
 *
 * A complete model vintage — both hashes required and non-blank.
 *
 * A vintage is the identity of a model output; a partial/empty vintage is never an
 * honest shape, so both fields are required (not Optional) and rejected if blank.
 */
export const zWhatChangedVintage = z.object({
    provenance_hash: z.string(),
    semantic_output_hash: z.string()
});

/**
 * WhatChangedModelComparisonWindow
 *
 * Allowlisted, shape-closed model window — no market key can hide on it.
 *
 * Admits ONLY the three honest model window shapes:
 * 1. ``{status: insufficient_history}`` — status alone.
 * 2. ``{status: model_multi_vintage_ambiguous, from_date, to_date, ambiguous_dates}``.
 * 3. ``{from_date, to_date, from_vintage, to_vintage}`` — clean two-date window, no status.
 *
 * ``extra="forbid"`` (via ``_Strict``) rejects unknown keys (incl. a nested
 * ``market_overlay``); the ``Literal`` status rejects unknown states; and the
 * post-validator rejects mixed/partial combinations so the window is fully closed.
 */
export const zWhatChangedModelComparisonWindow = z.object({
    ambiguous_dates: z.array(z.string()).nullish(),
    from_date: z.string().nullish(),
    from_vintage: zWhatChangedVintage.nullish(),
    status: z.enum(['insufficient_history', 'model_multi_vintage_ambiguous']).nullish(),
    to_date: z.string().nullish(),
    to_vintage: zWhatChangedVintage.nullish()
});

/**
 * WhatChangedModelSection
 */
export const zWhatChangedModelSection = z.object({
    comparison_window: zWhatChangedModelComparisonWindow.nullish(),
    decision_supported: z.literal(false),
    deltas: z.array(zWhatChangedModelDelta).nullish(),
    feature_freshness: zWhatChangedModelFeatureFreshness.nullish(),
    pvo_staleness: zWhatChangedModelPvoStaleness.nullish(),
    status: z.string(),
    vintage_changed: z.boolean().nullish()
});

/**
 * WhatChangedDailyDiff
 */
export const zWhatChangedDailyDiff = z.object({
    decision_supported: z.literal(false),
    market: zWhatChangedMarketSection,
    model: zWhatChangedModelSection,
    overall_status: z.string()
});

/**
 * WhatChangedResponse
 */
export const zWhatChangedResponse = z.object({
    daily_diff: zWhatChangedDailyDiff,
    decision_supported: z.literal(false),
    generated_at: z.string(),
    overall_status: z.string(),
    schema_version: z.string(),
    structural_context: zWhatChangedStructuralContext
});

/**
 * Response Get Engine B Scores Api Engine B Scores Get
 *
 * Successful Response
 */
export const zGetEngineBScoresApiEngineBScoresGetResponse = z.record(z.string(), z.unknown());

/**
 * Successful Response
 */
export const zGetSystemHealthApiHealthGetResponse = zSystemHealthResponse;

/**
 * Successful Response
 */
export const zLeaguePulseSurfaceApiLeaguePulseGetResponse = zLeaguePulseResponse;

/**
 * Successful Response
 */
export const zWhatChangedSurfaceApiLeagueWhatChangedGetResponse = zWhatChangedResponse;

export const zGetPlayerDetailApiPlayersSleeperIdGetPath = z.object({
    sleeper_id: z.string()
});

/**
 * Successful Response
 */
export const zGetPlayerDetailApiPlayersSleeperIdGetResponse = zPlayerDetailResponse;

/**
 * Successful Response
 */
export const zRealizedOutcomeScorecardApiRealizedOutcomeScorecardGetResponse = zRealizedOutcomeScorecardResponse;

export const zScoreSingleApiRookiesScorePostBody = zProspectRequest;

/**
 * Response Score Single Api Rookies Score Post
 *
 * Successful Response
 */
export const zScoreSingleApiRookiesScorePostResponse = z.record(z.string(), z.unknown());

/**
 * Prospects
 */
export const zScoreClassApiRookiesScoreClassPostBody = z.array(zProspectRequest);

/**
 * Response Score Class Api Rookies Score Class Post
 *
 * Successful Response
 */
export const zScoreClassApiRookiesScoreClassPostResponse = z.array(z.record(z.string(), z.unknown()));

/**
 * Successful Response
 */
export const zAuditRosterApiRosterAuditGetResponse = zRosterAuditResponse;

/**
 * Successful Response
 */
export const zRosterCapacitySurfaceApiRosterCapacityGetResponse = zRosterCapacityResponse;

/**
 * Successful Response
 */
export const zGetCaptureHealthApiSystemCaptureHealthGetResponse = zCaptureHealthResponse;

/**
 * Successful Response
 */
export const zGetModelProvenanceApiSystemModelProvenanceGetResponse = zModelProvenanceResponse;

/**
 * Successful Response
 */
export const zGetTierReadinessApiSystemTierReadinessGetResponse = zTierReadinessResponse;

export const zAnalyzeApiTradeAnalyzePostBody = zTradeRequest;

/**
 * Response Analyze Api Trade Analyze Post
 *
 * Successful Response
 */
export const zAnalyzeApiTradeAnalyzePostResponse = z.record(z.string(), z.unknown());

export const zTradeAssetsApiTradeAssetsGetQuery = z.object({
    q: z.string().optional().default(''),
    limit: z.int().optional().default(50)
});

/**
 * Successful Response
 */
export const zTradeAssetsApiTradeAssetsGetResponse = zTradeAssetCatalogResponse;

export const zEvaluateTradeEndpointApiTradeEvaluatePostBody = zTradeEvaluateRequest;

/**
 * Successful Response
 */
export const zEvaluateTradeEndpointApiTradeEvaluatePostResponse = zTradeEvaluation;

export const zReconcileTradeEndpointApiTradeReconcilePostBody = zTradeReconcileRequest;

/**
 * Successful Response
 */
export const zReconcileTradeEndpointApiTradeReconcilePostResponse = zTradeRosterReconciliation;

export const zReconcileTradeMarketEndpointApiTradeReconcileMarketPostBody = zMarketReconcileRequest;

/**
 * Successful Response
 */
export const zReconcileTradeMarketEndpointApiTradeReconcileMarketPostResponse = zTradeMarketReconciliation;

export const zGetTrustSurfaceApiTrustSurfacePositionGetPath = z.object({
    position: z.string()
});

/**
 * Successful Response
 */
export const zGetTrustSurfaceApiTrustSurfacePositionGetResponse = zTrustSurfaceResponse;

export const zGetModelCardApiTrustSurfacePositionModelCardGetPath = z.object({
    position: z.string()
});

/**
 * Successful Response
 */
export const zGetModelCardApiTrustSurfacePositionModelCardGetResponse = zModelCardResponse;
