// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * CounterArgumentField
 */
export const zCounterArgumentField = z.object({
    caveats: z.array(z.string()).optional().default([]),
    status: z.string(),
    text: z.string().nullable()
});

/**
 * DegradationField
 */
export const zDegradationField = z.object({
    message: z.string()
});

/**
 * DivergenceField
 */
export const zDivergenceField = z.object({
    delta: z.number().nullable(),
    status: z.string()
});

/**
 * DivergenceResult
 *
 * Gate 4. Populated only when sufficient FC snapshots and flagged player data exist.
 */
export const zDivergenceResult = z.object({
    diff_bca_ci95: z.tuple([z.number(), z.number()]),
    forward_horizon_days: z.int(),
    hit_rate: z.number(),
    hit_rate_wilson_ci95: z.tuple([z.number(), z.number()]),
    mann_whitney_method: z.string(),
    mann_whitney_p: z.number(),
    mann_whitney_u: z.number(),
    mean_alpha_control: z.number(),
    mean_alpha_flagged: z.number(),
    n_excluded_injury: z.int(),
    n_flagged: z.int(),
    n_matched_controls_per_flag: z.int().optional().default(3),
    position_beta: z.number()
});

/**
 * EvidenceListField
 */
export const zEvidenceListField = z.object({
    caveats: z.array(z.string()).optional().default([]),
    items: z.array(z.string()).optional().default([])
});

/**
 * MarketAssetRef
 */
export const zMarketAssetRef = z.object({
    asset_kind: z.enum([
        'player',
        'prospect_player',
        'future_pick'
    ]),
    bucket: z.enum([
        'early',
        'mid',
        'late'
    ]).nullish(),
    decision_supported: z.boolean().optional().default(false),
    player_id: z.string().nullish(),
    quantity_id: z.string().nullish(),
    round: z.int().nullish(),
    sleeper_id: z.string().nullish(),
    slot: z.int().nullish(),
    year: z.int().nullish()
});

/**
 * MarketDivergenceContext
 */
export const zMarketDivergenceContext = z.object({
    caveats: z.array(z.string()),
    decision_supported: z.boolean().optional().default(false),
    percentile_delta: z.number().nullable(),
    sigma_threshold: z.number(),
    signal_label: z.enum([
        'model_higher_than_market',
        'model_lower_than_market',
        'inside_band',
        'unavailable'
    ]),
    source_signal_status: z.string().nullable()
});

/**
 * MarketAssetOverlay
 */
export const zMarketAssetOverlay = z.object({
    asset_ref: zMarketAssetRef,
    caveats: z.array(z.string()),
    coverage_gap: z.string().nullable(),
    decision_supported: z.boolean().optional().default(false),
    divergence_context: zMarketDivergenceContext.nullish(),
    format_key: z.string(),
    label: z.string(),
    market_value: z.int().nullable(),
    market_volatility: z.number().nullish(),
    resolution: z.enum([
        'player_sleeper_id',
        'pick_exact_slot',
        'pick_generic_year_round',
        'unresolved'
    ]),
    source: z.literal('fantasycalc'),
    source_timestamp: z.string().nullish(),
    trend_30d: z.int().nullish()
});

/**
 * MarketRealismWarning
 */
export const zMarketRealismWarning = z.object({
    caveats: z.array(z.string()),
    decision_supported: z.boolean().optional().default(false),
    message: z.string(),
    metrics: z.record(z.string(), z.number()),
    severity: z.literal('advisory'),
    warning_type: z.enum([
        'package_dilution_warning',
        'roster_filler_warning',
        'market_package_requires_manual_review'
    ])
});

/**
 * MarketReconcileRequest
 */
export const zMarketReconcileRequest = z.object({
    counterparty_roster_id: z.int().nullish(),
    current_draft_year: z.int().optional().default(2026),
    format_key: z.string().optional().default('dynasty_sf_ppr'),
    received_assets: z.array(zMarketAssetRef),
    sent_assets: z.array(zMarketAssetRef)
});

/**
 * MarketRosterPenalty
 */
export const zMarketRosterPenalty = z.object({
    caveats: z.array(z.string()),
    decision_supported: z.boolean().optional().default(false),
    forced_cut_candidates: z.array(zMarketAssetOverlay),
    penalty_market_value: z.int(),
    post_trade_overflow: z.int(),
    roster_id: z.int(),
    unresolved_cut_count: z.int()
});

/**
 * ModelCardResponse
 *
 * Curated PUBLIC model-card contract — the 8 safety/identity fields only.
 *
 * Provenance fields (model_version / model_artifact_hash / git_sha) live on the
 * audit-internal PublishedModelCardSource artifact and are deliberately NOT exposed
 * here, so the public surface never leaks the 9-section ModelCard internals.
 */
export const zModelCardResponse = z.object({
    backtest_run_id: z.string().nullable(),
    caveats: z.array(z.string()),
    generated_at: z.string().nullable(),
    intended_use: z.string(),
    is_experimental: z.boolean(),
    known_failure_modes: z.array(z.string()),
    out_of_scope_uses: z.array(z.string()),
    position: z.string()
});

/**
 * ModelReliability
 *
 * QB-only descriptive model-reliability stamp (measured uncertainty, no verdict).
 */
export const zModelReliability = z.object({
    caveat: z.string(),
    position: z.string(),
    r2_oos_mean: z.number().nullish(),
    spearman_rho_mean: z.number().nullish()
});

/**
 * PlayerEvidence
 */
export const zPlayerEvidence = z.object({
    caveats: zEvidenceListField,
    counter_argument: zCounterArgumentField,
    risk_flags: zEvidenceListField,
    top_drivers: zEvidenceListField
});

/**
 * PlayerIdentity
 */
export const zPlayerIdentity = z.object({
    age: z.number().nullable(),
    draft_class: z.int().nullable(),
    name: z.string().nullable(),
    nfl_draft_pick: z.int().nullable(),
    nfl_draft_round: z.int().nullable(),
    position: z.string().nullable(),
    sleeper_id: z.string(),
    team: z.string().nullable()
});

/**
 * PlayerMarketLane
 */
export const zPlayerMarketLane = z.object({
    caveats: z.array(z.string()).optional().default([]),
    market_rank_overall: z.int().nullable(),
    market_rank_position: z.int().nullable(),
    market_value: z.number().nullable(),
    source: z.string().nullable(),
    source_timestamp: z.string().nullable(),
    status: z.string()
});

/**
 * PlayerModelLane
 */
export const zPlayerModelLane = z.object({
    dynasty_value_score: z.number().nullable(),
    engine_path: z.string().nullable(),
    model_grade: z.string().nullable(),
    model_version: z.string().nullable(),
    projection_1y: z.number().nullable(),
    projection_2y: z.number().nullable(),
    projection_3y: z.number().nullable(),
    xvar: z.number().nullable(),
    xvar_percentile_position: z.number().nullable()
});

/**
 * PlayerDetailResponse
 */
export const zPlayerDetailResponse = z.object({
    caveats: z.array(z.string()).optional().default([]),
    decision_supported: z.literal(false).optional().default(false),
    degradation: zDegradationField.nullable(),
    divergence: zDivergenceField,
    evidence: zPlayerEvidence.nullable(),
    identity: zPlayerIdentity,
    market: zPlayerMarketLane,
    model: zPlayerModelLane.nullable(),
    model_status: z.string(),
    sleeper_id: z.string(),
    source_timestamps: z.record(z.string(), z.string().nullable())
});

/**
 * ProspectRequest
 */
export const zProspectRequest = z.object({
    age: z.number(),
    draft_class: z.int().nullish(),
    final_college_age: z.number().nullish(),
    name: z.string(),
    pick: z.int(),
    position: z.string(),
    round: z.int(),
    sleeper_id: z.string().nullish(),
    te_ryptpa_final: z.number().nullish(),
    te_yards_per_reception_career: z.number().nullish()
});

/**
 * QBContextCard
 *
 * F2: explicitly typed; extra fields forbidden (no provenance/market backdoor).
 */
export const zQbContextCard = z.object({
    context_role: z.literal('context_signal').optional().default('context_signal'),
    cpoe: z.number().nullish(),
    dakota: z.number().nullish(),
    decision_supported: z.literal(false).optional().default(false),
    dropback_count: z.number().nullish(),
    epa_per_dropback: z.number().nullish(),
    full_name: z.string(),
    identity_coverage: z.enum([
        'FULL',
        'PARTIAL',
        'NONE'
    ]),
    pass_attempts: z.number().nullish(),
    player_id: z.string(),
    qb_context_annotations: z.array(z.string()).optional(),
    qb_context_caveats: z.array(z.string()).optional(),
    source_qb_context_annotations: z.string()
});

/**
 * RosterAuditSignalsView
 *
 * F3: curated signals view; nested decision_supported can never leak true.
 */
export const zRosterAuditSignalsView = z.object({
    age_cliff_risk: z.number().nullish(),
    age_value_context: z.string().nullish(),
    biological_debt_score: z.number().nullish(),
    caveats: z.array(z.string()).optional(),
    cliff_age: z.int().nullish(),
    decision_supported: z.literal(false).optional().default(false),
    liquidity_risk: z.string().nullish(),
    signal: z.string().nullish(),
    signal_drivers: z.array(z.string()).optional(),
    years_to_cliff: z.int().nullish()
});

/**
 * RosterAuditPlayer
 */
export const zRosterAuditPlayer = z.object({
    age: z.number().nullish(),
    caveats: z.array(z.string()).optional(),
    counter_argument: zCounterArgumentField,
    decision_supported: z.literal(false).optional().default(false),
    draft_class: z.int().nullish(),
    dvs_engine: z.enum([
        'A',
        'B',
        'blend'
    ]).nullish(),
    dvs_pct: z.number().nullish(),
    dynasty_value_score: z.number().nullish(),
    engine_used: z.string().nullish(),
    full_name: z.string(),
    inputs_missing: z.array(z.string()).optional(),
    inputs_present: z.array(z.string()).optional(),
    is_prospect: z.boolean().optional().default(false),
    model_grade: z.string(),
    model_status_applies: z.boolean().optional().default(false),
    model_version: z.string().nullish(),
    nfl_draft_pick: z.int().nullish(),
    nfl_draft_round: z.int().nullish(),
    nfl_team: z.string().nullish(),
    player_id: z.string(),
    position: z.string(),
    projection_1y: z.number().nullish(),
    projection_2y: z.number().nullish(),
    projection_3y: z.number().nullish(),
    risk_flags: zEvidenceListField,
    roster_audit: zRosterAuditSignalsView.nullish(),
    signal_completeness: z.number().optional().default(0),
    sleeper_id: z.string().nullish(),
    top_drivers: zEvidenceListField,
    xvar: z.number().nullish()
});

/**
 * RosterAuditResponse
 */
export const zRosterAuditResponse = z.object({
    caveats: z.array(z.string()).optional(),
    decision_supported: z.literal(false).optional().default(false),
    dropped_player_count: z.int().optional().default(0),
    engine: z.string(),
    model_status_by_position: z.record(z.string(), z.enum([
        'VALIDATED',
        'PROVISIONAL',
        'EXPERIMENTAL'
    ])),
    players: z.array(zRosterAuditPlayer).optional(),
    qb_context_cards: z.array(zQbContextCard).optional(),
    reason: z.string(),
    status: z.enum(['active', 'degraded'])
});

/**
 * RosterPenaltySummary
 */
export const zRosterPenaltySummary = z.object({
    decision_supported: z.boolean().optional().default(false),
    forced_cut_candidates: z.array(z.record(z.string(), z.unknown())),
    forced_cut_penalty_xvar: z.number(),
    penalty_caveats: z.array(z.string()),
    post_trade_overflow: z.int(),
    post_trade_total_players: z.int()
});

/**
 * StabilityResult
 */
export const zStabilityResult = z.object({
    dm_hln_pvalue: z.number().nullish(),
    dm_hln_statistic: z.number().nullish(),
    dm_method: z.string().optional().default('harvey_leybourne_newbold_1997'),
    dm_passes: z.boolean().nullish(),
    rmse_cv: z.number(),
    rmse_max_deviation_pct: z.number(),
    rmse_mean: z.number(),
    rmse_per_fold: z.array(z.number())
});

/**
 * StatusExplanation
 *
 * Auditable record of why a model_status was assigned (Step 0.5 spec §6.5).
 *
 * Records which folds failed each validity predicate and whether the cold-start
 * fold was excused, so the status is a documented decision rather than a vibe.
 */
export const zStatusExplanation = z.object({
    cold_start_fold_index: z.int().nullish(),
    cold_start_tolerated: z.boolean().optional().default(false),
    failed_ci_folds: z.array(z.int()).optional(),
    failed_rank_folds: z.array(z.int()).optional(),
    leakage_clean: z.boolean().nullish(),
    most_recent_fold_index: z.int().nullish(),
    most_recent_fold_pass: z.boolean().nullish(),
    null_coverage_min: z.number().nullish(),
    reason: z.string().optional().default('')
});

/**
 * GateResult
 */
export const zGateResult = z.object({
    g1_rank_correlation_pass: z.boolean(),
    g2_rmse_stability_pass: z.boolean(),
    g3_market_superiority_pass: z.union([
        z.literal(true),
        z.literal(false),
        z.literal('deferred')
    ]),
    g4_divergence_validity_pass: z.union([
        z.literal(true),
        z.literal(false),
        z.literal('deferred'),
        z.literal('insufficient_data')
    ]),
    gate_version: z.string().optional().default('1.0'),
    model_status: z.enum([
        'VALIDATED',
        'PROVISIONAL',
        'EXPERIMENTAL'
    ]).optional().default('EXPERIMENTAL'),
    null_coverage_min: z.number().nullish(),
    overall_grade: z.enum([
        'PRE_MODEL',
        'EXPERIMENTAL',
        'ACTIVE_B',
        'ACTIVE_B_VALIDATED',
        'DECISION_GRADE'
    ]),
    promotion_justification: z.string(),
    status_explanation: zStatusExplanation.nullish(),
    status_version: z.string().optional().default('0.5.0'),
    validity_ci_adequacy_pass: z.boolean().optional().default(false),
    validity_cold_start_fold_index: z.int().nullish(),
    validity_cold_start_tolerated: z.boolean().optional().default(false),
    validity_leakage_pass: z.boolean().optional().default(false),
    validity_most_recent_fold_index: z.int().nullish(),
    validity_most_recent_fold_pass: z.boolean().nullish(),
    validity_null_coverage_pass: z.boolean().optional().default(false),
    validity_r2_pass: z.boolean().optional().default(false),
    validity_rmse_stability_pass: z.boolean().optional().default(false),
    validity_spearman_pass: z.boolean().optional().default(false)
});

/**
 * TopKResult
 */
export const zTopKResult = z.object({
    diff_wilson_ci95: z.tuple([z.number(), z.number()]),
    k: z.int(),
    market_hit_rate: z.number(),
    model_hit_rate: z.number()
});

/**
 * FoldResult
 */
export const zFoldResult = z.object({
    calibration_by_decile: z.array(z.number()).nullish(),
    feature_coefficients: z.record(z.string(), z.number()).nullish(),
    fold_index: z.int(),
    kendall_tau: z.number(),
    kendall_tau_bca_ci95: z.tuple([z.number(), z.number()]),
    mae: z.number(),
    market_pool_n: z.int().nullish(),
    metric_caveats: z.array(z.string()).optional(),
    n_excluded_injury: z.int().optional().default(0),
    n_test: z.int(),
    n_train: z.int(),
    ndcg_at_12_market: z.number().nullish(),
    ndcg_at_12_model: z.number().nullish(),
    ndcg_at_24_market: z.number().nullish(),
    ndcg_at_24_model: z.number().nullish(),
    ndcg_diff_bca_ci95: z.tuple([z.number(), z.number()]).nullish(),
    ndcg_diff_primary_k: z.number().nullish(),
    null_coverage: z.number().nullish(),
    outcome_seasons: z.array(z.int()),
    precision_at_k: z.record(z.string(), zTopKResult).nullish(),
    primary_k: z.int().nullish(),
    r2_oos: z.number().nullish(),
    rank_ic: z.number(),
    regime_notes: z.string().nullish(),
    rmse: z.number(),
    spearman_rho: z.number(),
    spearman_rho_bca_ci95: z.tuple([z.number(), z.number()]),
    test_year: z.int(),
    train_years: z.array(z.int())
});

/**
 * TradeAsset
 */
export const zTradeAsset = z.object({
    caveat: z.string().nullish(),
    decision_supported: z.boolean().optional().default(false),
    dvs: z.number().nullish(),
    dvs_engine: z.string().nullish(),
    is_prospect: z.boolean().optional().default(false),
    player_id: z.string(),
    position: z.string(),
    xvar: z.number().nullable()
});

/**
 * TradeAssetCatalogEntry
 *
 * A single selectable asset, pre-shaped in both payload forms.
 */
export const zTradeAssetCatalogEntry = z.object({
    asset_id: z.string(),
    caveats: z.array(z.string()).optional().default([]),
    decision_supported: z.boolean().optional().default(false),
    kind: z.enum(['player', 'future_pick']),
    label: z.string(),
    market_ref: zMarketAssetRef,
    model_payload: zTradeAsset,
    position: z.string().nullish(),
    roster_owner_id: z.int().nullish(),
    roster_owner_name: z.string().nullish()
});

/**
 * TradeAssetCatalogResponse
 *
 * The catalog envelope for a single search query.
 */
export const zTradeAssetCatalogResponse = z.object({
    caveats: z.array(z.string()).optional().default([]),
    decision_supported: z.boolean().optional().default(false),
    query: z.string(),
    results: z.array(zTradeAssetCatalogEntry).optional().default([]),
    source_timestamp: z.string().nullish()
});

/**
 * TradeEvaluateRequest
 */
export const zTradeEvaluateRequest = z.object({
    side_a: z.array(zTradeAsset),
    side_b: z.array(zTradeAsset)
});

/**
 * TradeMarketReconciliation
 */
export const zTradeMarketReconciliation = z.object({
    adjusted_market_received: z.int(),
    adjusted_market_sent: z.int(),
    caveats: z.array(z.string()),
    counterparty_forced_cut_penalty: zMarketRosterPenalty.nullable(),
    counterparty_market_penalty_status: z.enum([
        'not_requested',
        'available',
        'unavailable'
    ]).optional().default('not_requested'),
    coverage_gaps: z.array(z.string()),
    david_forced_cut_penalty: zMarketRosterPenalty.nullable(),
    decision_supported: z.boolean().optional().default(false),
    format_key: z.string(),
    market_delta_for_david: z.int(),
    market_received_raw: z.int(),
    market_sent_raw: z.int(),
    market_source: z.literal('fantasycalc'),
    realism_warnings: z.array(zMarketRealismWarning).optional().default([]),
    received_assets: z.array(zMarketAssetOverlay),
    sent_assets: z.array(zMarketAssetOverlay),
    source_timestamp: z.string().nullable()
});

/**
 * TradeReconcileRequest
 */
export const zTradeReconcileRequest = z.object({
    david_assets: z.array(zTradeAsset),
    received_assets: z.array(zTradeAsset)
});

/**
 * TradeRequest
 */
export const zTradeRequest = z.object({
    my_assets: z.array(z.record(z.string(), z.unknown())),
    their_assets: z.array(z.record(z.string(), z.unknown()))
});

/**
 * TradeSide
 */
export const zTradeSide = z.object({
    assets: z.array(zTradeAsset),
    consolidation_factor: z.number(),
    side_value: z.number(),
    xvar_sum: z.number()
});

/**
 * TradeEvaluation
 */
export const zTradeEvaluation = z.object({
    caveats: z.array(z.string()),
    decision_supported: z.boolean().optional().default(false),
    fairness_delta: z.number(),
    favors: z.string().nullable(),
    favors_xvar_margin: z.number().nullable(),
    side_a: zTradeSide,
    side_b: zTradeSide,
    within_parity_band: z.boolean()
});

/**
 * TradeRosterReconciliation
 */
export const zTradeRosterReconciliation = z.object({
    adjusted_david_received_value: z.number(),
    adjusted_fairness_delta: z.number(),
    adjusted_favors: z.string(),
    adjusted_within_parity_band: z.boolean(),
    base_evaluation: zTradeEvaluation,
    caveats: z.array(z.string()),
    decision_supported: z.boolean().optional().default(false),
    roster_penalty: zRosterPenaltySummary
});

/**
 * TrustSurfaceResponse
 *
 * Typed Trust Surface contract: the full BacktestResult plus the hoisted,
 * consumer-facing fields. Non-breaking superset of the prior dict response, so the
 * frontend Hey API codegen has a real OpenAPI schema (no untyped object).
 */
export const zTrustSurfaceResponse = z.object({
    divergence_validity: zDivergenceResult.nullish(),
    experimental: z.boolean(),
    folds: z.array(zFoldResult),
    git_sha: z.string().nullish(),
    market_snapshot_dates: z.record(z.string(), z.string()).nullish(),
    market_source: z.enum([
        'fc_native',
        'dp_archive',
        'ktc_community_csv',
        'unavailable'
    ]),
    market_source_label: z.enum([
        'fantasycalc_native',
        'dynastyprocess_ecr_2qb',
        'ktc_community_csv',
        'unavailable'
    ]).optional().default('unavailable'),
    model_artifact_hash: z.string(),
    model_card_available: z.boolean(),
    model_reliability: zModelReliability.nullish(),
    model_status: z.string(),
    model_version: z.string(),
    overall_grade: z.string(),
    position: z.enum([
        'QB',
        'RB',
        'WR',
        'TE'
    ]),
    promotion_gate: zGateResult,
    retrain_mode: z.enum(['refit_per_fold_fixed_alpha', 'frozen_retrospective']),
    ridge_alpha: z.number(),
    rmse_stability: zStabilityResult,
    run_date: z.iso.datetime(),
    run_id: z.uuid().optional(),
    schema_version: z.string().optional().default('1.0.0')
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    ctx: z.record(z.string(), z.unknown()).optional(),
    input: z.unknown().optional(),
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * Response Get Engine B Scores Api Engine B Scores Get
 *
 * Successful Response
 */
export const zGetEngineBScoresApiEngineBScoresGetResponse = z.record(z.string(), z.unknown());

export const zGetPlayerDetailApiPlayersSleeperIdGetPath = z.object({
    sleeper_id: z.string()
});

/**
 * Successful Response
 */
export const zGetPlayerDetailApiPlayersSleeperIdGetResponse = zPlayerDetailResponse;

export const zScoreSingleApiRookiesScorePostBody = zProspectRequest;

/**
 * Response Score Single Api Rookies Score Post
 *
 * Successful Response
 */
export const zScoreSingleApiRookiesScorePostResponse = z.record(z.string(), z.unknown());

/**
 * Prospects
 */
export const zScoreClassApiRookiesScoreClassPostBody = z.array(zProspectRequest);

/**
 * Response Score Class Api Rookies Score Class Post
 *
 * Successful Response
 */
export const zScoreClassApiRookiesScoreClassPostResponse = z.array(z.record(z.string(), z.unknown()));

/**
 * Successful Response
 */
export const zAuditRosterApiRosterAuditGetResponse = zRosterAuditResponse;

export const zAnalyzeApiTradeAnalyzePostBody = zTradeRequest;

/**
 * Response Analyze Api Trade Analyze Post
 *
 * Successful Response
 */
export const zAnalyzeApiTradeAnalyzePostResponse = z.record(z.string(), z.unknown());

export const zTradeAssetsApiTradeAssetsGetQuery = z.object({
    q: z.string().optional().default(''),
    limit: z.int().optional().default(50)
});

/**
 * Successful Response
 */
export const zTradeAssetsApiTradeAssetsGetResponse = zTradeAssetCatalogResponse;

export const zEvaluateTradeEndpointApiTradeEvaluatePostBody = zTradeEvaluateRequest;

/**
 * Successful Response
 */
export const zEvaluateTradeEndpointApiTradeEvaluatePostResponse = zTradeEvaluation;

export const zReconcileTradeEndpointApiTradeReconcilePostBody = zTradeReconcileRequest;

/**
 * Successful Response
 */
export const zReconcileTradeEndpointApiTradeReconcilePostResponse = zTradeRosterReconciliation;

export const zReconcileTradeMarketEndpointApiTradeReconcileMarketPostBody = zMarketReconcileRequest;

/**
 * Successful Response
 */
export const zReconcileTradeMarketEndpointApiTradeReconcileMarketPostResponse = zTradeMarketReconciliation;

export const zGetTrustSurfaceApiTrustSurfacePositionGetPath = z.object({
    position: z.string()
});

/**
 * Successful Response
 */
export const zGetTrustSurfaceApiTrustSurfacePositionGetResponse = zTrustSurfaceResponse;

export const zGetModelCardApiTrustSurfacePositionModelCardGetPath = z.object({
    position: z.string()
});

/**
 * Successful Response
 */
export const zGetModelCardApiTrustSurfacePositionModelCardGetResponse = zModelCardResponse;
