// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * DivergenceResult
 *
 * Gate 4. Populated only when sufficient FC snapshots and flagged player data exist.
 */
export const zDivergenceResult = z.object({
    diff_bca_ci95: z.tuple([z.number(), z.number()]),
    forward_horizon_days: z.int(),
    hit_rate: z.number(),
    hit_rate_wilson_ci95: z.tuple([z.number(), z.number()]),
    mann_whitney_method: z.string(),
    mann_whitney_p: z.number(),
    mann_whitney_u: z.number(),
    mean_alpha_control: z.number(),
    mean_alpha_flagged: z.number(),
    n_excluded_injury: z.int(),
    n_flagged: z.int(),
    n_matched_controls_per_flag: z.int().optional().default(3),
    position_beta: z.number()
});

/**
 * GateResult
 */
export const zGateResult = z.object({
    g1_rank_correlation_pass: z.boolean(),
    g2_rmse_stability_pass: z.boolean(),
    g3_market_superiority_pass: z.union([
        z.literal(true),
        z.literal(false),
        z.literal('deferred')
    ]),
    g4_divergence_validity_pass: z.union([
        z.literal(true),
        z.literal(false),
        z.literal('deferred'),
        z.literal('insufficient_data')
    ]),
    gate_version: z.string().optional().default('1.0'),
    overall_grade: z.enum([
        'PRE_MODEL',
        'EXPERIMENTAL',
        'ACTIVE_B',
        'ACTIVE_B_VALIDATED',
        'DECISION_GRADE'
    ]),
    promotion_justification: z.string()
});

/**
 * MarketReconcileRequest
 */
export const zMarketReconcileRequest = z.object({
    counterparty_roster_id: z.int().nullish(),
    current_draft_year: z.int().optional().default(2026),
    format_key: z.string().optional().default('dynasty_sf_ppr'),
    received_assets: z.array(z.record(z.string(), z.unknown())),
    sent_assets: z.array(z.record(z.string(), z.unknown()))
});

/**
 * ModelReliability
 *
 * QB-only descriptive model-reliability stamp (measured uncertainty, no verdict).
 */
export const zModelReliability = z.object({
    caveat: z.string(),
    position: z.string(),
    r2_oos_mean: z.number().nullish(),
    spearman_rho_mean: z.number().nullish()
});

/**
 * ProspectRequest
 */
export const zProspectRequest = z.object({
    age: z.number(),
    draft_class: z.int().nullish(),
    final_college_age: z.number().nullish(),
    name: z.string(),
    pick: z.int(),
    position: z.string(),
    round: z.int(),
    sleeper_id: z.string().nullish(),
    te_ryptpa_final: z.number().nullish(),
    te_yards_per_reception_career: z.number().nullish()
});

/**
 * StabilityResult
 */
export const zStabilityResult = z.object({
    dm_hln_pvalue: z.number().nullish(),
    dm_hln_statistic: z.number().nullish(),
    dm_method: z.string().optional().default('harvey_leybourne_newbold_1997'),
    dm_passes: z.boolean().nullish(),
    rmse_cv: z.number(),
    rmse_max_deviation_pct: z.number(),
    rmse_mean: z.number(),
    rmse_per_fold: z.array(z.number())
});

/**
 * TopKResult
 */
export const zTopKResult = z.object({
    diff_wilson_ci95: z.tuple([z.number(), z.number()]),
    k: z.int(),
    market_hit_rate: z.number(),
    model_hit_rate: z.number()
});

/**
 * FoldResult
 */
export const zFoldResult = z.object({
    calibration_by_decile: z.array(z.number()).nullish(),
    feature_coefficients: z.record(z.string(), z.number()).nullish(),
    fold_index: z.int(),
    kendall_tau: z.number(),
    kendall_tau_bca_ci95: z.tuple([z.number(), z.number()]),
    mae: z.number(),
    market_pool_n: z.int().nullish(),
    metric_caveats: z.array(z.string()).optional(),
    n_excluded_injury: z.int().optional().default(0),
    n_test: z.int(),
    n_train: z.int(),
    ndcg_at_12_market: z.number().nullish(),
    ndcg_at_12_model: z.number().nullish(),
    ndcg_at_24_market: z.number().nullish(),
    ndcg_at_24_model: z.number().nullish(),
    ndcg_diff_bca_ci95: z.tuple([z.number(), z.number()]).nullish(),
    ndcg_diff_primary_k: z.number().nullish(),
    outcome_seasons: z.array(z.int()),
    precision_at_k: z.record(z.string(), zTopKResult).nullish(),
    primary_k: z.int().nullish(),
    r2_oos: z.number().nullish(),
    rank_ic: z.number(),
    regime_notes: z.string().nullish(),
    rmse: z.number(),
    spearman_rho: z.number(),
    spearman_rho_bca_ci95: z.tuple([z.number(), z.number()]),
    test_year: z.int(),
    train_years: z.array(z.int())
});

/**
 * TradeEvaluateRequest
 */
export const zTradeEvaluateRequest = z.object({
    side_a: z.array(z.record(z.string(), z.unknown())),
    side_b: z.array(z.record(z.string(), z.unknown()))
});

/**
 * TradeReconcileRequest
 */
export const zTradeReconcileRequest = z.object({
    david_assets: z.array(z.record(z.string(), z.unknown())),
    received_assets: z.array(z.record(z.string(), z.unknown()))
});

/**
 * TradeRequest
 */
export const zTradeRequest = z.object({
    my_assets: z.array(z.record(z.string(), z.unknown())),
    their_assets: z.array(z.record(z.string(), z.unknown()))
});

/**
 * TrustSurfaceResponse
 *
 * Typed Trust Surface contract: the full BacktestResult plus the hoisted,
 * consumer-facing fields. Non-breaking superset of the prior dict response, so the
 * frontend Hey API codegen has a real OpenAPI schema (no untyped object).
 */
export const zTrustSurfaceResponse = z.object({
    divergence_validity: zDivergenceResult.nullish(),
    experimental: z.boolean(),
    folds: z.array(zFoldResult),
    git_sha: z.string().nullish(),
    market_snapshot_dates: z.record(z.string(), z.string()).nullish(),
    market_source: z.enum([
        'fc_native',
        'dp_archive',
        'ktc_community_csv',
        'unavailable'
    ]),
    market_source_label: z.enum([
        'fantasycalc_native',
        'dynastyprocess_ecr_2qb',
        'ktc_community_csv',
        'unavailable'
    ]).optional().default('unavailable'),
    model_artifact_hash: z.string(),
    model_card_available: z.boolean(),
    model_reliability: zModelReliability.nullish(),
    model_version: z.string(),
    overall_grade: z.string(),
    position: z.enum([
        'QB',
        'RB',
        'WR',
        'TE'
    ]),
    promotion_gate: zGateResult,
    retrain_mode: z.enum(['refit_per_fold_fixed_alpha', 'frozen_retrospective']),
    ridge_alpha: z.number(),
    rmse_stability: zStabilityResult,
    run_date: z.iso.datetime(),
    run_id: z.uuid().optional(),
    schema_version: z.string().optional().default('1.0.0')
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    ctx: z.record(z.string(), z.unknown()).optional(),
    input: z.unknown().optional(),
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * Response Get Engine B Scores Api Engine B Scores Get
 *
 * Successful Response
 */
export const zGetEngineBScoresApiEngineBScoresGetResponse = z.record(z.string(), z.unknown());

export const zScoreSingleApiRookiesScorePostBody = zProspectRequest;

/**
 * Response Score Single Api Rookies Score Post
 *
 * Successful Response
 */
export const zScoreSingleApiRookiesScorePostResponse = z.record(z.string(), z.unknown());

/**
 * Prospects
 */
export const zScoreClassApiRookiesScoreClassPostBody = z.array(zProspectRequest);

/**
 * Response Score Class Api Rookies Score Class Post
 *
 * Successful Response
 */
export const zScoreClassApiRookiesScoreClassPostResponse = z.array(z.record(z.string(), z.unknown()));

/**
 * Response Audit Roster Api Roster Audit Get
 *
 * Successful Response
 */
export const zAuditRosterApiRosterAuditGetResponse = z.record(z.string(), z.unknown());

export const zAnalyzeApiTradeAnalyzePostBody = zTradeRequest;

/**
 * Response Analyze Api Trade Analyze Post
 *
 * Successful Response
 */
export const zAnalyzeApiTradeAnalyzePostResponse = z.record(z.string(), z.unknown());

export const zEvaluateTradeEndpointApiTradeEvaluatePostBody = zTradeEvaluateRequest;

/**
 * Response Evaluate Trade Endpoint Api Trade Evaluate Post
 *
 * Successful Response
 */
export const zEvaluateTradeEndpointApiTradeEvaluatePostResponse = z.record(z.string(), z.unknown());

export const zReconcileTradeEndpointApiTradeReconcilePostBody = zTradeReconcileRequest;

/**
 * Response Reconcile Trade Endpoint Api Trade Reconcile Post
 *
 * Successful Response
 */
export const zReconcileTradeEndpointApiTradeReconcilePostResponse = z.record(z.string(), z.unknown());

export const zReconcileTradeMarketEndpointApiTradeReconcileMarketPostBody = zMarketReconcileRequest;

/**
 * Response Reconcile Trade Market Endpoint Api Trade Reconcile Market Post
 *
 * Successful Response
 */
export const zReconcileTradeMarketEndpointApiTradeReconcileMarketPostResponse = z.record(z.string(), z.unknown());

export const zGetTrustSurfaceApiTrustSurfacePositionGetPath = z.object({
    position: z.string()
});

/**
 * Successful Response
 */
export const zGetTrustSurfaceApiTrustSurfacePositionGetResponse = zTrustSurfaceResponse;

export const zGetModelCardApiTrustSurfacePositionModelCardGetPath = z.object({
    position: z.string()
});

/**
 * Response Get Model Card Api Trust Surface  Position  Model Card Get
 *
 * Successful Response
 */
export const zGetModelCardApiTrustSurfacePositionModelCardGetResponse = z.record(z.string(), z.unknown());
