"""PlayerProfiler corrected decision gate.

This gate evaluates the clean enriched artifact generated by
scripts/enrich_training_data.py. The original pp_probe_results.json probe used
the wrong retrieval path and is no longer authoritative.

Path A is still unavailable in this branch: if clean coverage reaches the 80%
threshold, this test should fail and force an explicit promotion/backtest
decision rather than silently treating PlayerProfiler as a model input.
"""
from __future__ import annotations

import csv
from pathlib import Path

import pytest

from src.dynasty_genius.sources.source_registry import SOURCE_REGISTRY

ROOT = Path(__file__).resolve().parents[1]
ENRICHED_CSV = ROOT / "app" / "data" / "training" / "prospects_with_outcomes_v2.csv"

COVERAGE_THRESHOLD = 0.80
RECENT_SEASONS = set(range(2015, 2026))


def _load_rows() -> list[dict] | None:
    if not ENRICHED_CSV.exists():
        return None
    with ENRICHED_CSV.open() as handle:
        rows = list(csv.DictReader(handle))
    return rows or None


def _present(row: dict, field: str) -> bool:
    return row.get(field, "").strip().lower() not in ("", "null", "nan")


def _coverage(rows: list[dict], field: str) -> tuple[int, int, float]:
    present = sum(1 for row in rows if _present(row, field))
    total = len(rows)
    return present, total, present / total if total else 0.0


@pytest.mark.skipif(
    _load_rows() is None,
    reason="Clean enriched CSV not yet generated — run scripts/enrich_training_data.py first",
)
def test_pp_corrected_target_share_gate_keeps_context_signal_until_threshold():
    """target_share coverage must clear 80% before PP promotion is considered."""
    rows = [
        row for row in _load_rows()
        if int(row["season"]) in RECENT_SEASONS
    ]
    assert rows, "No rows from 2015-2025 seasons in enriched CSV."

    present, total, pct = _coverage(rows, "target_share")
    pp = SOURCE_REGISTRY["playerprofiler"]

    assert pct < COVERAGE_THRESHOLD, (
        f"PlayerProfiler target_share coverage reached {pct:.1%} "
        f"({present}/{total}). Run the PP-inclusive backtest and make an explicit "
        "promotion decision before leaving this gate in Path B mode."
    )
    assert "model_input" not in pp.roles
    assert "context_signal" in pp.roles


@pytest.mark.skipif(
    _load_rows() is None,
    reason="Clean enriched CSV not yet generated — run scripts/enrich_training_data.py first",
)
def test_pp_corrected_breakout_age_wr_te_gate_keeps_context_signal_until_threshold():
    """breakout_age coverage for WR/TE must clear 80% before PP promotion."""
    rows = [
        row for row in _load_rows()
        if int(row["season"]) in RECENT_SEASONS and row.get("position") in ("WR", "TE")
    ]
    assert rows, "No WR/TE rows from 2015-2025 seasons in enriched CSV."

    present, total, pct = _coverage(rows, "breakout_age")
    pp = SOURCE_REGISTRY["playerprofiler"]

    assert pct < COVERAGE_THRESHOLD, (
        f"PlayerProfiler breakout_age WR/TE coverage reached {pct:.1%} "
        f"({present}/{total}). Run the PP-inclusive backtest and make an explicit "
        "promotion decision before leaving this gate in Path B mode."
    )
    assert "model_input" not in pp.roles
    assert "context_signal" in pp.roles


@pytest.mark.skipif(
    _load_rows() is None,
    reason="Clean enriched CSV not yet generated — run scripts/enrich_training_data.py first",
)
def test_pp_corrected_gate_summary(capsys):
    """Informational coverage summary for ledger/CI logs."""
    rows = _load_rows()
    recent = [row for row in rows if int(row["season"]) in RECENT_SEASONS]
    skill = [row for row in recent if row.get("position") in ("WR", "RB", "TE")]
    wr_te = [row for row in recent if row.get("position") in ("WR", "TE")]

    ts_present, ts_total, ts_pct = _coverage(recent, "target_share")
    ba_present, ba_total, ba_pct = _coverage(wr_te, "breakout_age")
    ss_present, ss_total, ss_pct = _coverage(skill, "speed_score")

    print(
        "\nPP Corrected Gate Summary: "
        f"target_share={ts_present}/{ts_total} ({ts_pct:.1%}) | "
        f"breakout_age WR/TE={ba_present}/{ba_total} ({ba_pct:.1%}) | "
        f"speed_score skill={ss_present}/{ss_total} ({ss_pct:.1%})"
    )
    assert True
