/* Auto-generated by scripts/refresh_draft_state.py — do not edit. */
/* Refreshed: 2026-05-10T03:10:58.948271+00:00 · 0 picks taken */
window.DRAFT_STATE = {"taken":[],"draft_id":"1314363401757036544","refreshed_at":"2026-05-10T03:10:58.948271+00:00"};
