-- Step 0.7 mock roster valuation seed.
-- Use only for dev/test end-to-end validation when DYNASTY_SLEEPER_* live values are absent.
-- Every row is explicitly marked source_version = 'mock_step_0_7'.

INSERT INTO gen_alpha.gold.roster_valuation (
  valuation_id,
  valuation_date,
  player_id,
  player_name,
  position,
  nfl_team,
  roster_status,
  age_years,
  dynasty_trajectory,
  asset_tier_status,
  asset_tier_basis,
  qual_dominant_override,
  qual_rationale,
  internal_valuation,
  ktc_market_value,
  ktc_market_updated_at,
  feature_quality_status,
  framework_flags,
  evidence_json,
  source_version,
  calculated_at
)
VALUES
(
  'mock-2026-05-03-ryan-williams',
  DATE '2026-05-03',
  'mock-ryan-williams',
  'Ryan Williams',
  'WR',
  NULL,
  'WATCHLIST',
  20.0,
  'APPRECIATING',
  'CONDITIONAL_TIER_2',
  'Mock Step 0.8: demoted from anchor-tier after verified 2025 production dip; retain as value-arbitrage watch.',
  true,
  'Manual re-tier: legacy freshman hype and market consensus may still price Williams as an anchor, but verified 2025 output supports Conditional Tier-2 until 2026 rebound evidence.',
  6500.0,
  NULL,
  NULL,
  'READY_FOR_MODELING',
  array('qual_dominant_override', 'production_dip', 'conditional_tier_2'),
  '{"source":"mock_step_0_8","verified_context":"PM-approved correction: 2025 production dip; exact live-source ingestion pending"}',
  'mock_step_0_8',
  current_timestamp()
),
(
  'mock-2026-05-03-jonathan-taylor',
  DATE '2026-05-03',
  'mock-jonathan-taylor',
  'Jonathan Taylor',
  'RB',
  'IND',
  'STARTER',
  27.0,
  'CLIFF',
  'LIQUIDATION_TARGET',
  'Mock Step 0.7: RB age-27 cliff asset prioritized for 2027 pick conversion after verified 2025 outlier production.',
  false,
  NULL,
  5200.0,
  7000.0,
  TIMESTAMP '2026-05-03 00:00:00',
  'READY_FOR_MODELING',
  array('age_cliff', '2025_rushing_outlier', 'market_lag_top5_rb', 'priority_2027_1st_conversion'),
  '{"source":"mock_step_0_7","verified_context":"2025: 323 carries, 1585 rushing yards, 18 rushing TD; age 27 per Colts/NFL source check"}',
  'mock_step_0_7',
  current_timestamp()
),
(
  'mock-2026-05-03-davante-adams',
  DATE '2026-05-03',
  'mock-davante-adams',
  'Davante Adams',
  'WR',
  'LAR',
  'STARTER',
  33.0,
  'CLIFF',
  'LIQUIDATION_TARGET',
  'Mock Step 0.7: age-33 WR with verified 2025 touchdown outlier used for sell-high workflow testing.',
  false,
  NULL,
  2800.0,
  4300.0,
  TIMESTAMP '2026-05-03 00:00:00',
  'READY_FOR_MODELING',
  array('age_cliff', '2025_td_outlier', 'sell_high_veteran_wr'),
  '{"source":"mock_step_0_7","verified_context":"2025: 60 receptions, 789 yards, 14 TD per NFL/StatMuse check"}',
  'mock_step_0_7',
  current_timestamp()
),
(
  'mock-2026-05-03-tyreek-hill',
  DATE '2026-05-03',
  'mock-tyreek-hill',
  'Tyreek Hill',
  'WR',
  'FA',
  'BENCH',
  32.0,
  'CLIFF',
  'LIQUIDATION_TARGET',
  'Mock Step 0.7: age-32 free-agent WR with medical/landing-spot gates.',
  false,
  NULL,
  900.0,
  1900.0,
  TIMESTAMP '2026-05-03 00:00:00',
  'READY_FOR_MODELING',
  array('nfl_free_agent', 'medical_clearance_gate', 'distressed_asset'),
  '{"source":"mock_step_0_7","verified_context":"Free agent as of 2026-05-03; ACL/multi-ligament recovery gate"}',
  'mock_step_0_7',
  current_timestamp()
);
