/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardRouteImport } from './routes/board'
import { Route as LeagueRouteImport } from './routes/league'
import { Route as TrackRecordRouteImport } from './routes/track-record'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as ApiPublicHooksRefreshRouteImport } from './routes/api/public/hooks/refresh'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueRoute = LeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRecordRoute = TrackRecordRouteImport.update({
  id: '/track-record',
  path: '/track-record',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshRoute = ApiPublicHooksRefreshRouteImport.update({
  id: '/api/public/hooks/refresh',
  path: '/api/public/hooks/refresh',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/league': typeof LeagueRoute
  '/track-record': typeof TrackRecordRoute
  '/trades': typeof TradesRoute
  '/api/public/hooks/refresh': typeof ApiPublicHooksRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/league': typeof LeagueRoute
  '/track-record': typeof TrackRecordRoute
  '/trades': typeof TradesRoute
  '/api/public/hooks/refresh': typeof ApiPublicHooksRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/league': typeof LeagueRoute
  '/track-record': typeof TrackRecordRoute
  '/trades': typeof TradesRoute
  '/api/public/hooks/refresh': typeof ApiPublicHooksRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/league'
    | '/track-record'
    | '/trades'
    | '/api/public/hooks/refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/league'
    | '/track-record'
    | '/trades'
    | '/api/public/hooks/refresh'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/league'
    | '/track-record'
    | '/trades'
    | '/api/public/hooks/refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  LeagueRoute: typeof LeagueRoute
  TrackRecordRoute: typeof TrackRecordRoute
  TradesRoute: typeof TradesRoute
  ApiPublicHooksRefreshRoute: typeof ApiPublicHooksRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league': {
      id: '/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof LeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-record': {
      id: '/track-record'
      path: '/track-record'
      fullPath: '/track-record'
      preLoaderRoute: typeof TrackRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh': {
      id: '/api/public/hooks/refresh'
      path: '/api/public/hooks/refresh'
      fullPath: '/api/public/hooks/refresh'
      preLoaderRoute: typeof ApiPublicHooksRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  LeagueRoute: LeagueRoute,
  TrackRecordRoute: TrackRecordRoute,
  TradesRoute: TradesRoute,
  ApiPublicHooksRefreshRoute: ApiPublicHooksRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
