"""Build position-level roster need signals from live_roster_cards.json.

Reads resources/live_roster_cards.json (PVO dicts with roster_audit.years_to_cliff).
Aggregates age cliff signals by position:
  HIGH   — ≥2 players at or past cliff (years_to_cliff ≤ 0)
  MEDIUM — ≥1 at cliff, or ≥2 approaching (years_to_cliff == 1)
  LOW    — no cliff signals

Writes resources/roster_need_signals.js: window.ROSTER_NEED = {...};

Usage:
    .venv/bin/python scripts/build_roster_need_signals.py
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

ROSTER_CARDS = ROOT / "resources" / "live_roster_cards.json"
NEED_JS = ROOT / "resources" / "roster_need_signals.js"

SKILL_POSITIONS = ["WR", "RB", "QB", "TE"]


def _classify_position(cards: list[dict], position: str) -> str:
    pos_cards = [c for c in cards if c.get("position") == position]
    at_cliff = 0
    approaching = 0
    for c in pos_cards:
        ra = c.get("roster_audit") or {}
        ytc = ra.get("years_to_cliff")
        if ytc is not None:
            if ytc <= 0:
                at_cliff += 1
            elif ytc == 1:
                approaching += 1
    if at_cliff >= 2:
        return "HIGH"
    if at_cliff >= 1 or approaching >= 2:
        return "MEDIUM"
    return "LOW"


def main() -> None:
    if not ROSTER_CARDS.exists():
        print(f"ERROR: {ROSTER_CARDS} not found. Run build_live_roster.py first.")
        sys.exit(1)

    cards = json.loads(ROSTER_CARDS.read_text())
    need = {pos: _classify_position(cards, pos) for pos in SKILL_POSITIONS}

    ts = datetime.now(timezone.utc).isoformat()
    content = (
        "/* Auto-generated by scripts/build_roster_need_signals.py — do not edit. */\n"
        f"/* Generated: {ts} */\n"
        "window.ROSTER_NEED = "
        + json.dumps(need, separators=(",", ":"))
        + ";\n"
    )
    NEED_JS.write_text(content)
    print(f"Wrote roster_need_signals.js: {need}")


if __name__ == "__main__":
    main()
