"""Build Engine A prospect cards from the mock prospect identity fixture.

Reads resources/mock_prospect_identities_2026_2027.json, assembles a PVO per
prospect (firing Engine A when pick + round + age are all present), and writes:
  - resources/prospect_cards.json   (canonical artifact)
  - resources/prospect_cards.js     (window.PROSPECT_CARDS for dashboard)

2026 draft class prospects with pick + round + age get Engine A scores.
2027 draft class prospects (no pick/round yet) remain PRE_MODEL.

Usage:
    .venv/bin/python scripts/build_prospect_cards.py
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

if load_dotenv:
    load_dotenv(ROOT / ".env")

from src.dynasty_genius.pvo_assembler import assemble_roster_audit

FIXTURE_PATH = ROOT / "resources" / "mock_prospect_identities_2026_2027.json"
CARDS_JSON   = ROOT / "resources" / "prospect_cards.json"
CARDS_JS     = ROOT / "resources" / "prospect_cards.js"
LEAGUE_CTX_PATH = ROOT / "resources" / "david_league_context.json"


def _load_league_context():
    if not LEAGUE_CTX_PATH.exists():
        return None
    from src.dynasty_genius.models.league_context import LeagueContext
    return LeagueContext.load_from_json(LEAGUE_CTX_PATH)


def _write_js(cards: list[dict]) -> None:
    ts = datetime.now(timezone.utc).isoformat()
    js = (
        f"/* Auto-generated by scripts/build_prospect_cards.py — do not edit. */\n"
        f"/* Generated: {ts} · {len(cards)} prospects */\n"
        f"window.PROSPECT_CARDS = "
        + json.dumps(cards, separators=(",", ":"))
        + ";\n"
    )
    CARDS_JS.write_text(js)


def main() -> None:
    if not FIXTURE_PATH.exists():
        print(f"Fixture not found: {FIXTURE_PATH}")
        sys.exit(1)

    league_context = _load_league_context()
    if league_context:
        print(f"Loaded league context: {league_context.league_name}")

    cards = assemble_roster_audit(FIXTURE_PATH, league_context=league_context)

    CARDS_JSON.write_text(json.dumps(cards, indent=2))
    print(f"Wrote {len(cards)} prospect cards → {CARDS_JSON.relative_to(ROOT)}")

    _write_js(cards)
    print(f"Wrote JS artifact         → {CARDS_JS.relative_to(ROOT)}")

    print(f"\n{'Player':<28} {'Pos':<4} {'Age':>4}  {'DVS':>6}  {'Engine':<36}  Grade")
    print("-" * 92)
    for c in sorted(cards, key=lambda x: (
        0 if x.get("dynasty_value_score") is not None else 1,
        -(x.get("dynasty_value_score") or 0),
    )):
        dvs = c.get("dynasty_value_score")
        dvs_str = f"{dvs:.1f}" if dvs is not None else "—"
        age = f"{int(c['age'])}" if c.get("age") is not None else "—"
        engine = c.get("engine_used") or "PRE_MODEL"
        print(
            f"{c['full_name']:<28} {c['position']:<4} {age:>4}  "
            f"{dvs_str:>6}  {engine:<36}  {c['model_grade']}"
        )


if __name__ == "__main__":
    main()
