"""Build Engine A prospect cards from the mock prospect identity fixture.

Reads resources/mock_prospect_identities_2026_2027.json, assembles a PVO per
prospect (firing Engine A when pick + round + age are all present), and writes:
  - resources/prospect_cards.json   (canonical artifact)
  - resources/prospect_cards.js     (window.PROSPECT_CARDS for dashboard)

2026 draft class prospects with pick + round + age get Engine A scores.
2027 draft class prospects (no pick/round yet) remain PRE_MODEL.

Usage:
    .venv/bin/python scripts/build_prospect_cards.py
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

if load_dotenv:
    load_dotenv(ROOT / ".env")

from src.dynasty_genius.pvo_assembler import assemble_roster_audit

FIXTURE_2026 = ROOT / "resources" / "prospect_identity_2026.json"
FIXTURE_2027 = ROOT / "resources" / "mock_prospect_identities_2026_2027.json"
CARDS_JSON   = ROOT / "resources" / "prospect_cards.json"
CARDS_JS     = ROOT / "resources" / "prospect_cards.js"
LEAGUE_CTX_PATH = ROOT / "resources" / "david_league_context.json"


def _load_league_context():
    if not LEAGUE_CTX_PATH.exists():
        return None
    from src.dynasty_genius.models.league_context import LeagueContext
    return LeagueContext.load_from_json(LEAGUE_CTX_PATH)


def _write_js(cards: list[dict]) -> None:
    ts = datetime.now(timezone.utc).isoformat()
    js = (
        f"/* Auto-generated by scripts/build_prospect_cards.py — do not edit. */\n"
        f"/* Generated: {ts} · {len(cards)} prospects */\n"
        f"window.PROSPECT_CARDS = "
        + json.dumps(cards, separators=(",", ":"))
        + ";\n"
    )
    CARDS_JS.write_text(js)


def main() -> None:
    league_context = _load_league_context()
    if league_context:
        print(f"Loaded league context: {league_context.league_name}")

    all_cards = []
    
    # 1. 2026 Class (Verified)
    if FIXTURE_2026.exists():
        print(f"Assembling 2026 cards (verified)...")
        all_cards.extend(assemble_roster_audit(FIXTURE_2026, league_context=league_context))

    # 2. 2027 Class (Mock) - Filtered from combined mock file
    if FIXTURE_2027.exists():
        print(f"Assembling 2027 cards (mock)...")
        mock_cards = assemble_roster_audit(FIXTURE_2027, league_context=league_context)
        # Only keep 2027+ prospects from mock file to avoid duplicates/stale 2026 mocks
        all_cards.extend([c for c in mock_cards if c.get("draft_class", 0) >= 2027])

    if not all_cards:
        print("No prospects found to assemble.")
        sys.exit(0)

    CARDS_JSON.write_text(json.dumps(all_cards, indent=2))
    print(f"Wrote {len(all_cards)} prospect cards → {CARDS_JSON.relative_to(ROOT)}")

    _write_js(all_cards)
    print(f"Wrote JS artifact         → {CARDS_JS.relative_to(ROOT)}")

    print(f"\n{'Player':<28} {'Pos':<4} {'Age':>4}  {'DVS':>6}  {'Engine':<36}  Grade")
    print("-" * 92)
    for c in sorted(all_cards, key=lambda x: (
        0 if x.get("dynasty_value_score") is not None else 1,
        -(x.get("dynasty_value_score") or 0),
    )):
        dvs = c.get("dynasty_value_score")
        dvs_str = f"{dvs:.1f}" if dvs is not None else "—"
        age = f"{int(c['age'])}" if c.get("age") is not None else "—"
        engine = c.get("engine_used") or "PRE_MODEL"
        print(
            f"{c['full_name']:<28} {c['position']:<4} {age:>4}  "
            f"{dvs_str:>6}  {engine:<36}  {c['model_grade']}"
        )


if __name__ == "__main__":
    main()
