"""Build live Roster Audit cards from David's real Sleeper roster.

Fetches the live roster, assembles a PVO per player (with real age and
roster-context data), writes:
  - resources/live_roster_cards.json   (canonical artifact)
  - resources/roster_audit_cards.js    (window.ROSTER_AUDIT_CARDS for dashboard)

Usage:
    .venv/bin/python scripts/build_live_roster.py
"""

from __future__ import annotations

import asyncio
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

if load_dotenv:
    load_dotenv(ROOT / ".env")

from app.services.roster_auditor import get_my_roster, RosterConfigError
from src.dynasty_genius.identity import generate_dg_id
from src.dynasty_genius.models.league_context import LeagueContext
from src.dynasty_genius.models.player_identity import PlayerIdentity
from src.dynasty_genius.pvo_assembler import assemble_pvo

CARDS_JSON = ROOT / "resources" / "live_roster_cards.json"
CARDS_JS   = ROOT / "resources" / "roster_audit_cards.js"
LEAGUE_CTX_PATH = ROOT / "resources" / "david_league_context.json"


def _load_league_context() -> Optional[LeagueContext]:
    """Load David's league context from JSON."""
    if not LEAGUE_CTX_PATH.exists():
        return None
    return LeagueContext.load_from_json(LEAGUE_CTX_PATH)


def _build_cards(players: list[dict], league_context: Optional[LeagueContext]) -> list[dict]:
    cards = []
    for p in players:
        identity = PlayerIdentity(
            dg_id=generate_dg_id(p["full_name"], p["position"]),
            full_name=p["full_name"],
            position=p["position"],
            nfl_team=p.get("team"),
            age=None,
        )
        features = {"age": float(p["age"]) if p.get("age") is not None else None}
        pvo = assemble_pvo(
            identity, features, is_prospect=False, league_context=league_context
        )
        cards.append(pvo.model_dump())
    return cards


def _write_js(cards: list[dict]) -> None:
    ts = datetime.now(timezone.utc).isoformat()
    js = (
        f"/* Auto-generated by scripts/build_live_roster.py — do not edit. */\n"
        f"/* Generated: {ts} · {len(cards)} players */\n"
        f"window.ROSTER_AUDIT_CARDS = "
        + json.dumps(cards, separators=(",", ":"))
        + ";\n"
    )
    CARDS_JS.write_text(js)


async def main() -> None:
    league_context = _load_league_context()
    if league_context:
        print(f"Loaded league context for: {league_context.league_name}")

    print("Fetching roster from Sleeper…")
    try:
        players = await get_my_roster(league_context)
    except RosterConfigError as e:
        print(f"Config error: {e}")
        sys.exit(1)

    print(f"Fetched {len(players)} players. Assembling PVOs…")
    cards = _build_cards(players, league_context)

    CARDS_JSON.write_text(json.dumps(cards, indent=2))
    print(f"Wrote {len(cards)} cards  → {CARDS_JSON.relative_to(ROOT)}")

    _write_js(cards)
    print(f"Wrote JS artifact    → {CARDS_JS.relative_to(ROOT)}")

    print(f"\n{'Player':<28} {'Pos':<4} {'Age':>4}  {'Cliff':<18}  {'Liquidity':<30}  Signal")
    print("-" * 95)
    for c in sorted(cards, key=lambda x: (
        {"past_cliff": 0, "at_cliff": 1, "approaching_cliff": 2, "no_age_signal": 3}.get(
            (x.get("roster_audit") or {}).get("signal", "no_age_signal"), 3
        ),
        (x.get("roster_audit") or {}).get("years_to_cliff", 99) or 99,
    )):
        ra  = c.get("roster_audit") or {}
        age = str(int(c["age"])) if c.get("age") is not None else "—"
        liq = ra.get("liquidity_risk") or "—"
        print(
            f"{c['full_name']:<28} {c['position']:<4} {age:>4}  "
            f"{ra.get('signal','—').replace('_',' '):<18}  {liq:<30}  "
            f"{c['signal_completeness']:.0%}"
        )


if __name__ == "__main__":
    asyncio.run(main())
