"""Fetch Sleeper draft picks and write resources/draft_state.js.

Env vars:
  DYNASTY_SLEEPER_DRAFT_ID   — if set, used directly (no discovery call)
  DYNASTY_SLEEPER_LEAGUE_ID  — fallback: discovers active draft from league

If no active draft is found, writes an empty taken list with a no_active_draft flag.

Usage:
    .venv/bin/python scripts/refresh_draft_state.py
    ! .venv/bin/python scripts/refresh_draft_state.py   (from Claude Code prompt)
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

try:
    from dotenv import load_dotenv
    load_dotenv(ROOT / ".env")
except ImportError:
    pass

from app.data.sleeper import get_draft, get_draft_picks, get_league_drafts

DRAFT_STATE_JS = ROOT / "resources" / "draft_state.js"


def _write_state(
    taken: list[str],
    draft_id,
    caveat=None,
    draft_status=None,
    last_picked=None,
    total_picks=None,
    current_pick_no=None,
) -> None:
    ts = datetime.now(timezone.utc).isoformat()
    payload: dict = {"taken": taken, "draft_id": draft_id, "refreshed_at": ts}
    if caveat:
        payload["caveat"] = caveat
    if draft_status is not None:
        payload["draft_status"] = draft_status
    if last_picked is not None:
        payload["last_picked"] = last_picked
    if total_picks is not None:
        payload["total_picks"] = total_picks
    if current_pick_no is not None:
        payload["current_pick_no"] = current_pick_no
    content = (
        "/* Auto-generated by scripts/refresh_draft_state.py — do not edit. */\n"
        f"/* Refreshed: {ts} · {len(taken)} picks taken */\n"
        "window.DRAFT_STATE = "
        + json.dumps(payload, separators=(",", ":"))
        + ";\n"
    )
    DRAFT_STATE_JS.write_text(content)
    print(f"Wrote draft_state.js — {len(taken)} taken, status={draft_status}, draft_id={draft_id}")


async def _find_draft_id():
    draft_id = os.environ.get("DYNASTY_SLEEPER_DRAFT_ID")
    if draft_id:
        print(f"Using DYNASTY_SLEEPER_DRAFT_ID override: {draft_id}")
        return draft_id

    league_id = os.environ.get("DYNASTY_SLEEPER_LEAGUE_ID")
    if not league_id:
        raise ValueError(
            "Set DYNASTY_SLEEPER_DRAFT_ID or DYNASTY_SLEEPER_LEAGUE_ID in .env"
        )

    drafts = await get_league_drafts(league_id)
    if not drafts:
        print("No drafts found for league — writing empty state.")
        return None

    active = [d for d in drafts if d.get("status") in ("drafting", "active")]
    pool = active if active else drafts
    pool.sort(key=lambda d: d.get("created", 0), reverse=True)

    print(f"Found {len(drafts)} draft(s):")
    for d in pool:
        print(f"  draft_id={d['draft_id']} status={d.get('status')} created={d.get('created')}")

    selected = pool[0]["draft_id"]
    print(f"Selected: {selected}")
    return selected


async def main() -> None:
    draft_id = await _find_draft_id()
    if draft_id is None:
        _write_state([], None, caveat="no_active_draft")
        return

    draft_meta, picks = await asyncio.gather(
        get_draft(draft_id),
        get_draft_picks(draft_id),
    )

    taken = [str(pick["player_id"]) for pick in picks if pick.get("player_id")]

    draft_status = draft_meta.get("status") if draft_meta else None
    settings = (draft_meta or {}).get("settings", {})
    rounds = settings.get("rounds") or 0
    teams = settings.get("teams") or 0
    total_picks = (rounds * teams) if (rounds and teams) else None
    current_pick_no = len(picks)

    last_picked = None
    if picks:
        last_pick = max(picks, key=lambda p: p.get("pick_no") or 0)
        meta = last_pick.get("metadata") or {}
        last_picked = {
            "pick_no": last_pick.get("pick_no"),
            "player_id": str(last_pick.get("player_id", "")),
            "full_name": (meta.get("first_name", "") + " " + meta.get("last_name", "")).strip(),
            "position": meta.get("position", ""),
        }

    _write_state(
        taken, draft_id,
        draft_status=draft_status,
        last_picked=last_picked,
        total_picks=total_picks,
        current_pick_no=current_pick_no,
    )


if __name__ == "__main__":
    asyncio.run(main())
