"""Fetch Sleeper draft picks and write resources/draft_state.js.

Env vars:
  DYNASTY_SLEEPER_DRAFT_ID   — if set, used directly (no discovery call)
  DYNASTY_SLEEPER_LEAGUE_ID  — fallback: discovers active draft from league

If no active draft is found, writes an empty taken list with a no_active_draft flag.

Usage:
    .venv/bin/python scripts/refresh_draft_state.py
    ! .venv/bin/python scripts/refresh_draft_state.py   (from Claude Code prompt)
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

try:
    from dotenv import load_dotenv
    load_dotenv(ROOT / ".env")
except ImportError:
    pass

from app.data.sleeper import get_draft_picks, get_league_drafts

DRAFT_STATE_JS = ROOT / "resources" / "draft_state.js"


def _write_state(taken: list[str], draft_id, caveat=None) -> None:
    ts = datetime.now(timezone.utc).isoformat()
    payload: dict = {"taken": taken, "draft_id": draft_id, "refreshed_at": ts}
    if caveat:
        payload["caveat"] = caveat
    content = (
        "/* Auto-generated by scripts/refresh_draft_state.py — do not edit. */\n"
        f"/* Refreshed: {ts} · {len(taken)} picks taken */\n"
        "window.DRAFT_STATE = "
        + json.dumps(payload, separators=(",", ":"))
        + ";\n"
    )
    DRAFT_STATE_JS.write_text(content)
    print(f"Wrote draft_state.js — {len(taken)} taken picks, draft_id={draft_id}")


async def _find_draft_id():
    draft_id = os.environ.get("DYNASTY_SLEEPER_DRAFT_ID")
    if draft_id:
        print(f"Using DYNASTY_SLEEPER_DRAFT_ID override: {draft_id}")
        return draft_id

    league_id = os.environ.get("DYNASTY_SLEEPER_LEAGUE_ID")
    if not league_id:
        raise ValueError(
            "Set DYNASTY_SLEEPER_DRAFT_ID or DYNASTY_SLEEPER_LEAGUE_ID in .env"
        )

    drafts = await get_league_drafts(league_id)
    if not drafts:
        print("No drafts found for league — writing empty state.")
        return None

    active = [d for d in drafts if d.get("status") in ("drafting", "active")]
    pool = active if active else drafts
    pool.sort(key=lambda d: d.get("created", 0), reverse=True)

    print(f"Found {len(drafts)} draft(s):")
    for d in pool:
        print(f"  draft_id={d['draft_id']} status={d.get('status')} created={d.get('created')}")

    selected = pool[0]["draft_id"]
    print(f"Selected: {selected}")
    return selected


async def main() -> None:
    draft_id = await _find_draft_id()
    if draft_id is None:
        _write_state([], None, caveat="no_active_draft")
        return

    picks = await get_draft_picks(draft_id)
    taken = [str(pick["player_id"]) for pick in picks if pick.get("player_id")]
    _write_state(taken, draft_id)


if __name__ == "__main__":
    asyncio.run(main())
