import type { LeaguePulseResponse } from "../lib/api";

export function leaguePulseResponse(
  overrides: Partial<LeaguePulseResponse> = {},
): LeaguePulseResponse {
  return {
    captured_at: "2026-06-22T18:00:00Z",
    card_section_counts: [
      {
        decision_supported: false,
        section_cap: 20,
        shown_count: 1,
        sort_key: "absolute_model_market_delta_desc",
        total_count: 7,
      },
      {
        decision_supported: false,
        section_cap: 20,
        shown_count: 1,
        sort_key: "positional_z_differential_desc",
        total_count: 3,
      },
    ],
    caveats: ["league_pulse_artifact_state_2026-06-22"],
    decision_supported: false,
    dropped: {
      market_overlay_cards: 0,
      model_native_cards: 0,
      partner_rankings: 0,
      roster_capacity_candidate_pools: 0,
      team_postures: 0,
      team_values: 0,
      decision_supported: false,
    },
    market_overlay_cards: [
      {
        card_id: "market-1",
        card_type: "UNROSTERED_MODEL_MARKET_DIVERGENCE",
        caveats: ["market_overlay_unvalidated_divergence"],
        decision_supported: false,
        evidence: {
          asset_xvar: 1.4,
          evidence_status: "evidence_complete",
          lineup_role: "bench",
          market_percentile: 42,
          model_minus_market_delta: 0.18,
          model_percentile: 71,
          signal: "MODEL_HIGH_MARKET_LOW",
        },
        evidence_status: "evidence_complete",
        rationale_primary: "market_overlay_context_only",
        rationale_secondary: ["market_overlay_unvalidated_divergence"],
        roster_capacity_candidates: {
          caveats: [],
          decision_supported: false,
          items: [
            {
              capacity_conflict_status: "roster_capacity_pressure",
              caveats: [],
              decision_supported: false,
              dvs: -0.7,
              full_name: "Depth WR",
              position: "WR",
              sleeper_player_id: "drop-1",
              value_status: "valued",
              xvar_pct: 0.11,
            },
          ],
          narrowing_rule: "all_safe_candidates",
          pool_status: "available",
          selection_rule: "descriptive_candidate_pool_no_tool_selection",
          sort_key: "xvar_pct_ascending_then_full_name_then_sleeper_player_id",
        },
        score_components: {
          divergence_score: 0.7,
          feasibility_score: 0.5,
          fit_score: 0.4,
        },
        sort_key: "absolute_model_market_delta_desc",
        sort_value: 0.18,
      },
    ],
    model_native_cards: [
      {
        card_id: "model-1",
        card_type: "ROSTER_SURPLUS_DEFICIT_MATCH",
        caveats: [],
        decision_supported: false,
        evidence: {
          counterparty_position_z: 0.9,
          counterparty_surplus_label: "surplus",
          position: "RB",
          positional_z_differential: 1.6,
          perspective_position_z: -0.7,
          perspective_surplus_label: "deficit",
        },
        evidence_status: "evidence_complete",
        rationale_primary: "positional_differential",
        rationale_secondary: ["counterparty_fit"],
        score_components: {
          feasibility_score: 0.6,
          fit_score: 0.8,
        },
        sort_key: "positional_z_differential_desc",
        sort_value: 1.6,
      },
    ],
    partner_rankings: [
      {
        counterparty_roster_id: 2,
        counterparty_team_name: "Team Two",
        caveats: ["partner_score_market_influenced"],
        decision_supported: false,
        evidence: {
          counterparty_posture: "REBUILDING",
          divergence_row_count: 3,
          perspective_posture: "CONTENDER",
          position_scores: {
            QB: 0.1,
            RB: 0.8,
            TE: 0.2,
            WR: 0.3,
          },
        },
        market_influenced: true,
        matched_positions: ["RB"],
        partner_score: 0.74,
        score_components: {
          activity_recency_score: 0.2,
          complementarity_score: 0.8,
          divergence_density_score: 0.5,
          posture_alignment_score: 0.6,
        },
      },
    ],
    perspective_roster_id: 1,
    source_artifacts: {
      decision_supported: false,
      league_opportunity: { schema_version: "league_opportunity.v2" },
      team_posture: { schema_version: "team_posture.v1" },
      team_value_matrix: { schema_version: "team_value_matrix.v1" },
    },
    status: "degraded",
    team_postures: [
      {
        roster_id: 1,
        team_name: "David",
        posture_label: "CONTENDER",
        score: 0.7,
        components: {
          age_window_score: 0.4,
          development_stash_score: 0.1,
          early_pick_balance_score: 0.2,
          starter_weighted_xvar_z: 1.1,
        },
        caveats: [],
        decision_supported: false,
      },
    ],
    team_values: [
      {
        roster_id: 1,
        team_name: "David",
        age_profile: {
          median_age: 25,
          pct_value_over_28: 0.22,
          value_weighted_age: 25.4,
        },
        decision_supported: false,
        future_picks: {
          outgoing_count: 1,
          owned_count: 7,
          pick_value_status: "unvalued",
        },
        positional_summary: {
          QB: { surplus_label: "balanced", z_score: 0.4 },
          RB: { surplus_label: "deficit", z_score: -0.3 },
          TE: { surplus_label: "balanced", z_score: 0.1 },
          WR: { surplus_label: "surplus", z_score: 0.8 },
        },
        value_views: {
          decision_supported: false,
          depth_credit_xvar: 1.2,
          lineup_xvar: 7.9,
          starter_weighted_xvar: 8.4,
          top_n_xvar: 8.6,
          total_xvar_capped: 9.1,
        },
      },
    ],
    ...overrides,
  };
}
